### ISSUE TITLE
Missing anchor in the link to "Paging" section of the Presentation API

### ISSUE THREAD

**Issue by regisrob** [IIIF/api#1006]
In section ["3.3.2. Paging Results"](http://iiif.io/api/search/1.0/#paging-results) of the Search API 1.0, the link on "paging features" should point to the right section of the P-API 2.1 (i.e. http://iiif.io/api/presentation/2.1/#paging)

**Comment by azaroth42** [comment]
We either did this or we missed it, but the ship has sailed. Closing.
