### ISSUE TITLE
Add palette service to annex

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1011]
We should add a reference to @workergnome's http://palette.davidnewbury.com/ service to the services annex.

**Comment by zimeon** [comment]
I agree. I think a little additional work is needed to think about whether we define the meaning of the palette data beyond "output of  `http://palette.david.newbury.com?url=<IMAGE_API_ID>`". If not, then do we get into possible awkward questions of what to include/not-include down the road?

**Comment by workergnome** [comment]
Happy and interested in thinking through norms around defining services. 
Right now, I have a profile:
http://palette.davidnewbury.com/vocab/iiifpal.ttl
a context:
http://palette.davidnewbury.com/vocab/context.json
And an example defined. What else could be useful?

- David Newbury
-----------------------------------
p. (773) 547-2272
e. david.newbury@gmail.com




On Wed, Dec 21, 2016 at 1:03 PM -0500, "Simeon Warner" <notifications@github.com> wrote:












I agree. I think a little additional work is needed to think about whether we define the meaning of the palette data beyond "output of  http://palette.david.newbury.com?url=<IMAGE_API_ID>". If not, then do we get into possible awkward questions of what to include/not-include down the road?

**Comment by zimeon** [comment]
The big question to me is how should "what the service does" be described? The key part in your description is:

```
iiifpal:Palette a owl:Class ;
  rdfs:comment "This represents an palette extracted from the image." .
```

Perhaps a very general description like that is right. But then, should any other palette generation service (perhaps even a very dumb one that returns all colors in an image) use the same profile URI? Or should this profile be specific to your algorithm/service? If it is general, should IIIF adopt it and you say you conform to it? (sounds a bit too centralized unless there would be widespread reuse) I'm just asking questions because I'm really not sure what approach is best...

**Comment by workergnome** [comment]
I agree that's the question, and this service is definitely a stalking
horse for this conversation.

My personal opinion is that in defining a service, I'm offering up a
JSON-LD metadata format that IIIF clients can choose to interpret or not.
I don't think I'm defining IIIF Palettes—certainly not at this point.  I'm
defining "David Newbury's Palette Service", which is a *profile* and a *context
*that describe that JSON-LD metadata.

I've also created a server that can generate that metadata from an image
represented by a IIIF Image API endpoint, and a client that can consume
IIIF Image API endpoints that publish this service, but those are
nice-to-haves, not need-to-haves.  (Maybe they're need-to-haves from the
standpoint of IIIF adoption or recommendation—I don't know.)

I think of the Service Annex as a slightly more formal version of Awesome
IIIF, in that they're *recommendations* from the IIIF community as
specifically useful, well-tested additions that clients MAY support.  I
could define my own geography service, and use it, and it wouldn't break
anything, but if I use IIIF's recommendation clients beyond my own are more
likely to adopt it.

Maybe the distinction I'm making here is that Services are client
extensions, and what's really interesting is which *clients* support them,
whereas profiles are *server* extensions.  Neither of them are IIIF *API*
extensions except that they're using the built-in, defined mechanisms for
extending IIIF.


That being said, I think that the IIIF community should develop a set of
suggestions (norms?) for how to publish extensions like this.  The
mechanisms are in the API, but I don't know if anyone knows how to use
them, yet.


- David Newbury
-----------------------------------
p. (773) 547-2272
e. david.newbury@gmail.com

**Comment by azaroth42** [comment]
@workergnome Given the new registries and better understanding in Prezi3 of service vs extension vs seeAlso vs Annotation ... is this still an issue, or should we close?

**Comment by workergnome** [comment]
Happy to close.  I think we understand what's needed here--and once we know how to submit entries to the registry, we can reopen this particular one.
