### ISSUE TITLE
Make painting annos MUST for `@id`

### ISSUE THREAD

**Issue by jkeck** [IIIF/api#1019]
We are creating an interface in Spotlight that will allow users to save a cropping of a IIIF backed image resource for use around their exhibit. We will be storing `@id`s from the given IIIF manifest down to the annotation level in order to support canvases with multiple painting annotations.  We will be storing the service `@id` as well for performance reasons. We want to store the annotation `@id` so that we can re-construct the service `@id` (and cropped image url) for the correct image resource in the case of a file renaming, sequence change, etc.  If we encounter multiple painting annotations in a canvas without IDs at present we will need to simply need to select the first.

From #456
@azaroth42: Will you be providing access to the annotations themselves via their URIs as well?

@jkeck: not planning on it currently, although we may reconsider that if they were MUST and required to be dereferenced.

@azaroth42: Then I don't see the interoperability requirement for having identifiers for the painting annotations? What is someone other than your own system going to do with them? There's no problem with having them, but why should everyone be required to create and maintain them?

**Comment by jkeck** [comment]
What would the suggested way be to ensure we are referencing the correct annotation when there are multiple in the same canvas?  Without an `@id` we're planning on simply bailing and using the first.

**Comment by azaroth42** [comment]
Discuss in Toronto at the same time as #880.

**Comment by azaroth42** [comment]
Proposal:  Unless the use case requires an *external* reference, there's no requirement for a URI on a painting annotation. Handling of node references in the JSON by a viewer doesn't need specification changes. Need this use case, otherwise close wontfix.

**Comment by azaroth42** [comment]
Note to self:  Currently v3 doc says MUST for all annotations. Need to distinguish in docs.

**Comment by azaroth42** [comment]
Revised proposal: The web annotation model requires id on Annotations. Thus any annotation that does not have an id is not a valid web annotation.  Thus we should require id on all annotations, painting or otherwise.

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting that `@id` is required in order to follow the web annotation model

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#id
