### ISSUE TITLE
Update editorial process to include mention of WGs

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1060]
The [Community Process](http://iiif.io/api/annex/notes/editors/#community-process) section of the [IIIF Editorial Process](http://iiif.io/api/annex/notes/editors/) document should be reworked a little to include mention of WGs as defined in [IIIF Groups Framework](http://iiif.io/community/groups/framework/). Should probably also mention how we arrive at decisions - strive for consensus through discussion.

**Comment by azaroth42** [comment]
This is done, isn't it?

**Comment by azaroth42** [comment]
(Yes it's done, closing)

**Comment by zimeon** [comment]
Belated agreement, it is done
