### ISSUE TITLE
Prezi 3 / Image 2 requires id and @id :(

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1064]
Document this in the Presentation API.

**Comment by azaroth42** [comment]
Related to #518 about cross-version weirdness

**Comment by ndushay** [comment]
yes, yes it does.  bumped into this.  😿

**Comment by azaroth42** [comment]
Noting that this is a worse scenario than the `rights` / `license` issue, as for that one (#644) there are two explicit context definitions.  Here we have an alias (`id`), and nothing (raw use of `@id`) ... so the alias will always trump the lack of a definition.  This doesn't matter for consumption via JSON-LD aware processors, but it will prevent the creation of the right JSON by a JSON-LD based toolchain -- the compaction will always prefer the `id` form, and you can't "unset" it.

**Comment by azaroth42** [comment]
As there's nothing we can do to solve this, re-tagging as editorial.

**Comment by azaroth42** [comment]
I've raised the issue for JSON-LD 1.1 to allow explicitly zeroing out a context definition:
https://github.com/json-ld/json-ld.org/issues/546

**Comment by azaroth42** [comment]
Closed by #1301
