### ISSUE TITLE
Add language property for external resources

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1065]
For example to say that an audio file referred to from an annotation is in English.

Should be available for any external content bearing resource (audio, video, ...) and AnnotationLists [as representation of subtitles, etc], and Layers [as cross-canvas grouping mechanism for AnnotationLists].

**Comment by glenrobson** [comment]
Thinking about our Newspapers what does not having the language tag say? Does it mean unknown language. 

For some titles we know they are English or Welsh. Others we know are mixed Welsh and English but we don't know which specific articles are in a particular language.

**Comment by zimeon** [comment]
To mirror as much as possible the sort of logic used for [language on labels in prezi](http://iiif.io/api/presentation/2.1/#language-of-property-values), I think no language would mean no language based selection should be applied. This is pretty close to unknown and certainly appropriate in the case that the language is unknown.

**Comment by azaroth42** [comment]
While it seems easy to do, we should consider implementation status and utility. 
Discuss in Toronto.

**Comment by azaroth42** [comment]
Web Annotations cover the content resource description of language already, which would become editorial for the cookbook.

However, internal references such as `related`, `rendering`, `rights` etc could still benefit from this feature.

**Comment by zimeon** [comment]
:+1: to add `language` property (use is optional) at Toronto WG meeting

**Comment by azaroth42** [comment]
Closed by #1308
