### ISSUE TITLE
Define URI for JSON-LD media type profile for IIIF Prezi

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1066]
Considerations:

* One profile [per `protocol`]
* One per version of Presentation API [per `@context`]
* One per version per class [per ontology]

Useful for content negotiation and determining what you've found, beyond JSON.

(From @ahankinson)

**Comment by azaroth42** [comment]
For example:

```
Content-Type:  application/ld+json;profile="http://iiif.io/api/presentation/2/context.json"
```

**Comment by zimeon** [comment]
Should this be `profiles` in example above, per [RFC6381](https://tools.ietf.org/html/rfc6381)?

**Comment by azaroth42** [comment]
Nope, the media type definition is singular:  http://www.iana.org/assignments/media-types/application/ld+json

**Comment by zimeon** [comment]
Ah, thanks, was trying to find ref... is RFC6381 dead? Or is this a weird situation where there is a general `profiles` and a JSON-LD specific `profile`?

**Comment by azaroth42** [comment]
I think RFC6381 over-reaches by attempting to assert a parameter on media types outside of its scope. Parameters are defined by the registration of the media type, per IANA process, so `profile` is the correct one for JSON-LD.

**Comment by azaroth42** [comment]
Proposal to ratify:  Use the context document's URI as the profile for the media type. e.g.
> `application/ld+json;profile="http://iiif.io/api/presentation/2/context.json"`

**Comment by glenrobson** [comment]
So the text in the image api (for compliance) suggests using the `Link` header:

"The compliance level URI may also be given in the HTTP Link header (RFC5988) with the parameter rel="profile", and thus a complete header might look like:

```Link: <http://iiif.io/api/image/2/level1.json>;rel="profile"```

from: http://iiif.io/api/image/2.1/#compliance-levels is this related to the above discussion?

**Comment by christopher-johnson** [comment]
Using `Link` to specify `#context` relations is not allowed for `application/ld+json` Content-Types per [6.8](https://json-ld.org/spec/latest/json-ld/#interpreting-json-as-json-ld) of  JSON-LD 1.1 spec.  The Image API 2.1.1 spec works around this by allowing one to Link a context document but not using the json-ld vocabulary #context relation.  imo, this is not useful.  An `@context` document is defined by the json-ld vocabulary first, and not by the generic `profile` relation.  A server or client processor should have a meaningful hint before it dereferences a Link header (if that is what is intended by its use) and the `profile` relation does not provide that.  One limitation of @azaroth42 proposal above is that one cannot additionally specify a shape (as defined in the [JSON-LD vocabulary](https://www.w3.org/ns/json-ld#expanded)) for the document itself, which is AFAIK how JSON-LD prefers to use `Content-Type profile`

**Comment by azaroth42** [comment]
Done:  http://prezi3.iiif.io/api/presentation/3.0/#responses

**Comment by christopher-johnson** [comment]
`Content-Type` with `profile` is also applicable to writeable request interaction.  For example, if a client needs to `PUT` a IIIF Manifest to an LDP server, it could specify `Content-Type: application/ld+json;profile="http://iiif.io/api/presentation/3/context.json"`.   `Content-Type` is an important header for clients to provide to differentiate between RDF and Non-RDF Sources for writes.  It should also be possible, for a server to extract a profile from such a request and store it as a Link relation to the document.   

Not sure how useful it is for a server to respond with a "mandatory" Content-Type profile, since the client _could_ provide its preference for a JSON-LD serialization profile type with an Accept header.  For example, a client that did not support a v3 API would only Accept a v2.1 serialization profile.

**Comment by azaroth42** [comment]
The IIIF Community has continually and explicitly deferred discussion on create, update and delete of resources (aka REST).

**Comment by christopher-johnson** [comment]
It seems then that the IIIF Community is led by data Consumers, and not Producers.  It is mystifying to me how standardizing a process for generating annotations is not central to the community agenda.  I suppose that REST support is a question of infrastructure, yet with "Interoperability", one could assume the IIIF to advance more than a monolithic standardized serialization for a client Consumer.

**Comment by azaroth42** [comment]
I think it's led by Producers with custom non RDF based toolchains and workflows, that then need to cater to the Consumers so there's something useful done with the results. 

That said, REST for Annotations is already a solved problem:  https://www.w3.org/TR/annotation-protocol/
