### ISSUE TITLE
Add duration to canvas, make spatial dimensions optional when duration specified

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1069]
See IIIF/iiif-av#15 . For handling audio and video we need to add a temporal dimension to the canvas. For the audio-only case it should not be necessary to have a `width` and `height`.

**Comment by tomcrane** [comment]
AV call 25/7/2017 - Are there defaults for canvas dimensions?

**Comment by tomcrane** [comment]
AV call - approved

**Comment by jpstroop** [comment]
Toronto WG Plenary: 👍

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#duration

**Comment by mikeapp** [comment]
👍 agree done, closing
