### ISSUE TITLE
Define JSON-LD profile URI for Image info.json

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1090]
cf #1066 and azaroth42/museum-lod#7. 

Propose the context document URI.

**Comment by tomcrane** [comment]
Compare with Prezi API at http://prezi3.iiif.io/api/presentation/3.0/#responses

**Comment by azaroth42** [comment]
Agreement on community call of 2018-01-31.

**Comment by azaroth42** [comment]
Closed by #1428
