### ISSUE TITLE
Upstream: Context attempts to redefine JSON-LD keywords @id, @type

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1106]
See this issue, which we have too:
https://github.com/w3c/web-annotation/issues/421

Mea culpa.

As the context is not normative nor semantically versioned, I propose we fix it in our context documents before the misunderstanding goes further.

**Comment by azaroth42** [comment]
Discussion 08/30:  We should fix for 2.1 as it's not semantically versioned. (re-milestoning)

**Comment by zimeon** [comment]
:+1: on the fix in Presentation 3.0, I don't think this applies to Presentation 2.x as we don't in http://iiif.io/api/presentation/2/context.json attempt to redefine `@id`, `@type`

**Comment by azaroth42** [comment]
Closing as this is pretty much just a mental note to Rob to not mess it up again.
