### ISSUE TITLE
If property can ever have multiple values, require a JSON array

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1131]
From this thread:
> https://groups.google.com/forum/?hl=en#!topic/iiif-discuss/ihQ3nHanh8Y

The proposal is to force all properties that can have multiple values to always be an array, in all APIs.
In the Presentation API, this would be: `label, metadata, description, thumbnail, attribution, rights, logo, type, viewingHint, related, rendering, service, seeAlso, within`

This is done in JSON-LD by adding `@container: @set` into the context document for those properties.

Note however that JSON-LD 1.0 currently prevents us from doing it for the values of LanguageMaps:
> https://github.com/json-ld/json-ld.org/issues/407
> https://github.com/IIIF/iiif.io/issues/755

But this is fixed in 1.1 (c.f. #1192) 

An example from @workergnome:
> http://evil-manifests.davidnewbury.com/iiif/garden/everything_a_list.json

**Comment by azaroth42** [comment]
I am :+1: on the proposal, other than for type which I think we should require be 1:1. Constantly type checking values to see if they're a list or a value is painful and results in hard to find bugs. Note that the current validator even incorrectly errors on the everything_a_list manifest.

**Comment by tomcrane** [comment]
:+1: too. Currently `@list` property names are plural (e.g., canvases) or mass nouns (e.g., otherContent), but I think the `@set` property names should remain singular:

```
"label": [ "one label", "another label"] 
```

not

```
"labels": [ "one label", "another label"] 
```

**Comment by workergnome** [comment]
Agree with @tomcrane on nouns remaining as they are, if only for backwards compatibility.

re: `type`:  I think about CRM integration, for instance, and, say: http://linked.art/model/object/digital/#iiif-manifests

```
{
    "id": "http://iiif.example.org/presentation/1/manifest.json", 
    "type": "InformationObject", 
    "conforms_to": "http://iiif.io/api/presentation", 
    "format": "application/ld+json;profile=\"http://iiif.io/api/presentation/2/context.json\""
  }

**Comment by azaroth42** [comment]
Following this pattern, and #1147 / #1176, we should also define an absolute format for first/last/next/prev references.  If we ever allow more than just the URI, then they should always be a JSON object, requiring at least two properties (id and something else).

(Reason for 2 properties being that JSON-LD will compact {"id": "foo"} to just "foo")

**Comment by workergnome** [comment]
My preference would be to explicitly limit them to 1:1 URIs.

**Comment by azaroth42** [comment]
General agreement, and noted that type/@type and @context are special cases.

**Comment by christopher-johnson** [comment]
Good proposal.  https://github.com/IIIF/iiif.io/issues/994.

**Comment by zimeon** [comment]
I note that the addition of `@container: @set` in the context to define this behavior means that the change won't introduce any problems serializing from RDF.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting

**Comment by azaroth42** [comment]
Done throughout.

**Comment by azaroth42** [comment]
Tagging principles so we can document it as a design pattern.

**Comment by azaroth42** [comment]
Removing image, via #1433
