### ISSUE TITLE
Legal to summarize Lists?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1144]
In a Collection of Manifests, where the intended representation lets you drill down into parts of the collected Manifests, I'd like to have the important ranges for navigation in the collection document for ease of access, and a hint to the viewer I'd like them to be rendered.

However the AV group has agreed that all parts of the resource must be represented in the Ranges, if there are any.  Does that apply to Manifests as documents (e.g. I can do it), or Manifests as "things" that might be summarized in Collections (e.g. I can't do it)?  This will take effect in 3.0, but today the question still has implications in 2.x because ...

It becomes a bit more subtle than some of the other properties ... we can leave out `sequences` completely, or `rights` or whatever ... but `structures` is a `@type:@list`, meaning that if a system were treating everything as triples in a global pool, there would be two different Lists, one summary from the Collection and one complete from the Manifest. Following from our design principles:

> It should be possible to transform representations back and forth between triples and the JSON-LD serialization without loss, but not necessarily without the use of custom code.

This would _not_ be round-trippable once you take into account multiple documents.

**Comment by azaroth42** [comment]
Clarification from discussion 7/5 call:  The assumption in the issue is that the structures reported in the collection might be a subset of the structures presented in the manifest.  Thus the information in the structures would not be completely identical.

Agreement from call: The functionality is very valuable, so having a method to achieve this would be useful. The actual restriction needed for the round-trip is that all of the items in any given list must be consistent in order and extent -- every item needs to be there in the right place -- but whether every item is fully described or whether it's just a URI (plus type, plus label) makes no difference.  That level is framing, rather than equivalence.

**Comment by azaroth42** [comment]
Confirm in Toronto.

**Comment by azaroth42** [comment]
Discussion: The only time this becomes a problem is if there was an RDF based client that merges data across documents.

Proposal: It is legal in IIIF to include only part of any resource's set of properties or members of a list. It is acknowledged that this data may not be round-trippable through a triplestore when there are multiple documents involved (see #1267). The authoritative form is always the referenced document (e.g. a Collection that has an out of date set of labels for a Manifest would have its labels replaced by the Manifest's labels when the Manifest is loaded.)

If accepted, then this issue can be closed and #1267 covers updating the principle.

**Comment by azaroth42** [comment]
Upon further reflection of other issues, if it is legal to include part of `items`, how would any client know that there are more entries to be found by dereferencing the URI?

**Comment by tomcrane** [comment]
As it is impossible to guarantee or enforce that a resource included in another resource is identical to the resource with the same @id when dereferenced (web caches, mistakes, dynamic resources, whatever), client software has to be built on the assumption that they might not be the same, so whether we perceive this as utility or problem is up to us. 

Clients should do the sensible thing and lead the user to what is likely to be the most authoritative / complete form, through navigation user experiences, and take advantage of the ability to show what they can along the way.

Having a strong opinion on round tripping applying to a single document only (#1311) gives us the utility.

(So :+1:)

**Comment by workergnome** [comment]
Agreed.  From an API perspective, it's common to have entities at various levels of completeness, but with the same ID.  From an RDF perspective, open-world says that no entity should be seen as complete.

 Also :+1: from me.
