### ISSUE TITLE
Clarify if @type is required for thumbnails.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/api#1147]
We're trying to tie up some loose ends on detail image and choice in Mirador and noticing that a number of our demo objects are failing validation. We've been able to track down the issue with most of them, and usually the problem is something with the manifest itself, or with iiif-evented-canvas, but some we're not sure about.

http://gallica.bnf.fr/iiif/ark:/12148/btv1b84539771/manifest.json (and some other BNF manifests in the Mirador demo) doesn't validate, erroring that "Every resource must have @type". However, all resources seem to have a type. More details given in the below issue:

https://github.com/sul-dlss/iiif-evented-canvas/issues/2

**Comment by tomcrane** [comment]
In http://gallica.bnf.fr/iiif/ark:/12148/btv1b84539771/manifest.json, thumbnails are:

```
"thumbnail" : {
        "@id" : "http://gallica.bnf.fr/ark:/12148/btv1b84539771/f1.thumbnail"
}
```

I think they should be either:
```
"thumbnail" : "http://gallica.bnf.fr/ark:/12148/btv1b84539771/f1.thumbnail"
```
or 
```
"thumbnail" : {
        "@id" : "http://gallica.bnf.fr/ark:/12148/btv1b84539771/f1.thumbnail",
        "@type": "dctypes:Image"
}
```

Even better (not _directly_ pertinent, just a plea):
```
"thumbnail" : {
        "@id" : "http://gallica.bnf.fr/ark:/12148/btv1b84539771/f1.thumbnail",
        "@type": "dctypes:Image",
        "width": 400,
        "height": 300
}
```
(please put the thumbnail dimensions in the manifest if you know them!)

**Comment by regisrob** [comment]
Thanks @tomcrane. One day Rob told me it shouldn't actually be necessary to have a type on thumbnail. I thought this has been fixed ever since in the validator (accoding to this ticket: https://github.com/IIIF/presentation-validator/issues/16). So what I understand out of this is that as soon as the thumbnail's value is structured as an object with an @id, it MUST also have a @type (as in your example), which would not be required if the thumbnail is only a string.

So I guess I should kill two birds with one stone by requesting the IT people at the BnF both to fix the "thumbnail" in their manifests (if possible including the width/height of the thumbnail image) AND switch to HTTPS :)

**Comment by aeschylus** [comment]
Thanks for the follow-up on this all. Reflecting on the call this Wednesday, and going over the notes, I don't know where we came down on this. The notes and the discussion I remember seem to contradict the spec by implying type wasn't important on thumbnail object bodies. The spec says in the table of technical properties under http://iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements that `@type` is required for any and everything.

If it is, then I'll continue to require type in the evented-canvas library for producing thumbnails, and remove the BNF objects from the mirador demo temporarily.

**Comment by regisrob** [comment]
@aeschylus This should be fixed in the BnF manifests quite soon (but I do not know exactly when...)

**Comment by workergnome** [comment]
And `duration`?

**Comment by azaroth42** [comment]
Ahh, yes, and duration for audio/video resources, good call.

**Comment by azaroth42** [comment]
If we accept #1185, this also becomes moot -- all resources would require a `type`, including thumbnails.

**Comment by azaroth42** [comment]
#1185 is a tighter definition. Closing in favor of that issue.
