### ISSUE TITLE
Clarify release process for patch level updates

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1154]
... that a community call is sufficient review for the "open meeting" requirement.

**Comment by jpstroop** [comment]
From Community/Tech call on 10 May 2017: Probably OK to relax the process, but an issue review (on a call) and freeze period probably.

**Comment by srabun** [comment]
Agreed and confirmed on May 24 community call that face-to-face meetings are not necessary for patch updates, we can send an email announcement, allow time for comment, and discuss via regularly scheduled community/tech calls. See notes from May 24 call: https://docs.google.com/document/d/1PcDA8ntnwW20BvQGQFg-W5J0z1pbtANVY_fTNOpQdVM/edit
