### ISSUE TITLE
Clarify "server" and "identifier" for auth redirects

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1162]
http://iiif.io/api/auth/1.0/#tiered-access currently says:

> If a server supports multiple tiers of access, then it MUST use a different identifier for each Description Resource and its corresponding Content Resource(s).

Which isn't really the requirement.  There could be two servers, one of which has the protected full assets and a second server at a different domain with the public degraded versions. Then the "identifier" parameter doesn't necessarily change at all.  Or different prefixes.  The requirement is that the URI up to and including the identifier must be different.

**Comment by tomcrane** [comment]
Address in 2.0

**Comment by tomcrane** [comment]
Addressed in https://github.com/IIIF/api/pull/2115

https://github.com/IIIF/api/pull/2115/commits/f911383dfc241283b9997600fd876361959ee052)

**Comment by zimeon** [comment]
Resolved with publication of Auth 2.0 https://iiif.io/api/auth/2.0/. The approach is now resource (URI) centric and there is more uniform description of different access controlled resources, without any mention of the `identifier` component of Image API services
