### ISSUE TITLE
For issues discussed/derived from slack, add a pointer to archive

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1163]
To improve transparency of the process, any issues discussed in slack or created due to a discussion in slack, should have a pointer added to the issue (either in a comment or the main description) referencing the beginning of the discussion in iiif.slackarchive.io.

Discussions should thus take place on open, archived channels, especially #general and #technical.

If accepted, this should be added to the process document.

**Comment by zimeon** [comment]
Should this be copy-paste into issue _and_ add pointer to source in the archive?

**Comment by azaroth42** [comment]
See: https://github.com/linked-art/linked.art/issues/52 for a possible solution

**Comment by azaroth42** [comment]
slackarchive.io is defunct :(   Prerequisite would be to get a new archive!

**Comment by azaroth42** [comment]
slackarchive officially dead.  Open source / abandonware:  https://github.com/dutchcoders/slackarchive

**Comment by azaroth42** [comment]
Editors agree close - if there's interest in a slack archive in the future, then this could be reopened.
