### ISSUE TITLE
Typo in Auth 3.2: "appropriated"

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1165]
> "an appropriated authorized"

should be "an appropriately authorized"

(Auth 1.0.1?)

**Comment by zimeon** [comment]
Agree should be fixed but perhaps best to wait and roll up with other changes?

**Comment by azaroth42** [comment]
Agreed, though see #1166 for another 1.0.1 potential issue

**Comment by tomcrane** [comment]
Fixed in https://github.com/IIIF/api/pull/2115

Commit: https://github.com/IIIF/api/pull/2115/commits/4125a366b02cb5fd3067b3b4520eee32034403a0
