### ISSUE TITLE
202 response for info.json?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1168]
Could it be legal to respond to the info.json with a 202 Accepted, in the case where there will be a not insignificant delay in generating the info.json and/or the image content?  For example, if the backing store for the image is perhaps a tape drive or the system requires a JP2 to be generated on demand from a high resolution master file, then how can a system signal to the client that the request is understood but not yet able to be served, so please continue to another image and come back for this one?

[From discussion with potential vendor]

**Comment by workergnome** [comment]
I wouldn't be opposed to this in principle, but it's a pretty big breaking change from the existing spec.  At this point, we assume that when you dereference a URL, you get the content or an error, and so every implementation would have to handle both paths, and that seems like it might be a burden on the client implementations.

**Comment by robcast** [comment]
Would a 503 with Retry-After be too brutal?  It would also require separate handling in the client. Our server sends 503 to image requests when it's overloaded so that could be a similar situation on the one hand but to my knowledge it's still not possible to get the HTTP status code from an image request so maybe it's not so similar after all.

**Comment by zimeon** [comment]
I don't think [202 Accepted](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) makes much sense for a GET or HEAD request, I agree with @robcast that 503 with a helpful time indication would be better.

However, not clear whether this needs to be in the spec. Perhaps we need indication of compelling use cases and and understanding of how Javascript would handle this in image requests.

**Comment by azaroth42** [comment]
Close wontfix. If someone actually needs this, with an implementation, they can reopen.
