### ISSUE TITLE
How do we close stories issues?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1169]
Related to #843, not only how do we track stories movement into specs ... but also how we decide that a story is not in scope, or otherwise not going to be solved, or when it is solved, who can/should close the story issue?

We have people not understanding the relationship and commenting on stories that have been already long since solved: https://github.com/IIIF/iiif-stories/issues/9#issuecomment-305011591 
This is a disservice to both our community and to ourselves.

**Comment by azaroth42** [comment]
My proposal is that Editors will close core spec story issues, and WG chairs can close WG specific stories, when those stories have been resolved one way or the other.

**Comment by zimeon** [comment]
Sounds good to me @azaroth42. I think we need to ensure that on closing there is a clear statement about how it was solved or why ruled out-of-scope. Do we need to lock closed stories too? Doing so would mean that commenting on a closed issue would then require a new issue referencing it, but it would keep the old issue clean.

**Comment by jpstroop** [comment]
I think that as long as we close the issue with a response (how this is solved, why it's out of scope, links to relevant parts of specs, other working docs, etc.) I'm 👍  to eds closing. Like the idea of locking as well.

**Comment by tomcrane** [comment]
Maybe a standard template/checklist for story issue resolution, as per @jpstroop's list. And lock the story to require a new issue.

**Comment by azaroth42** [comment]
Discussion from Discovery group break (Rob S, Dave B, Jason R, Antoine I, Matt M)

Unanimous decision from chairs of a group for stories that are in their TSG scope can close. 4/5 Editors can close for stories that are not in any TSG scope. If something is in scope but difficult, then it can be tagged as `defer` to help with sorting/filtering.

Can close when the story is:
  * decided to be out of scope
  * decided to already be solved
  * decided that it isn't solved, but issue is raised on the iiif.io issue list, preferably with a proposal for a solution

**Comment by azaroth42** [comment]
This is documented in the README for the stories repo.  Closing.
