### ISSUE TITLE
Update readme to define contribution requirements

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1172]
A project I'm associated with via the Getty has started using CLAs, with a nice little integration:
    https://cla-assistant.io/

I forget if we've discussed CLAs, but (a) should we require them? and (b) should we use the integration?

**Comment by azaroth42** [comment]
Close no-one-cares?

**Comment by workergnome** [comment]
Given the lack of actual (reusable, licensed) code on the site, I don't think it matters?

**Comment by azaroth42** [comment]
Additions to the text are still potentially copyright to the organization that employs the contributor or the contributor themselves, and thus potentially problematic to back-out should there be complaints down the line. Contributions are contributions, natural language or programming language, IMO.

Proposal:  Update README.md to state that contributions are welcome, and the contributor asserts that they have the right to license the contribution (of whatever form) such that content may be published as CC-BY by the IIIF Consortium (per our license statement on all specifications).
