### ISSUE TITLE
Reconsider lowercase class names in Presentation API text

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1173]
When we move to the Web Annotation model, we inherit several class names with CamelCase that would be confusing if lower cased as we currently do. For example "annotation collection" could be confused with a Collection from IIIF, and "specific resource" (rather than oa:SpecificResource) is very confusing.  Notably SpecificResource is one of the classes that `timeMode` can be applied to.

Proposal: Use AnnotationCollection instead of annotation collection. No backticks.

**Comment by azaroth42** [comment]
No one cares? Hopefully thus okay that I've done this in 3.0.

**Comment by workergnome** [comment]
:shrug:

**Comment by azaroth42** [comment]
Done. Closing :)
