### ISSUE TITLE
Rename contentLayer to ... something else?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1174]
In 3.0 when we move to the Web Annotation Data Model, IIIF Layers go away in favor of AnnotationCollections.  Meaning that the `contentLayer` relationship becomes very oddly named, and should be in sync with the new naming somehow.

Some options:

  * `content` as per new Canvases property, and have it reference a List of AnnotationPages ? Changes the model, without real reason.
  * `contentAnnotationCollection` is a bit of a mouthful.
  * `contentCollection` could be confused with Collections?
  * `contentAnnotations` could be confused for an AnnotationPage as range?
  * Leave it the same, despite "Layer" not being a class any more

Other options?

**Comment by azaroth42** [comment]
Why is it to a Layer rather than a list of AnnotationLists?  If it were the latter, it could be the same relationship as from Canvas to list of AnnotationLists... which would be `content` in 3.0, simplifying the model.

**Comment by azaroth42** [comment]
Proposal:  `includes`

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting that we will go with `includes`

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#includes

**Comment by zimeon** [comment]
:+1: agree done
