### ISSUE TITLE
Non Image thumbnails

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1176]
For audio only canvases, the only "thumbnail" available might be a short audio clip rather than an image.  Similarly for video, the thumbnail might be a video.

I propose to allow these as thumbnails, and thus require both id and type on a thumbnail resource.

**Comment by azaroth42** [comment]
AV call 08/22: As points to a specific format, it would point to a particular encoding of a video rather than the multi-format choice or canvas.  

Challenge then is what to do for clients that only support one of the encodings, and how to describe the resource in sufficient detail that the client can determine which to use.  Currently no documentation about the implication of more than one thumbnail. No service available for AV, compared to Images.

**Comment by azaroth42** [comment]
Getty AV discussion: All of the thumbnails should be equally useful, such that if you pick any one of them depending on the current client environment, it should be sufficient.  Otherwise :+1:

**Comment by jronallo** [comment]
May help to see some examples of what this would look like with different and multiple formats to have something more to comment on.

**Comment by brion** [comment]
Possible examples:
* duration canvas with one MP3, one WAV, and one Ogg. All three should be considered equivalent and whichever one is best fit for playback capability is used?
* duration canvas with one JPEG and one MP3. JPEG should be used in visual contexts, MP3 should be used in audio contexts?
    * accessibility scenarios may encourage use of audio, for instance, or it may be selected explicitly
* spatial+duration canvas with one JPEG, one MP4, and one WebM. JPEG should be used if video playback unsuitable, or whichever of MP4 or WebM is preferred by the browser should be played if able to play it?

**Comment by julsraemy** [comment]
Also, an audio thumbnail for a manuscript is good for accessibility purposes.

**Comment by jpstroop** [comment]
Toronto WG Plenary: 👍, modulo a question about using `label` or another method for alt text (wrt accessibility). See #1288.

Also, needed to clarify via disucssion that:
 * `thumbnail` is always a list
 * Multiple Types are allowed,
 * More than one of the same type is allowed
