### ISSUE TITLE
startCanvas, contentLayer to use {id:...} form

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1177]
For consistency (see #1131) with other references to resources, should `startCanvas` and `contentLayer` also always use the object format, rather than a URI reference, even though the type of the resource is able to be determined from the property (canvas and layer/annotationCollection respectively)?

e.g. 3.0 would deprecate `"startCanvas": "canvas-uri"` and instead require `"startCanvas": {"id": "canvas-uri", "type": "Canvas"}`

**Comment by workergnome** [comment]
+1 for explicitness, at least in my opinion.

**Comment by mikeapp** [comment]
👍

**Comment by azaroth42** [comment]
Discussion at AV Getty meeting: :+1:

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#startcanvas
