### ISSUE TITLE
@context ends with WebAnnos, then IIIF

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1186]
`@context` can be a list, and in 3.0 will always be a list of at least two (IIIF and Web Annotation contexts). It may be longer than two if there are extensions in use.

The order of the items in the list matters for two reasons:
1.  The priority is from the end backwards. e.g. later definitions will overwrite earlier ones.  
2.  Clients use the presence of the iiif context to determine that it's a Presentation API response. If the location is fixed, the test is easier. This is much less important than the previous :)

I think the IIIF context should be the last, ensuring that we always override any other definitions for the same keys.

**Comment by tomcrane** [comment]
👍 
This approach prevents you overriding IIIF terms with your own added contexts, which we want for interop.

**Comment by azaroth42** [comment]
As an alternative, that would also make #1195 easier, we could use scoped contexts to ensure that the Annotation context only applies in the slots where annotations, annotation pages and annotation collections can actually appear.  Then we don't trash the WA context for label by redefining it to be a language map.

It would mean that only the IIIF context would appear in the documents, as that context would import the Annotation context at the right scope.  This exacerbates the existing issue that @context is not always the same datatype (normally just a string, but an array if more than one context doc) but makes things easier overall, I believe.

**Comment by workergnome** [comment]
As a minor preference, I'd prefer to see all the contexts applied up at the top, in the context block.  I think additionally overriding IIIF with, say, WA, in places would be useful, but it would be explicit in that case why and what that's doing.

No strong feelings, though.

**Comment by azaroth42** [comment]
Proposal: 
> The value of the @context property must be a list, and the last two values must be the Web Annotation context and the Presentation API context, in that order. And further contexts must be added at the beginning of the list.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#linked-data-context-and-extensions

**Comment by zimeon** [comment]
:+1: agree done

**Comment by mikeapp** [comment]
👍 closing
