### ISSUE TITLE
Allow Canvases to be annotated to Canvases

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1191]
As a more robust solution for #42.
(see also #1190)

Questions as to where sub-canvases live in the representation.

**Comment by azaroth42** [comment]
AV call 8/8/17: @azaroth42 to come up with some mocks to help discussion.

**Comment by azaroth42** [comment]
Example from Avalon: https://mallorn.dlib.indiana.edu/playlists/739/manifest

Questions:  
  * What about fragments of canvases? 
  * What about auto-advance?
  * What about a time+space clip, that doesn't include any of the video painted area ... does the audio still play?
  * Is this just toooo damn hard!?

**Comment by azaroth42** [comment]
Proposal:
> Canvases should be able to be treated as content resources for the purposes of annotating them on to other Canvases. 

This issue is only about the broadest level of the above, not about the processing issues of the myriad possibilities and pitfalls it might introduce.  A processing algorithm (# xxx) would be important for making this implementable.

**Comment by azaroth42** [comment]
Questions are reducable to: 
* Is there a single temporal dimension for the entire canvas, or do spatial regions of the canvas have their own temporal dimension?
* Can you select a reduced set of dimensions from the sub-canvas for association with the master canvas?

**Comment by jpstroop** [comment]
Toronto WG Plenary: 👍

**Comment by azaroth42** [comment]
Editorial question of where this lives, given no "advanced association" section. It seems more than a cookbook entry.

**Comment by stephenwf** [comment]
I have a few questions:
* Can I embed the same canvas in 2 canvases in the same manifest?
* Can/How would you target a canvas inside of a canvas using a range?
* If an annotation list is attached targeting canvases that in other canvases should they be painted? Are there times where you would not want that behaviour?
* Can embedded canvases be references to other canvases inside the current manifest, instead of the full JSON for the canvas?

**Comment by azaroth42** [comment]
In order, from my perspective:

* Yes, though we don't know of any realistic use cases when you would actually want to do this.
* The same way as ever, by reference to the embedded canvas's URI. The navigation UX would be weird, on the other hand, especially if it appeared in more than one parent canvas.  We might want to disallow this.
* The annotations should be associated with the canvas that they paint.  That said, if the client encounters one and can paint it, it probably should.
* Do you mean "Can the child canvas be in the Sequence, rather than tied to the parent canvas"?  And yes, you can. Is it a recursiveness issue where Canvas A embeds Canvas B embeds Canvas A?  Also yes, but don't do that that unless you want to implement a mandelbrot viewer in IIIF :D

**Comment by azaroth42** [comment]
Closed #1414
