### ISSUE TITLE
Use of JSON-LD 1.1 features is okay before standardization

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1192]
A prerequisite issue for much of Prezi3 is the decision about whether we should use not-yet-standardized functionality projected for JSON-LD 1.1, including `@none` in language maps, type/predicate specific `@context` definitions, and `@set` requirement for language map values.

Tagging as `principles` as it's a core design pattern question.

**Comment by zimeon** [comment]
We have no formal requirement to use fully baked standards, we explicitly hedge in the [design patterns](http://iiif.io/api/annex/notes/design_patterns/#use-existing-standards-where-possible).

So then it is a question of tactics. It would be really bad to base 3.0 on something that fails to become a standard and get adoption (e.g. we use 1.1 features that the community rejects in favor of 1.0). How/when can we be reasonably sure that 1.1 will make it, and on what timescale? I didn't find much hint poking about (can see [issues in the JSON-LD 1.1 milestone](https://github.com/json-ld/json-ld.org/milestone/3) but that doesn't give much of a hint about convergence, let alone standardization).

**Comment by azaroth42** [comment]
I don't believe that there's a timeline for an official new TR for JSON-LD 1.1, it would require the W3C to create a WG chartered to do it.  I think that @gkellogg would like to have the Community Group version ready to go by the end of the year.  I would be surprised if 1.1 was a full spec before the beginning of 2020.

It would be very painful to have to, for example, go from `@none` to `@null` making a new version of IIIF for the sake of three characters. 

We don't need to make the decision until we pull the trigger on Prezi 3, but we (community) should be considering the ramifications of it.

**Comment by gkellogg** [comment]
Indeed, end of the year is reasonable for a complete CG spec. As for a new TR, I have heard rumblings about a mechanism to advance a CG spec to TR without needing a WG, presuming that the process used is appropriate, but nothing else.

This is a topic to bring up in a Wednesday session at  TPAC, for sure.

As for the degree of community by in with the 1.1 work: each change has going through a review period, and some have had lively comments. But, I don't think that the absence of negative feedback can be necessarily taken as acceptance either. I think we'll need to wait for work to complete and to put out the equivalent of a Proposed Recommendation to get broader feedback. We'll also need to put out a specific request for implementations to get more implementation feedback. Developers are (somewhat reasonably) not likely to spend time implementing to a moving target (myself excluded, of course).

**Comment by azaroth42** [comment]
Thanks @gkellogg! @sandhawke proposed a process change here:  https://github.com/w3c/w3process/issues/41 but it doesn't seem to have much buy in yet from other W3Cers.

**Comment by azaroth42** [comment]
(affects #755)

**Comment by azaroth42** [comment]
Discussion at Getty AV Meeting:
* Have used CG spec in the past (Open Annotation, rather than wait for Web Annotation)
* Can provide implementations towards JSON-LD 1.1 which will be appreciated
* General developer happiness
* The way to not end up at 4.0 in 2 to 3 years is to adopt 1.1, as otherwise we continue to use 1.0 and then have to go to 1.1 anyway to get the benefit of the additional features.
* Rolling the dice on the TR spec, but not the CG spec.

:+1: from the group.

**Comment by gkellogg** [comment]
@azaroth42 your thoughts on how to push for a JSON-LD WG towards a TR at TPAC appriciated.

**Comment by zimeon** [comment]
:+1: agreed to move ahead with JSON1.1 for Presentation/Image 3.0 at Toronto WG meeting

**Comment by azaroth42** [comment]
Does this need to be documented somewhere? And if so, where?

**Comment by azaroth42** [comment]
Ping on where to document? I think this is sufficient, and we can close?

**Comment by tomcrane** [comment]
An introductory note about foundational specifications would be very valuable for newcomers to the spec. Does it belong **in** the spec, as a preamble? But that isn't the exact question; community has agreed that we're good with JSON-LD 1.1, it's documented here, closing OK.

**Comment by zimeon** [comment]
I think the discussion and decision is documented here. 

I'm fine with a spec pre-amble note about foundational specs, but that would not mention their status because doing so would look silly a couple of years later when that status changed.

**Comment by azaroth42** [comment]
Closing. The update to the principles, plus this issue, covers the bases.

**Comment by azaroth42** [comment]
(Noting that a JSON-LD Working Group is being chartered, so far bearing out our strategy)
