### ISSUE TITLE
Allow choiceHint

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1194]
From the AV work, we know that we need to hint to the client whether it (the software) should make the choice or whether the user should make the choice.  Something like the description below.

The question is whether the list of values is closed or whether there can be any URI as per `viewingHint`?  My preference would be to allow additional hints via full URIs to enable experimentation without getting in the way of validation.

---

A hint associated with a Choice resource that a client can use to determine the publisher's intent as to which agent _SHOULD_ make the choice between the different options.  In the absence of any `choiceHint` value, the rendering application can use any algorithm or process to make the determination.

* A Choice _MAY_ have exactly one `choiceHint`, and the value _MUST_ be one of the options described below.

| Value | Description |
| ----- | ----------- |
| `client` | The client software is expected to select an appropriate option without user interaction. |
| `user` | The client software is expected to present an interface to allow the user to explicitly select an option. |

``` json-doc
{"choiceHint": "client"}
```

**Comment by zimeon** [comment]
I like the general pattern of allowing URIs for extension (per https://github.com/IIIF/iiif.io/issues/1075#issuecomment-314759879), but to have extension with fallback  for interoperability one would want to be able to specify a defined value _and_ a custom URI. But then if multiple values were allowed we'd need extra rules saying how to resolve/decide which to follow. Without multiple values you are stuck with the default behavior if an extension URI is used but the client doesn't understand it. Not sure what best trade-off is here.

**Comment by azaroth42** [comment]
Discussion on 8/2/17 call:  Different bitrate of videos (or different sizes, qualities for the same image at different endpoints) -- user might choose to degrade their quality.   Concerns as to whether this is broadly applicable to other formats/media.

Discuss in Toronto in AV session?

**Comment by azaroth42** [comment]
Getty discussion:  `choiceHint` defines a feature of an `oa:Choice` ... which isn't defined or even mentioned in the specification, as it's part of the Web Annotation that is now in a pattern document (previously section 6).

Question as to whether there is ever sufficient information for a client to make an informed choice on behalf of the user -- can make a choice of format.   No consensus as to whether it's needed or not.

**Comment by azaroth42** [comment]
Propose to remove it from the spec. We can re-add it later if there's consensus that it's needed.

**Comment by zimeon** [comment]
Agree remove for now and close out this issue. We've aired this a few time and no compelling cases where the client can make a good choice have come up.

**Comment by azaroth42** [comment]
Closed by #1298.
