### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by srabun** [IIIF/api#1196]
From Cuba: https://drive.google.com/file/d/0B7dsMrW9Kus_OFpyNHpFWVo1TFk/view

**Comment by azaroth42** [comment]
Reassigning from Sheila to @glenrobson (until we have a new Community Coordinator)

**Comment by glenrobson** [comment]
Whats the procedure for these? I thought we were generally OK with pointing to external translations but how do we feel about hosting translations (of the spec)?

**Comment by zimeon** [comment]
I am against hosting, dubious even for linking based on OAI-PMH experience

**Comment by azaroth42** [comment]
Agree with Simeon. Close wontfix? Or someone willing to get in touch and ask them to put the pages online?

**Comment by azaroth42** [comment]
Propose close wont fix.  Silence for 21 days considered assent.

**Comment by azaroth42** [comment]
21 days are up. Closing.
