### ISSUE TITLE
Clients SHOULD process inline annotationPages first

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1201]
In discussion of #1068, we have agreed to combine presentation 2.0 `images` and `otherContent` into a single `content` in presentation 3.0 which includes inline and referenced `AnnotationPage` entries. In 2.0, the distinction served to indicate what should be painted immediately (`images`) or loaded later (`otherContent`). What are the rules with `content` (inline vs referenced?) and are any explicit hints necessary?

**Comment by tomcrane** [comment]
@workergnome's concern was that there's no longer any semantic distinction between content to be loaded now and content to be loaded later, only its location in the serialisation (inline in the manifest or in another resource).

**Comment by azaroth42** [comment]
I agree that there isn't a semantic distinction, just a serialization one. However it's a serialization/API concern, not a modeling one (IMO).  In the absence of network latency of transferring serializations (of the JSON-LD, and the content resources) between server and client, there would be no need for the distinction. 

I think that the action is to call out the difference between embedded AnnotationPages and referenced AnnotationPages, in the same sort of way we do now for AnnotationList.  The change is to make this more consistent, rather than splitting up into images as an array/rdf:List and other stuff as an identified AnnotationList.

**Comment by azaroth42** [comment]
Is there a normative requirement about content loading, or is it an implementation or design note?

**Comment by workergnome** [comment]
I think the spec should consider inline and referenced works as equivalent.  We already have mechanisms to point to related, but not-loaded content (see also, referenced), and unless we're going to semantically distinguish between immediate-need and deferred-load content, I don't think there's a reason to add a note.

Do we intend clients to process them differently?

**Comment by tomcrane** [comment]
Clients do process them differently because typically (at the moment) the inline `images` are a small amount of data but linked annotations - transcriptions, say - could be a large set of data and might have a negative effect on user experience if immediately painted. 

```
"content": [
   { 
        // inline stuff... 
   },
   {
        "id": "https://example.org/letter-by-letter-transcription/page1.json",
        "type": "AnnotationPage",
        "label": "Load me if you dare"       
    }
]
```
> Is there a normative requirement about content loading, or is it an implementation or design note?

Not sure...

**Comment by azaroth42** [comment]
I think from a *cough* semantic point of view, inline and referenced resources are equivalent. The question is at the data-as-API level. I think we do intend clients to process them differently -- load the resources that are inline in the manifest first, and then process the externally referenced ones.  In 2.x this amounted to process the images, then the rest ... but that distinction no longer holds once we add time based media and collapse everything down to `content[s]`

On further reflection (and work on #1243), I think we should have a normative SHOULD on clients to process inline resources before referenced.

**Comment by azaroth42** [comment]
Discussion on AV call:

Noting that temporal canvases will need to load content resources in the order of their appearance according to the canvas clock.
Gives a pressure release valve for having very very large manifests, which is the first and required resource to load. 

Proposal from AV:  SHOULD in the spec for client implementation, as it sends a clear reason to developers as to why they should be doing this.

**Comment by zimeon** [comment]
:+1: agreed in Toronto that inline annotationPages SHOULD be processed in the order in which they appear in the Canvas
