### ISSUE TITLE
Require `type` for ALL resources

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1203]
There is some confusion in 2.x as to which resources require a `type` (or `@type`) and which ones do not. In 3.x we could require _all_ resources to have a type, following the specification's classes plus the list identified in the Annotation work:
  https://www.w3.org/TR/annotation-model/#classes

**Comment by jpstroop** [comment]
I can't think of a reason why not.

**Comment by zimeon** [comment]
If the goal is to avoid confusion, then _"all resources SHOULD have a `type`"_ would probably be sufficient. It seems a bit of a stretch to justify _MUST_ on a clarity argument, is there a more compelling reason?

Also, for extensibility it would presumably be best to use _SHOULD_ for the set of classes: _"all resources SHOULD/MUST have a `type`, that SHOULD be from \[the specification's classes plus the list identified in the Annotation work]"_

**Comment by workergnome** [comment]
Just to clarify, this would include resources that are only included via URI:

```
"thumbnail": {
   "@id": "http://www.example.com/image.jpg",
   "@type": "dctypes:Image"
}

```

and would no longer allow

```
"thumbnail":  "http://www.example.com/image.jpg"
```

This would also effect https://github.com/IIIF/iiif.io/issues/1201, because now "inline" would mean "inline as a sparse object with only a type and id", not `string` vs `object`.

**Comment by azaroth42** [comment]
Related to #1185.

For consistency of the value of Thumbnail, Logo, License, etc, if there can ever be an object there should always be an object. The easiest way to ensure this is to have mandatory property, of which `type` seems the most useful and understandable.  Otherwise if there's just the URI, the compaction will prefer the most compact form of just the string.  

References would indeed be always sparse objects, rather than strings ... making it easier to handle when there is a fully embedded resource.

**Comment by workergnome** [comment]
So, everything MUST have a type, and thus must be an object, both of which I think are improvements over the current spec in terms of implementation (at a slight cost to compactness).

Which leaves @zimeon's question, about what they types can or should be.  Definitely in favor of an open-ended implementation here, for future-proofing.

**Comment by azaroth42** [comment]
To @zimeon's point about SHOULD vs MUST, we already require type on pretty much everything ... just not content resources or services. All of the core IIIF types (Collection, Manifest, Sequence, etc etc) are MUST.  So to me this is a consistency argument (and an ease of processing one, as using heuristics to guess the type is painful) rather than a comprehension one.

**Comment by azaroth42** [comment]
#1185 is tighter definition. Closing in favor of it.
