### ISSUE TITLE
Consider reifying all language literals

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1213]
One of the issues with the approach in 2.x for multi-lingual values is that not every value will be translated into every language.  Thus if there are 10 values in English, and only 5 in French, it is impossible to tell which of the English values should be displayed to someone with a French locale.

A possible solution is to reify the literals into resources.  Thus instead of:

```
{"description": {
    "en": ["Here is the description of the object in English", 
           "And a second description"],
    "fr": ["Voici la description de l'objet en français"],
    "@none": ["A description in an unknown language"]
}
```

Where the second description is not displayed to the French-speaking user, instead the more verbose solution:

```
{"description": [
  {"value": { "en": "Here is the description of the object in English",
             "fr": "Voice la description de l'objet en francais"}},
  {"value": {"en": "And a second description, only in English"}}
  ]
}
```

There's no need for the array wrappers for the languages, as there would only ever be one value per language.  It would mean moving away from the common Dublin Core predicates, and `label` would be quite painful... but I think it's worth a discussion.

**Comment by azaroth42** [comment]
FWIW, the only actual language-based fields are:  `label`, `description`, `attribution` and the `label` and `value` pairs in `metadata. So the number of affected properties is low, even if they're very very commonly used.

**Comment by workergnome** [comment]
I get the problem, but I'm curious what that would resolve to in RDF.  My naive assumption is it would be:

```turtle
<entity> dc:description _:b1, _:b2.

_:b1 rdf:value "Here is the description of the object in English"@en;
    rdf:value "Voice la description de l'objet en francais"@fr.

_:b2 rdf:value "And a second description, only in English"@en.
```

Which seems horribly ugly.  But without there being an entity to associate multiple descriptions to, I don't know what else you can do.  It doesn't seem that entities within language maps are associated with each other in any way—they're just tagged, unordered options.

**Comment by irv** [comment]
Dumb question: would that mean I can do the following?

```
{"description": [
  {"value": { "en": "Here is the description of the object in English",
             "fr": "Voice la description de l'objet en francais"}},
  {"value": {"en": "And a second description, only in English"},
  {"label": {"en": "Description is now characterisation"}}
  ]
}
```

**Comment by azaroth42** [comment]
@workergnome Yes, it's ugly in RDF due to the class-less blank nodes, but it's valid.  We could require a `type` on the reified object which seems annoying but possible, however requiring a URI seems really overkill. 

@irv It wouldn't allow setting a UI label for description, if that's what you were intending with your last line? I wonder if description should just go into `metadata`...

**Comment by irv** [comment]
Bummer. Reason I ask is that `attribution` has a very specific legal meaning, which we change in our UV instance but that's no good if someone loads our manifests in their viewer. benefit of keeping the content in `attribution` as opposed to an entry in `metadata` being that the client has to display `attribution`...

**Comment by azaroth42** [comment]
Discussion:  Solves a very small problem by making everyone's lives harder. Close wontfix.

**Comment by zimeon** [comment]
Close wontfix validated at Toronto WG meeting
