### ISSUE TITLE
Clarify token expiration is invalidCredentials error state

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1215]
Assuming my reading is correct, when a token expires the most appropriate error state is `invalidCredentials` -- invalid because they have expired, not because the user is not authorized.
This should prompt a refresh of the token, not necessarily a re-login.

Did we discuss `expiredCredentials` as a separate error state, given that we define the `expiresIn` key for the token?  Either way, the spec should be clearer about which error state to use for expired tokens.

**Comment by tomcrane** [comment]
Addressed in https://github.com/IIIF/api/pull/2115

Commit: https://github.com/IIIF/api/pull/2115/commits/fc9da657eef34ad06ce33875a8f7e591ac7e55f4

**Comment by zimeon** [comment]
Resolved in Auth 2.0, see `expiredAspect` in https://iiif.io/api/auth/2.0/#access-token-error-format
