### ISSUE TITLE
Ranges should be reference-able like external Sequences

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1218]
Currently, the second and subsequent Sequence resources can be reference to external documents that are retrieved and processed.  This seems inconsistent with Ranges, where multiple Range hierarchies must all be embedded.  I propose that ranges should be able to be external references with only `id`, `type` and `label`.

**Comment by zimeon** [comment]
... so a compliant client _MUST/SHOULD_ be prepared to retrieve (from anywhere) and process (an arbitrary number of) additional documents in order to present the contents of a manifest.

Not saying this is necessarily a reason to object, but just checking the implication.

**Comment by mikeapp** [comment]
@zimeon I think we're potentially heading down that road already in doing away with `images` via #1068 / #1201 

Sequences seem a bit more amenable to lazy loading.  With Ranges there are cases where the entire hierarchy may be needed:
* Clients that track the user's position in the table of contents as they page through the sequence
* Clients that require the Layer information from `contentLayer` when rendering annotations (probably not a real use case at the moment)

Also, current clients don't necessarily (ever?) inform the user of failures related to loading Image API resources.  We might consider an explicit requirement to notify the user when things go wrong.

That said, I think this would be helpful for the SCTA/e-codices use case and so am tentatively 👍

**Comment by jpstroop** [comment]
> tentatively 👍

Same here, for the first use case @mikeapp mentioned.

**Comment by zimeon** [comment]
I am a tentative :+1: too. I think this is clean and adds flexibility for implementation and re-use. I think we might want to include:

  * A warning about client overhead/responsiveness issues of wildly distributed Manifest content
  * A note that clients _SHOULD_ indicate to the user cases where included Ranges cannot or have not been loaded (e.g. by marking in table of contents navigation)

**Comment by benwbrum** [comment]
Another use case supporting this recommendation: a client requests a list of canvases that is dynamically generated in response to some query.  

- Find all articles that need OCR correction 
- Find all articles that have been corrected 
- Find all pages that need to be transcribed
- Find all pages that have been transcribed but need proofreading

Ideally, a manifest would list a way of acquiring this list (like a list of URIs to sequences), but the list would not be embedded within the manifest itself.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting that we will permit any Range beyond the first to be external

**Comment by tomcrane** [comment]
Clarification - the first range may be external too - if the only range is one of these: https://github.com/IIIF/api/issues/1259 (thumbnail every 10s) - then you would want it to be external. This is *different from* `sequence`, where there is nothing to be gained by having the first sequence external.

**Comment by azaroth42** [comment]
Is it that the entire hierarchy may be available in a single external representation (and hence only top level ranges can be external) or can _any_ range be external and the client needs to fetch them in as it constructs the hierarchy?

Proposal:  Only top level ranges can be external.

**Comment by tomcrane** [comment]
Discuss on AV call

**Comment by tomcrane** [comment]
Rob via Lyft - allow `behavior` on the reference as well as `id`, `type` and `label`

**Comment by tomcrane** [comment]
Restriction to top level makes client implementation easier

**Comment by tomcrane** [comment]
AV call - general agreement

**Comment by azaroth42** [comment]
This issue closed by #1325 ; and consistency for API level is called out in #1331
