### ISSUE TITLE
Search API: Annotation ID in 3.4.4. example is wrong

### ISSUE THREAD

**Issue by jbaiter** [IIIF/api#1219]
I think that the example given in [3.4.4. Multi-Annotation Hits](http://iiif.io/api/search/1.0/#multi-annotations-hits) is wrong, since the first identifier in `.hits.annotations` refers to `"http://example.org/identifier/annotation/anno-bush"`, which is not part of `.resources`. I believe the identifier should instead be `"http://example.org/identifier/annotation/anno-bird"`, which points to the first annotation in `.resources`.

**Comment by azaroth42** [comment]
Yes, good catch! :+1:

**Comment by digitaldogsbody** [comment]
wontfix for v1, willfix for v2

**Comment by digitaldogsbody** [comment]
Fixed by #2121
