### ISSUE TITLE
Search API: AnnotationList in 3.3.3. has wrong context.

### ISSUE THREAD

**Issue by jbaiter** [IIIF/api#1220]
Currently the example AnnotationList in [3.3.3. Target Resource Structure](http://iiif.io/api/search/1.0/#target-resource-structure) has the Search API context as its single context.

Since the AnnotationList does not have any Search API-specific fields, I believe that the context should instead be that of the Presentation API (as in all preceding examples in 3.3).

**Comment by azaroth42** [comment]
:+1: should indeed be Prezi context URI.

**Comment by digitaldogsbody** [comment]
wontfix for v1, fixed for v2
