### ISSUE TITLE
Clarify related vs rendering for "display to human" resources

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1224]
`related` says:
> A link to an external resource intended to be displayed directly to the user ...

`rendering` says:
> A link to an external resource intended for display [or download] by a human user

Per @benwbrum's survey, there is a lot of overlap between these in practice. 

I think the difference is that `related` is ABOUT the resource (it could link to a video of a curator talking about the painting, an academic paper is about or uses the archive, etc), whereas `rendering` is a representation OF the resource (a youtube video of the video manifest, a PDF of the book).

Proposal:

`related`:  A link to an external resource that refers to or is about the resource with the property, that is intended to be displayed to a human user.

`rendering` A link to an external resource that is an alternative, non-IIIF representation of the resource with the property, that is intended to be displayed to a human user.

**Comment by azaroth42** [comment]
I believe this is an editorial change, rather than normative, given the examples in the different sections... but it could be considered to be a normative change by the not insignificant number of adopters who have used the two interchangeably.  

Note that the two primary clients have __completely different__ implementations. Mirador does not handle `rendering` at all, whereas UV uses it to populate a drop down list of downloads (which is the use case we added it for). OTOH, UV does not handle `related` and Mirador puts it into the info slide out pane along with `seeAlso`. This has led to the current incompatibility of the manifests published.

**Comment by workergnome** [comment]
Is it about the resource, or is it about the entity depicted in the resource?

In my mind, `rendering` is a link to an alternative view of the resource itself (The manifest as a website, or the manifest as a PDF), whereas `related` is a link that is about the entity that the resource is about.

**Comment by azaroth42** [comment]
We don't really make a distinction in IIIF between manifest and the object or content that it models. So it's about whatever will make sense to the user when experiencing the content :)  And yes, that's the distinction I tried to capture in the issue.

**Comment by workergnome** [comment]
If it helps, here is a version that I wrote up for my personal use. I don't know if it's fully correct, but it might be a good straw man to start from?

Ofness

The manifest is the machine-readable content OF the manifest.
Dereferencable IDs within the manifest are external links to additional machine-readable content OF the manifest.
Annotations are the human-readable content OF the manifest.
rendering are external links to additional human-readable versions OF the manifest.
(Note that there is no place to put machine-readable or human-readable technical metadata about the manifest itself, as a document. For instance, when it was created, or when it was last updated, or who created it.)

Aboutness

metadata are embedded human-readable content ABOUT the item depicted in the manifest.
related are links to human-readable content ABOUT the the item depicted in the manifest.
A viewer is not intended to process these, but could provice access to them.
seeAlso are links to machine-readable content ABOUT the the item depicted in the manifest.
A viewer is not intended to process these, but could provide access to them.
(Note that there is no place to provide embedded machine-readable metadata about the item depicted in the manifest.)

Out of Scope Content

Comment Annotations are for structured content in a form defined outside of the IIIF spec intended to be directly readable by humans.
An interface COULD use these to augment the presentation of the manifest.
Services are for structured content in a form defined outside of the IIIF spec intended for processing by the interface to provide additional functionality to the presentation of the manifest.
An interface COULD use these to augment the presentation of the manifest.

**Comment by azaroth42** [comment]
Done, pending removal of related in #1286: http://prezi3.iiif.io/api/presentation/3.0/#related
