### ISSUE TITLE
Separate links to external resources from internal

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1225]
As noted by @jronallo, there are two distinct sets of linking properties that are currently bundled together.  There are links to external resources (`related`, `service`, `rendering`, and `seeAlso`), and links to internal resources (`within`, `startCanvas`, `contentLayer`).

It would be easier to understand if these were separated in the documentation by sub-headings.

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
:+1:  (as seen in [current draft](http://preview.iiif.io/api/prezi3/api/presentation/3.0/#linking-properties))

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#related

**Comment by zimeon** [comment]
:+1: done & closing because there was already editors' review based on the draft
