### ISSUE TITLE
Define requirements for the properties of external linked resources

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1226]
There is some confusion around the requirements for the properties of externally linked resources, as the current requirements are somewhat hidden in the definitions of the property semantics, rather than being called out more prominently. 

Proposal from @jronallo:  Reconsider the requirements for the different types of external resources, and add a table that summarizes them.

**Comment by workergnome** [comment]
If it helps, here is a version that I wrote up for my personal use.  I don't know if it's fully correct, but it might be a good straw man to start from?


## Ofness 
* **The manifest** is the machine-readable content OF the manifest.
* **Dereferencable IDs** within the manifest are external links to additional machine-readable content OF the manifest.
* **Annotations** are the human-readable content OF the manifest.
* `rendering` are external links to additional human-readable versions OF the manifest.

_(Note that there is no place to put machine-readable or human-readable technical metadata about the manifest itself, as a document.  For instance, when it was created, or when it was last updated, or who created it.)_

## Aboutness
* `metadata` are embedded human-readable content ABOUT the item depicted in the manifest.
* `related` are links to human-readable content ABOUT the  the item depicted in the manifest. 
     - A viewer is not intended to process these, but could provice access to them.
* `seeAlso` are links to machine-readable content ABOUT the  the item depicted in the manifest. 
     - A viewer is not intended to process these, but could provide access to them.

_(Note that there is no place to provide embedded machine-readable metadata about the item depicted in the manifest.)_

## Out of Scope Content
* **Comment Annotations** are for structured content in a form defined outside of the IIIF spec intended to be directly readable by humans.
     - An interface COULD use these to augment the presentation of the manifest.
* **Services**  are for structured content in a form defined outside of the IIIF spec intended for processing by the interface to provide additional functionality to the presentation of the manifest. 
     - An interface COULD use these to augment the presentation of the manifest.

**Comment by azaroth42** [comment]
I think that's more relevant to #1224 ?  This issue is the properties of the linked resources, rather than the semantics of the links.

**Comment by workergnome** [comment]
Ah.  I mis-interpreted the issue.  I'll move my comment over there.

**Comment by azaroth42** [comment]
Done:  http://prezi3.iiif.io/api/presentation/3.0/#external-links

**Comment by zimeon** [comment]
:+1: agree done with section on external links

**Comment by mikeapp** [comment]
👍 closing
