### ISSUE TITLE
Require format, strongly recommend profile, call out label as useful for seeAlso

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1227]
Following from discussion in the Discovery group, it would be good to reconsider the requirements around properties of external resources, and particularly for `seeAlso`.

The recommendation from Discovery is:

* `format` should be required -- this is a backwards incompatible, normative change.
* `profile` should be required when there is one defined for the profile in use. This means we can only really strongly recommend it, and link from the spec to the list of known profiles.
* `label` should be optional, but called out as useful.

We need to consider the requirements for `type` around external resources, per #817.

**Comment by zimeon** [comment]
Eds' discussion: we feel that `format` should remain SHOULD and not become a MUST. It is common practice to add it but it does not seem essential

**Comment by azaroth42** [comment]
Noting relationship with #1275, #1276, and #1284.

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#external-links

**Comment by zimeon** [comment]
:+1: agree done

**Comment by mikeapp** [comment]
👍 done
