### ISSUE TITLE
Make Image API level 0 / static use case more explicit

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1231]
Given @jrochkind's [experience](https://bibwild.wordpress.com/2017/08/29/full-res-pan-and-zoom-js-viewer-on-a-sufiahyrax-app/), we should review and make explicit that level 0 compliance is driven by the ability to create a completely static implementation that can be used, e.g. with openseadragon, leaflet, etc.

We could go even further and put the algorithms for making the requisite _pile-o-tiles_ for those in an annex note or on Github, whatever.

**Comment by zimeon** [comment]
I think it would be helpful to make the goals and requirements of level0 more explicit. Many (all?) level0 implementations out there don't quite stick to level0 (e.g. requesting a thumbnail that isn't listed in `sizes` is not following level0) but it would be pretty easy to fix these issues if highlighted. One idea would be to add a level0-tile-source-and-validation suite -- something that you can point a supposedly level0-compliant client out and it tells you the requests for derivatives that aren't specified by the level0 `info.json` (I have done this manually while developing [`iiif_static.py`](https://github.com/zimeon/iiif/blob/master/iiif_static.py) by generating a tileset and watching for 404's in a log during use).

**Comment by azaroth42** [comment]
Closed by #1436
