### ISSUE TITLE
Consider non-linear navigation patterns

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1238]
While a manuscript or letter has a (likely single) linear navigation order, other object types do not.  For example, even without a 3d model, a series of photographs of a statue makes no real difference whether you rotate through the images clockwise or counter-clockwise.  Even books are three dimensional -- the spine might typically be put at the end of the sequence as it's not very interesting, but if you were wanting to rotate around the views of cover, spine, leading edge, bottom edge, top edge and back cover, there's no "correct" linear order.  This can't be solved with multiple sequences, as it would require every permutation.

(/ht discussions with @workergnome)

**Comment by zimeon** [comment]
`renderingHint: your-guess-is-as-good-as-mine`

But, seriously, one use case above is "no-order". That could be expressed as a `renderingHint`.

The more general case of lots of possible paths, with or without a preferred start point, would seem to require some sort of mapping from a given canvas to other canvases. If I imagine a cube with 6 painted sides then each side could have a left, right, up, down to get to the adjacent sides. That _might_ generalize to some sets of photographs of a single object (e.g. statue0 and be a lower bar option that a full 3d model of orientations and locations of views.

**Comment by azaroth42** [comment]
`renderingHint: "individuals"` is maybe close enough already?

If there are lots of possible paths, they could be expressed as hotspot annotations ... I think the question is whether or not there's an easier solution for a general, broad case.

**Comment by azaroth42** [comment]
Need to see some experimental implementations to see what can be done, and then see if it generalizes to something cross-domain and broadly useful. Defering.

**Comment by azaroth42** [comment]
Closed by the removal of Sequence. Now there can be a list of Canvases that are items, which then are referred to by ranges without a notion of a particular sequence or order.
