### ISSUE TITLE
add id to each table in Presentation spec

### ISSUE THREAD

**Issue by jronallo** [IIIF/api#1239]
It would be nice if there were ids in the HTML output so that it is possible to link directly to various tables in the specification. I'm thinking particularly of the "Summary of Metadata Requirements" section of the Presentation spec.

There's a link to the [heading for the section](http://iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements), but I'm not seeing a way to deep link to a table like the "Paging Properties".

**Comment by azaroth42** [comment]
And for tables in the other specs too.

**Comment by azaroth42** [comment]
Closed by #1319
