### ISSUE TITLE
Specify the valid values for size pct:n

### ISSUE THREAD

**Issue by jcoyne** [IIIF/api#1240]
Should `n` be an integer or are floats allowed/required to be supported?

**Comment by azaroth42** [comment]
Should copy the string from region percents:  "These may be floating point numbers."

**Comment by jcoyne** [comment]
@azaroth42 I feel that "may" is potentially too weak.  Does that mean the user may provide a FP, or that the server may support them?

**Comment by azaroth42** [comment]
Server support is given in the compliance levels document:  http://iiif.io/api/image/2.1/compliance/#region

We could expand both to say:

> Each comma separated value may be supplied as either an integer or a floating point number.

?

**Comment by jpstroop** [comment]
Closed by #1438
