### ISSUE TITLE
Quoted integers/floats should still not be allowed

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1252]
From IIIF/presentation-validator#55:

> The validator reports an error "Validation Error: sc:Canvas['height'] does not accept a unicode, only an integer" for quoted integers. This is a python issue, and probably not intended.
> Json-ld uses type coercion to identify values. Whether or not a value is quoted does not indicate its type. See https://www.w3.org/TR/json-ld/#typed-values. Also, in RDF all literals are quoted, so an fromRDF transformation to JSON-LD would not arbitrarily remove the quotes for an integer.

It is intended, as the Presentation API makes the (implicit) additional requirement that integers in RDF be represented as integers in JSON.

I think this falls under the same decision as #1131 and #920 -- we should aim to be as strict as possible with the representation to prevent the need for type checking, or in this case type coercing from string to integer. We are building an API to be used without knowledge of Linked Data/RDF, that also happens to be useful in that context.

My proposal is that quoted integers/floats NOT be allowed, and we call this out explicitly in the specification.

**Comment by zimeon** [comment]
Perhaps a key bit of input data would be: "What do you need to do in JavaScript to read both forms?"

**Comment by christopher-johnson** [comment]
I have confirmed that quoted integers _do not work_ with Mirador > 2.4.0.  It is very easy to cast a quoted property value (i.e. String) as an integer in javascript with the parseInt() function.   Unfortunately, Mirador does not do any type coercion as it does not use the JSON-LD processor for deserialization nor does it cast any values to integers, which is certainly the cause of the problem.

**Comment by azaroth42** [comment]
Notes:
 * In conflict with design principles around JSON and simplicity
 * Focus has been on interpretation as JSON-LD, not creation from RDF
 * Major breaking change
 * Makes developers unhappy
 * Can't find a JSON-LD context that auto-converts
 * To do post-processing properly would require ontology aware descent of the entire tree -- the context is insufficient as it should not assert the `@type` on the property in cases where the range could be either int or float (for example). More kludgey would be to process only properties known to be ints/floats. Very kludgey would be a regex that looks for height,width,duration in the string representation.

Ed's proposal: close wontfix

**Comment by christopher-johnson** [comment]
Why is allowing quoted integers a "breaking change"?  And why does it make developers unhappy?  What is kludgey to me is that in your API, JSON syntax overrides an absolutely legal JSON-LD representation.  I wonder what @gkellogg thinks about this.

**Comment by gkellogg** [comment]
JSON-LD is intended to be developer friendly, and the use of native representations simplified the lives of those that are really just working at the JSON level. Too bad JSON doesn’t have a native representation for dates.

**Comment by christopher-johnson** [comment]
I have observed that a JSON native type that is assigned `@type` in an `@context` will not compact.
[Here ](https://json-ld.org/playground/#/gist/aaed79b4e7e536bb83b46ca87baa0d35 )is a gist that shows this.  
I guess that the `@type` assignment is superfluous if the JSON schema overrides it.

**Comment by azaroth42** [comment]
JSON-LD best practices promotes the use of native types: https://json-ld.org/spec/latest/json-ld-api-best-practices/#native-values

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting

**Comment by azaroth42** [comment]
No change needed.

**Comment by zimeon** [comment]
:+1: agree done (no-op)
