### ISSUE TITLE
Image API: Size should provide guidance on whether to include full size if supported.

### ISSUE THREAD

**Issue by jcoyne** [IIIF/api#1254]
Currently the size says:
> Sizes (optional): A set of height and width pairs the client should use in the size parameter to request complete images at different sizes that the server has available. This may be used to let a client know the sizes that are available when the server does not support requests for arbitrary sizes, or simply as a hint that requesting an image of this size may result in a faster response. A request constructed with the w,h syntax using these sizes must be supported by the server, even if arbitrary width and height are not.

Can you add some guidance as to whether the server SHOULD or SHOULD NOT include a full size in this list if it is supported?  (Presently Cantaloupe does not)

**Comment by jpstroop** [comment]
See #872, but perhaps we should revisit.

**Comment by jpstroop** [comment]
Oh wait...not exactly the same issue. I think any size that is available should be listed. The challenge, of course, is that for a level 2-compliant server, _any_ size is technically available. I agree that the fuzzy semantics of `sizes` is a problem.

**Comment by jcoyne** [comment]
I'm just suggesting guidance for implementers with regard to this one corner case.  I.e. is it reasonable for me to open an issue to cantaloupe and say "Sizes should contain the full size dimensions"?

**Comment by azaroth42** [comment]
Sizes are the preferred sizes. If it's level 0, then the preferred sizes are the only sizes.  If it's level 2, then the preferred sizes are ones that can be delivered the most efficiently, and thus likely the power of 2 JP2 levels.  If you're only running off a single raster image, and there's no more or less efficient sizes, then just pick some :)

**Comment by azaroth42** [comment]
I don't imagine that @jpstroop will want to put in the full size dimensions of his 150k pixel scroll :D

**Comment by zimeon** [comment]
To @jcoyne's [question](https://github.com/IIIF/iiif.io/issues/1254#issuecomment-330889298), I do **not** think it is reasonable to open an issue with cantaloupe. Outside of level0 implementations, one would expect an entry in `sizes` only for particularly efficiently provided or preferred sizes.

May want to revisit spec for clarity on this.

**Comment by azaroth42** [comment]
Closed by #1439

**Comment by zimeon** [comment]
Clarification was added in http://iiif.io/api/image/3.0/compliance/#5-level-0-compliance
