### ISSUE TITLE
Clients SHOULD present first range structure

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1255]
If the publisher has a multiple top level structure hierarchies (e.g. logical versus physical structures), and has a preference for which the viewer should display by default, then the first hierarchy SHOULD be displayed by the client as a default.

Further evidence towards #1193 plus an additional client requirement on top of that.

**Comment by azaroth42** [comment]
Further clarified by #1259.

**Comment by zimeon** [comment]
Discussed in Getty A/V meeting with consensus that " the first hierarchy SHOULD be displayed by the client as a default".

**Comment by azaroth42** [comment]
Closed by #1304. Why aren't these being auto-closed?
