### ISSUE TITLE
Consider a range viewingHint for generating navigation based on thumbnails

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1259]
Example use case - generate thumbnails every 10s along a scrubbing bar for a video.
 - Create a range with a child range for each 10s
 - The thumbnail property of each range is displayed as the user drags the scrubbing bar

Other summary navigation experiences could be generated from this data, e.g., a sheet of thumbnails used to jump to points of the video. The same technique could give access to parts of a book, it is not AV-specific.

We don't want the client to render this range as a hierarchical TOC. The viewingHint is required to tell the client to ignore this range for generating regular navigation, and use it only for "visual" navigation.

Suggestions for name of viewingHint:

* visual-nav (but it might not be visual)
* thumbnail-nav (use the thumbnail property of child ranges)
* summary-nav

**Comment by zimeon** [comment]
Eds' meeting: need more discussion of possible hints

**Comment by azaroth42** [comment]
Contingent on external range issue: #1218

**Comment by azaroth42** [comment]
No objections on AV call:  https://docs.google.com/document/d/1QG_eMA-decmrKpE2UClE6XvVD_k32AOYQ1TD5Suf9rg/edit#

**Comment by azaroth42** [comment]
Propose `thumbnail-nav` as the `behavior` name. At this stage I think we have to try writing it up and see if it sticks.

**Comment by tomcrane** [comment]
See if this sticks: https://github.com/IIIF/api/pull/1364/files

**Comment by tomcrane** [comment]
AV Call - include an example that isn't time-based media, such as a scroll.

**Comment by azaroth42** [comment]
Closed by #1364
