### ISSUE TITLE
Rename otherContent to annotations

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1262]
E.g. in 2.1.1 we can annotate Ranges and Manifests, as described here:
  http://iiif.io/api/presentation/2.1/#comment-annotations

**Comment by tomcrane** [comment]
`content` permitted on other resource types? This doesn't feel like the right name for the term, but is no less right than `otherContent` was.

**Comment by azaroth42** [comment]
Impacts #1068

**Comment by tomcrane** [comment]
As per #1068 - we need a single term for linking to annotations, but `content` might not be the right term.

**Comment by azaroth42** [comment]
From #1068, proposal is `annotations`

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting to use `annotations`

**Comment by mkanzaki** [comment]
Property for textual annotaions embedded in a Canvas is ``items`` or ``annotations`` ? What if the same textual annotation is saved in a different file (as in v2) ?

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#annotations

**Comment by mkanzaki** [comment]
I can't see any difference in the `annotations` section from the cache of Oct 13...
