### ISSUE TITLE
posterCanvas

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1263]
(From AV Group meeting)

A canvas outside of the sequence (a property of a manifest), that is a representation of the content with potentially different dimensions. It has a different purpose from a thumbnail. Think Netflix, Amazon Prime, BBC iPlayer, etc - the thumbnail is used to attract the user, to open the specific item (often alongside other thumbnails representing other items). Once selected, the item doesn’t start playing immediately. Instead you see the poster image, which might be displayed with other metadata about the object. The poster image for time-based media exists outside any time dimension of any of the object’s canvases, it is there to fill the “null time” before the user starts to play the content, before the time dimension of any of the item’s content starts. When the main content is video, a client would be expected to replace the poster with the playing content; when the content is audio only, and there is nothing else to see, the client to keep the image on screen. posterCanvas = “Object Level Enticement”

[If we have multiple canvases with videos in the same manifest, each may want its own poster to show before playback? -> discuss further later?]

Why posterCanvas and not posterImage, or some other property that expects an image resource? More flexible - e.g., a posterCanvas for a 3D object could be a x,y,duration canvas of a short video flyaround of an object. Could be annotated with overlay text? Or discourage annotation of this out-of-sequence canvas? 

The out-of-sequence notion is important - it is outside of the time dimension of the object it is the poster for.

Questions - is this a step too far? Is it just another type of thumbnail? How would client know what to use? poster is a common concept distinct from thumbnail across multiple institutions.

**Comment by azaroth42** [comment]
A convincing-to-me argument in favor was that if the canvas simply had h,w,d dimensions then the client would be forced to render the spatial content, when the intent is only to provide something to look at if there is space to render it.  A "winamp" style player which only has audio controls should be a sufficient implementation for plain audio.

**Comment by tomcrane** [comment]
This could also be a Canvas annotated on to the manifest with the motivation `poster` (`postering`?...)

**Comment by tomcrane** [comment]
(AV call - @mikeapp) Are we conflating use cases here?

* Something to show while content buffering
* Something to show while main content plays
* An enticement to view the main content

**Comment by mikeapp** [comment]
I also had some concerns about the various use cases and the fixed aspect ratio of the Canvas.   An aspect ratio (not to mention the content) selected for a screen-wide banner enticement might look odd elsewhere - and require letterboxing or overflow/cropping - if used, for example, as a poster.   

As @tomcrane notes there is the same issue with thumbnails of unusually wide or tall objects, but perhaps more visible in this case if the poster is a central element of the UI.

**Comment by tomcrane** [comment]
AV Call - change cardinality of posterCanvas to allow a choice (but NOT to be a sequence, not content)

On the grounds that changing our mind would be a breaking change.

Spec should warn about time-based media in posterCanvas Canvases conflicting with time based media of content. Cookbook?

**Comment by zimeon** [comment]
See #1356 for PR fixing
