### ISSUE TITLE
Assess use of renderingHints with duration canvases

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1264]
Discuss the current renderingHints and ensure that they make sense with duration only canvases and manifests.

**Comment by zimeon** [comment]
I current draft: http://preview.iiif.io/api/prezi3/api/presentation/3.0/#renderinghint

**Comment by azaroth42** [comment]
Eds' proposal:

* `individuals`:  Default behavior for duration canvases.
* `paged`: Not valid for d canvases, same semantics as w,h for w,h,d
* `continuous`: Not valid for d canvases, same semantics as w,h for w,h,d
* `multi-part`: Okay? Four manifests representing operas, each part of a broader cycle
* `non-paged`: Not valid for d canvases, same semantics as w,h for w,h,d
* `facing-pages`: Not valid for d canvases, same semantics as w,h for w,h,d
* `none`: Same semantics
* `no-nav`: Same semantics
* `auto-advance`: Only for things with a duration
* `together`: Same semantics

**Comment by zimeon** [comment]
Perhaps `continuous` should note that for make d-only canvases follow, use `auto-advance`

**Comment by azaroth42** [comment]
Continuous + auto-advance = piano roll player

**Comment by azaroth42** [comment]
Add a column to the table for W,H,D (or similar) validity

**Comment by beaudet** [comment]
consider use case where you'd have an in-exhibition viewer that cycles through via auto-advance and upon reaching the end, starts over from the beginning.  Also consider the use case where you would have end-user interaction that would suspend the auto-advance behavior until a certain timeout would be reached at which point the viewer either starts over or returns to the last auto-advanced state and resumes.

**Comment by beaudet** [comment]
some ideas for renaming renderingHint:

interactionPattern
clientBehavior
viewerBehavior
viewingPattern

**Comment by azaroth42** [comment]
Noting the action needed to close the issue is to add a column to the table.
