### ISSUE TITLE
Validate client requirements spelled out in section 3

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1271]
Client requirements are now spelled out in [3. Resource Descriptions](http://preview.iiif.io/api/prezi3/api/presentation/3.0/#resource-properties) of the prezi3 draft. These need validation by the community.

**Comment by azaroth42** [comment]
Proposal to dedicate a technical call to this issue in early 2018.

**Comment by tomcrane** [comment]
What is a client?

* A standalone viewing application
* A user experience of a web page that presents a IIIF resource using a mixture of components.

UV, Mirador vs Thumbnail strip component - these are all clients, but the latter fails to meet most of the _MUSTs_, unless the user experience includes other components that meet other parts of the spec client requirements.

Publishers won't publish IIIF if their important metadata is ignored when reused by others on the web, but spec implementations by an institution can do whatever they like.

Client requirements:

If you are using someone else's manifest, you must construct a user experience (by whatever means, combination of components, full-fat viewer etc) that meets the "client requirement" _MUSTs_ of the specification.

A "full" implementation (i.e., that claims to be full) must do the _MUSTs_.
Client _MUSTs_ apply to products that claim to be self-contained compliant IIIF viewers, not to a web page that uses IIIF to show your own things.

Section of spec that establishes what "client" means in the rest of the spec - covers Principles of reuse and the paras above.

Add section 1.3?

**Comment by workergnome** [comment]
I can think of many software agents and clients that will support IIIF but will not be explicitly viewers--for instance the IIIF Manifest Editor supports IIIF, but is not a viewer, and I would imagine a IIIF "shopping-cart" system that allows people to build on-the-fly collections or manifests would also not support all client requirements, particularly around the display of metadata.

Is our intent to discourage these sorts of agents, or to provide guidance around a very specific type of client that's a "full IIIF viewer"?

**Comment by tomcrane** [comment]
Neither.

I've updated the text in my comment slightly as it was not very clear as hastily captured notes.

Most of client requirements really only apply to the second pair of bullet points in my comment above. In order to encourage all sorts of development activity around IIIF, from self-contained viewers to specialist components to ad-hoc experiences, we need to define what we mean by Client, and if we don't think _Client_ can be bent far enough to fit those bullet points, we need some other way of saying it.

**Comment by zimeon** [comment]
Note introduction of text that defines clients in https://github.com/IIIF/api/pull/1474/files#diff-35b93d1a4cd76f02960d65b1ed15692bR157

**Comment by workergnome** [comment]
As a thought--are we worried about contractual or legal issues with client MUSTs?  I know that many of the image rights issues we run into are because someone added a legal requirement that we follow a requirement document or a spec without understanding the nuances of what was said.

What could be the implications of someone interpreting the MUSTS in a very strict way, without a full understanding of the implications?

**Comment by benwbrum** [comment]
I've just reviewed the 3.0 client _MUSTs_, and see the following gaps in our existing implementation of the FromThePage crowdsourcing platform as a IIIF client:

* "Clients must render `metadata` on a Manifest."  This is not something we implemented originally, as we were not comfortable caching and re-presenting a stale copy of an institution's metadata to end users.  It's not a huge burden to add.
* "Clients must render `requiredStatement` on every resource type."  We can implement this when we support prezi 3.0, but absolutely do not want to interrupt the user's flow to fling splashy copyright/restriction statements in front of them as they navigate from one document to another, nor one page to be transcribed to another.  Most likely, this will be presented as a footer on documents imported via IIIF.  (I'm pretty sure that most of our clients--institutions importing their own IIIF materials onto FromThePage for crowdsourcing--will be happier with this than with some lightbox flashing at their users.)
* "Clients must render `rights` on every resource type." We can add this in a footer.
* "Clients must render `logo` on every resource type."  Ditto this.

For our purposes, I really don't see big problems with any of the MUSTs, so long as they don't interrupt the user's data-entry workflow by presenting distracting or irrelevant information.  (See ["No Windows. One Exit. Free Drinks: Casino-Driven Design for Crowdsourcing](https://www.propublica.org/nerds/casino-driven-design) for an example of the challenges with navigation links, logos, etc. in crowdsourcing.)  Only the `requiredStatement` element has implementation instructions specific enough to be worrisome.

**Comment by tomcrane** [comment]
Hi @benwbrum - do you consider the new paragraph in the spec sufficient to give you license to ignore a MUST in circumstances where you think FromThePage is exempt from the definition of "general purpose client"?

> This section also defines processing requirements for clients for each of the combinations of class and property. These requirements are for general purpose client implementations that are intended to be used to render the entire resource to the user, and not necessarily for consuming applications with specialized use or individual component implementations that might be used to construct a client. The inclusion of these requirements gives publishers a baseline expectation for how they can expect implmentations advertised as compliant with this specification to behave when processing their content.

I didn't cover applications like FromThePage in my comment above https://github.com/IIIF/api/issues/1271#issuecomment-367979451 which outlines some of the other scenarios.

> Most likely, this will be presented as a footer on documents imported via IIIF.

That seems entirely reasonable to me!

**Comment by benwbrum** [comment]
That looks good to me, @tomcrane!

**Comment by azaroth42** [comment]
@mejackreed @rsinghal @aeschylus @ahankinson 

A review from Mirador or Diva, to go along with UV and From the Page, and I would consider this closable?

**Comment by mejackreed** [comment]
👍 without a certification or validation process, these "requirements" don't seem enforceable. So I'm fine with it. As long as the community continues to be open to adding things to iiif-awesome and related resources without a certification step

**Comment by azaroth42** [comment]
Definitely no intent to require certification or anything like that. It's at best a checklist for people deciding which client to use, such that they can put in a tender "the implementation must conform to all of the client requirements of the specification" or "all MUSTs and SHOULDs".

**Comment by azaroth42** [comment]
Given above review from @mejackreed, I think we're good to close.  +1s?
