### ISSUE TITLE
 xsd:integer data type assignment on JSON schema native type prevents compaction

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1272]
ref #1252 
datatype assignment in `@context` should be removed since the JSON schema explicitly defines an unquoted value as an integer.

**Comment by azaroth42** [comment]
It seems to compact okay in the JSON-LD playground:
    https://json-ld.org/playground/#/gist/e9f3b81219d387b0a4513b046988cca5

That said, I don't see any value in including it in the context, and we should take them out of all of the contexts, following the reasoning in #946.

**Comment by christopher-johnson** [comment]
Ref: [Here is a gist](https://json-ld.org/playground/#/gist/345908beef8eb3c02134ed32ff0fd5ef) that shows the problem clearly.
