### ISSUE TITLE
annotation list should allow service dereferencing by @type

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1273]
the 2.1 API indicates that the annotation list `@id` must be dereferenceable.  It is also possible to have dynamic lists generated from an annotation services that could depend on `@type`.  For example, a canvas may have multiple annotation services, one for AV and one for bibliographic metadata.  Clients should not make the assumption that the annotations are monolithically available by dereferencing the list IRI.  ref: #1068

**Comment by azaroth42** [comment]
What is the actual proposed change?  A canvas can already have multiple annotation lists associated with it.  We can't mandate that clients construct URIs to unknown annotation services.

Propose close invalid.

**Comment by christopher-johnson** [comment]
The change is that clients could check for an `service` key before dereferencing the annotation `@id` IRI.  If a `service` key exists, then that could be used with reference to an `@type` selector.  The client logic is too rudimentary with the current specification for any kind of specialized annotation implementations.  There is no mandate needed, just a provision that would allow such a structure to exist.

**Comment by azaroth42** [comment]
Anything can have a `service` :) To be more functional would require an annotation search protocol ... which we have in the Search API already.  So I still don't think that there's an issue here.
> http://iiif.io/api/presentation/2.1/#linking-properties

**Comment by christopher-johnson** [comment]
The Search API specified service seems to be understood currently as a manifest construct, and this is what clients expect.  The specification does allow the structure within the canvas object, so I think that this issue is covered.  This is more of a client implementation concern  Resolved.
