### ISSUE TITLE
Image API servers should be required to support OPTIONS method

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1274]
many Image API server implementations do not provide OPTIONS.  
The [CORS specification](https://www.w3.org/TR/cors/) indicates that OPTIONS is required for requests with preflight. 

This should be a MUST for all image API servers. This is not indicated in the 2.1.1 spec 
http://iiif.io/api/image/2.1/#image-information-request

**Comment by azaroth42** [comment]
We already link to the CORS specification in that section.  
Are you trying to use an html5 canvas to render the images? Or what situation is causing a failure due to the lack of support in implementations for OPTIONS?

**Comment by christopher-johnson** [comment]
There is no way for a client to know what access control methods a server supports without a preflight. 
It is a client bug, imo, if it simply allows the browser to throw errors for xhrs on servers that do not support what it wants.  This is demonstrated at http://projectmirador.org/demo/.

An xhr for content-type `application/json` or `application/ld+json` is **not** a "simple request", and technically MUST always require a browser preflight, (even though `jquery` allows it).   Angular.js xhr for example will trigger an OPTIONS preflight for content-type `application/json`.  

It is correct by the specifications to require a IIIF server serving a `application/ld+json` to support OPTIONS.  

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
[2] https://fetch.spec.whatwg.org/#cors-safelisted-request-header

**Comment by azaroth42** [comment]
Duh, for info.json which is what you linked to. Sorry, yes, implementations need to support OPTIONS on info.json for it to work.

:+1: to requiring it.

**Comment by tomcrane** [comment]
Also it should be called out in the Auth API and impl notes. It's kind of implicit in "support CORS" - you can't possibly make auth work without supporting OPTIONS, and there are several examples of it in the wild*, but the spec expects you to join the dots yourself about permitted HTTP verbs.

* e.g., https://github.com/digirati-co-uk/iiif-auth-server/blob/cbc803e55721f6ef71374bc2d4166bbfb39b1ad5/iiifauth/iiif_auth_server.py#L112

**Comment by azaroth42** [comment]
Closed by #1440

**Comment by christopher-johnson** [comment]
@azaroth42 I have observed that if one tries to fetch an image from the getty museum e.g.
```bash
curl -v -X OPTIONS https://data.getty.edu/museum/api/iiif/103470/full/224,300/0/default.jpg
```
Apache returns a 405 even though CORS headers are present.  Also, that image server does not support image API requests for some reason.  e.g.
```
https://data.getty.edu/museum/api/iiif/103470/full/90,0/0/default.jpg
``` will fail.  Not sure to whom this issue should be directed, but maybe you can pass it along to the IT support team at Getty.

If the browser cannot do a fetch preflight using OPTIONS, then the response is considered opaque, and this is incurs a large cache penalty.  I am experimenting with a progressive web app for IIIF, and CORS vs opaque responses is an important concept for the appCache, particularly for images.

Adding optional CORS headers and _requiring_ the OPTIONS method if CORS is used should be specified separately in the IIIF Image API.

**Comment by jpstroop** [comment]
@christopher-johnson 

https://data.getty.edu/museum/api/iiif/103470/info.json

Makes it clear that this is a level 0 implementation and does not support arbitrary size requests.

**Comment by azaroth42** [comment]
Level 0 is not required to support CORS, so we've done what we can in adding the headers. We'll support OPTIONS when we migrate the museum infrastructure over to using Loris.
