### ISSUE TITLE
profile property is not described in Presentation API

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1276]
And it should be, as we trigger client behavior from it.
Should it be a single URI or an array of URIs?

(c.f. #520, #1013 --> #1275)

**Comment by workergnome** [comment]
My money is on single, with addl. property as described in the proposal in #1275.

**Comment by azaroth42** [comment]
This is already done in Prezi3: http://prezi3.iiif.io/api/presentation/3.0/#profile modulo where the table of known profile URIs should live.
