### ISSUE TITLE
sc: namespace serves wrong content-type / does not support content-negotiation

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1278]
The content type provided for requests to the "http://iiif.io/api/presentation/2#" is "application/xml".  

It does not "Accept" alternate Content-Type headers from the client and does not serve "application/ld+json".  For validators that may want to parse the vocabulary as linked data, this is a problem.

Reference: https://www.w3.org/TR/swbp-vocab-pub/

**Comment by zimeon** [comment]
Current behavior: http://iiif.io/api/presentation/2# --302--> http://iiif.io/api/presentation/2/ontology.xml which is an OWL ontology in RDF/XML served as `application/xml`.

I think RDF/XML (yuk) is really the normal way to serve OWL but the content-type should be `application/rdf+xml` instead of `application/xml`. I'm not sure whether conneg is worth the hassle, not sure how many people are trying to use JSON-LD with OWL.

**Comment by christopher-johnson** [comment]
here is the IIIF Presentation [ontology](https://www.w3.org/2012/pyRdfa/extract?uri=http%3A%2F%2Fiiif.io%2Fapi%2Fpresentation%2F2%2Fontology.xml%23&format=json&rdfagraph=output&vocab_expansion=false&rdfa_lite=false&embedded_rdf=true&space_preserve=true&vocab_cache=true&vocab_cache_report=false&vocab_cache_refresh=false) as JSON-LD.

It makes little difference actually what format RDF is in, because it should be concrete syntax neutral.  The important thing is to serve the RDF documents with a content type that is recognizable by implementations like Jena RIOT.  `application/rdf+xml `would work fine for me.

**Comment by glenrobson** [comment]
I’ll have a look at returning application/rdf+xml.

**Comment by glenrobson** [comment]
Both of the ontology xml files should now be returning `application/rdf+xml` instead of `application/xml`. Let me know if you spot any issues.

**Comment by zimeon** [comment]
LGTM, thanks @glenrobson!

```
simeon@Cider ~> curl -# -I http://iiif.io/api/presentation/2/ontology.xml | head -4
HTTP/1.1 200 OK
Content-Length: 11546
Content-Type: application/rdf+xml
Date: Thu, 05 Oct 2017 02:35:12 GMT

simeon@Cider ~> curl -# -I http://iiif.io/api/image/2/ontology.xml | head -4
HTTP/1.1 200 OK
Content-Length: 4544
Content-Type: application/rdf+xml
Date: Thu, 05 Oct 2017 02:35:31 GMT
```
