### ISSUE TITLE
iiif: namespace does not provide a vocabulary document

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1279]
the iiif: namespace URI [http://iiif.io/api/image/2#](http://iiif.io/api/image/2#) redirects to a verbose html description of the IIIF Image API specification when it should simply provide the vocabulary as linked data.

This could be accomplished by implementing content negotiation that provides [http://iiif.io/api/image/2/context.json](http://iiif.io/api/image/2/context.json) when a client sends a request header "Accept" "application/ld+json"

**Comment by zimeon** [comment]
I think that having the namespace URI resolve to the documentation is the best default behavior given that there isn't an ontology.

I'm not sure who/what would use conneg to the context from the namespace URI.

**Comment by christopher-johnson** [comment]
Vocabulary and ontology are basically interchangeable in relation to namespace URIs.  There is not a mandate that says only OWL can be served from a namespace URI.  

A good example is Activity Streams. 
[https://www.w3.org/ns/activitystreams#](https://www.w3.org/ns/activitystreams#)  

They serve the document with HTTPS, it redirects to the verbose page with a browser GET, and with a client who accepts application/ld+json, the same URI returns the vocabulary, which is an `@context` just like the Image API.  IMO, those are the three principle ingredients required for a sound namespace implementation.

**Comment by azaroth42** [comment]
The ontology is:  http://iiif.io/api/image/2/ontology.xml 
No, the namespace doesn't redirect to it, and with the correct Accept header it probably should.

**Comment by azaroth42** [comment]
@glenrobson Can `http://iiif.io/api/image/2#` redirect to `http://iiif.io/api/image/2/ontology.xml` when the `Accept` header of the request is "application/rdf+xml"

Similarly for `http://iiif.io/api/presentation/2` redirecting to its ./ontology.xml file.

Many thanks!

**Comment by glenrobson** [comment]
For info `http://iiif.io/api/presentation/2` already redirects to the ontology. With `http://iiif.io/api/image/2#` would it be OK to redirect without checking the accept header? Currently `http://iiif.io/api/image/2#` redirects to `http://iiif.io/api/image/2.1/`

**Comment by glenrobson** [comment]
I went with forwarding all requests to `http://iiif.io/api/image/2#` to the ontology. Feel free to re-open if you think it requires the accept header check. 

```
curl -v "http://iiif.io/api/image/2#" >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.222.225.108...
* TCP_NODELAY set
* Connected to iiif.io (52.222.225.108) port 80 (#0)
> GET /api/image/2 HTTP/1.1
> Host: iiif.io
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html
< Content-Length: 161
< Connection: keep-alive
< Date: Thu, 16 Aug 2018 01:00:32 GMT
< Location: https://iiif.io/api/image/2/ontology.xml
< Server: nginx/1.12.1
```
