### ISSUE TITLE
ontology=sc:ViewingDirection sc:ViewingHint  @context=sc:viewingDirection sc:viewingHint

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1280]
The [ontology](http://iiif.io/api/presentation/2# ) defines these classes with the uppercase "V".  

The [context](http://iiif.io/api/presentation/2/context.json ) with a lowercase "v".

**Comment by azaroth42** [comment]
Close Invalid -- the context is the relationship, the ontology uppercase is the class.
Working as expected.

**Comment by christopher-johnson** [comment]
I do not agree.  Why is it necessary to make this confusing distinction?  A class can also be used as an Object Property (i.e. a relationship).  In any case, the `@context` SHOULD include all objects that are specified in the ontology.

**Comment by azaroth42** [comment]
Whether a class can or cannot be used as a relationship is irrelevant as we have the relationships separate from the classes.

Whether @context should include all of the terms in an ontology or not is not a question that we've come up against. We have used the context as the means to construct the IIIF JSON-LD representation, which is (after all) the point of a JSON-LD context -- to map between JSON and RDF.  
As the class ViewingHint is not ever used in the IIIF representation, there isn't a need to map that class into JSON... and hence no need to have it in the context.

Similarly, we do not define external terms that are needed in the JSON in the ontology, but they are included in the context.

**Comment by christopher-johnson** [comment]
It is not irrelevant, as per the RDF schema a [property is an instance](https://www.w3.org/TR/rdf-schema/#ch_property) of rdf:class.  I assume that the term "relationship" is understood to mean an "object property" distinct from a "datatype property".

If an object property defines a relationship to a member instance, then the named individual range object _should_ be defined with an `@type` reference to its parent.  So, any range of `viewingHint` , for example, could be defined in the API as being an `@type` "ViewingHint".  This is a proper method to cast individuals in JSON-LD.

RIght, the ontology should not include externally defined terms, but that is not the issue here.

**Comment by christopher-johnson** [comment]
An RDF object property works like type casting in Java.  
```java
Person person = new Person(); 
```
or in RDF
```turtle
<> Person <person>.  
```
So, in truth, it is redundant (and imo, _confusing_) to define distinct "lower case" properties for "relationships". 

 `<> sc:Canvas <canvas>` _is equivalent to_ `<> sc:hasCanvases <canvas>` for example.  

The lower case convention is suitable for datatype properties, but for object properties it is superfluous.  There is no error or **invalidity** in this issue.  Please reevaluate the rather quick dismissal of it and make the appropriate corrections.

**Comment by azaroth42** [comment]
Reopening, and we'll discuss next week in Toronto.

**Comment by azaroth42** [comment]
After discussion, it's working as expected. Re-closing.
