### ISSUE TITLE
presentation api @context response headers: Content-Type: application/json?

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1282]
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 5198
Content-Type: application/json
Date: Fri, 06 Oct 2017 05:18:51 GMT
ETag: "da9063fda5d05b33e0fc0963cc9ac6bf"
Last-Modified: Thu, 05 Oct 2017 22:18:09 GMT
Server: nginx/1.10.3
Connection: keep-alive

Server does support content negotiation, though it is irrelevant.  The default Content-Type for a JSON-LD `@context` SHOULD be `application/json` and not `application/ld+json`

**Comment by christopher-johnson** [comment]
In giving [due consideration](https://groups.google.com/forum/#!msg/trellis-ldp/di0Nhvl6vAI/VfNurycMBwAJ) to the fact that a JSON-LD context is actually _not_ a JSON-LD document, I now believe that it is preferable to serve context documents with Content-Type `application/json` and represent them in RDF as http://www.w3.org/ns/ldp#NonRDFSource

**Comment by azaroth42** [comment]
I don't believe this is correct. A document containing only a JSON-LD context but no instance data is still a JSON-LD document.

The W3C context documents all serve as JSON-LD, as does schema.org. For example:
* https://schema.org/docs/jsonldcontext.json
* https://www.w3.org/ns/anno.jsonld
* https://www.w3.org/ns/activitystreams.jsonld

Propose close wontfix.

**Comment by christopher-johnson** [comment]
Without a provable method to validate what is and is not JSON-LD, your argument is without substance.  
https://github.com/json-ld/json-ld.org/issues/543#issuecomment-340263154
