### ISSUE TITLE
presentation api @context response headers: no cache control

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1283]
Ref: https://json-ld.org/spec/latest/json-ld-api-best-practices/#cache-context

Example:
http://schema.org/docs/jsonldcontext.json
`Cache-Control: private, max-age=600`

**Comment by azaroth42** [comment]
I propose the following header:
`Cache-Control: public, no-transform, max-age=2419200`

Meaning: transparent caches should cache it, but must not modify it or its headers.  It should be considered as valid for 4 weeks after the request.

@glenrobson can this be added for all documents in:
* auth/1/ 
* image/1/ 
* image/2/ 
* presentation/1/
* presentation/2/
* search/1/

Thanks!

**Comment by glenrobson** [comment]
Sure will look into it.

**Comment by glenrobson** [comment]
I believe this is now fixed, see example below. 
```
curl -v "http://iiif.io/api/presentation/2/context.json" >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.222.225.119...
* TCP_NODELAY set
* Connected to iiif.io (52.222.225.119) port 80 (#0)
> GET /api/presentation/2/context.json HTTP/1.1
> Host: iiif.io
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 5138
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: public, no-transform, max-age=2419200
```
