### ISSUE TITLE
Pattern for when to use URI string or JSON object

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1284]
Reviewing the situations when we use URIs as strings rather than as the `id` of a resource encoded as a JSON object, I propose the following design pattern:

If a URI could be treated as a value in an enumerated list, such that the context could assign a short form to it, then the URI _MUST_ be given as a string.  Conversely, if this is not the case and the number of resources is either unbounded or impossible to enumerate, it _MUST_ be given in the object form with at least an `id` and `type`. All enumerations defined by IIIF specifications _MUST_ be encoded in the respective context as easy-to-remember-and-use strings.

There are a countable number of renderingHints, renderingDirections, choiceHints, timeModes, __profiles__, features, and types, which must thus all be strings. There is an uncountable number of logos, licenses, thumbnails, canvases, images, etc. which thus must be given as objects.

**Comment by workergnome** [comment]
I agree with this proposal—it makes a good distinction. Does this effect the guidance given around community extensions provided by additional contexts, in that they might be full URIs or short forms?

**Comment by tomcrane** [comment]
👍

**Comment by jpstroop** [comment]
👍

**Comment by zimeon** [comment]
:+1:

To @workergnome 's point, I think that stuffing an extension URI into a field where a string is expected ends up being OK. An unaware client might interpret the URI as a string, but it would be unique and unsupported, and so ignored.

Minor mathy technical comment: the set of all URIs is [countable](https://en.wikipedia.org/wiki/Countable_set), so the difference is between a small number of `renderingHint`, `renderingDirection` etc, and a large number of `logo`, `license`, etc. ;-)

**Comment by mikeapp** [comment]
👍

**Comment by azaroth42** [comment]
To move forwards on this issue ... it's more fine grained than the current design patterns.

I propose a new section 3 to the patterns document that describes the JSON(-LD) design patterns we've adopted.

**Comment by azaroth42** [comment]
Change to consider towards #1479 fix is that we want to allow widely used / well known URIs defined by other specifications to be used directly without defining an alias for them in the context.  This results in arrays with both short strings and URIs, but that's okay ... the viewer just needs to process the URI as a string.

Proposed change to the last sentence of the middle paragraph (the actual text):

> All enumerated values defined by IIIF specifications or the appropriate IIIF extension registry MUST be encoded in the respective context as easy-to-remember-and-use strings. Externally defined URIs _MAY_ be used directly.

**Comment by jrochkind** [comment]
For those less familiar with json-ld, can you give an example of what a "object form with at least an id and type" might look like for a previous example which, if I understand correctly, previously would have been simply free text string?
