### ISSUE TITLE
Allow startCanvas on Manifest

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1285]
If the `renderingDirection` and the various canvas related `renderingHint`s can be aggregated up to the Manifest, then `startCanvas` should be allowed at that level as well.

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#startcanvas

**Comment by zimeon** [comment]
:+1: agree done

**Comment by sdellis** [comment]
If both the Manifest and a lone Sequence have different startCanvases specified, which one should be honored?

**Comment by azaroth42** [comment]
The Sequence. The more specific should override the more general.  There might be another sequence that doesn't have a start specified, which would then use the Manifest's definition.  Basically -- crawl up the tree looking for values and stop when you find one :)

**Comment by sdellis** [comment]
👍 Perhaps this could be one of the processing algorithms proposed in #1268 for Prezi3.
