### ISSUE TITLE
Clarify `related` to be only the "home page" of this resource

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1286]
The information carried in `related` is redundant with the information that can be carried in `metadata`, without the ability to have internationalized labels.  The client never needs to have the URI to the related resource, as the only thing that it will use it for is to generate HTML to display a link to the resource, unlike `seeAlso` or `service` for example where the client will interact with the resource directly. The set of related resources is a set, not a list, and hence the order of the links to be displayed is not deterministic.

Proposal: Remove the `related` property from Presentation 3.0 as redundant, and instead just put links into `metadata`.

**Comment by zimeon** [comment]
Sounds sensible, do we need to post question asking whether anyone is using `related` now?

**Comment by tomcrane** [comment]
This uses `related`:

https://exhibitions.library.nuigalway.ie/oshaughnessy-memoir/

Their manifest appears to be missing at time of writing, I'll update this with a more detailed example when it is back. Anyway, it works by offering the link provided by `related` to view the object on its "home" page as described here:

https://github.com/digirati-co-uk/nui-galway-viewer/blob/master/implementation.md#linking-to-other-representations

It makes explicit use of the semantics of `related`.

**Comment by tomcrane** [comment]
So I'm :-1: on deprecating related, I couldn't build this if it was buried in metadata.

https://github.com/digirati-co-uk/nui-galway-viewer/blob/master/galway-viewer/src/view/Supplemental.js#L82

**Comment by tomcrane** [comment]
OK, it's back - https://exhibitions.library.nuigalway.ie/oshaughnessy-memoir/ - most of the `linking` annotations open a view of the linked resource. If the linked manifest has a `related` property, the viewer provides a link to it.

**Comment by workergnome** [comment]
Couldn't you do that with `seeAlso`, though?  My feeling is that we need one property for display to humans (`metadata`) and one for external links that need to be understood by software (`seeAlso`).  

Could be missing something obvious, though

**Comment by azaroth42** [comment]
`seeAlso` refers to a machine readable document, rather than a human readable one. So I don't think that's the right pattern either. 

The memoir viewer makes the assumption that the related resource is 'view in repository' -- that label is hard coded.  If you applied the viewer to something that used related for a different purpose (as it can be any related resource) it would be wrong.  To me, that says that either the current structure is inadequate (no space for a label with related) or this is a very custom view, rather than an interoperable one.

**Comment by tomcrane** [comment]
I agree that the memoir is a specialist viewer that knows its content. The "View in repository" hard-coded label would not be appropriate generally. But "see more, for humans" would be appropriate, or better still the `label` property from the value of `rendering`. The behaviour of the viewer requires the semantics of `related` as currently defined, and couldn't work out what that link should be without it.

**Comment by azaroth42** [comment]
Well ... the definition of `related` is:

> A link to an external resource that describes or is about the IIIF resource.

Whereas `rendering` is:

> A link to an external resource that is an alternative, non-IIIF representation of the IIIF resource. [...] Examples might include the preferred viewing environment for the IIIF resource, such as a viewer page on the publisher’s web site.

I would argue that the memoir use case is actually `rendering`.

**Comment by azaroth42** [comment]
Agree it's not rendering.  

Useful to put all links to related resources in a consistent place in the UI, rather than per-institution ordering and language.

Proposal to make it more explicit / tighter definition.  Something like a reference to a human readable web resource about the catalog, the "home page" for the object.  Anything more complicated can go in metadata as it needs its own label to understand the type of relationship.

**Comment by tomcrane** [comment]
Same sense as http://xmlns.com/foaf/spec/#term_homepage

**Comment by tomcrane** [comment]
Discussing this right now wrt British Library use case, and the word "homepage" has been used several times for want of a better term. So I'm feeling better about `homepage` as the name of this term now.

Use case is a curated playlist of highlights (AV, but applies to other things). Highlights are ranges or canvases, `within` manifests, with each manifest having a `homepage` (the catalogue page) to go to if you're interested in learning more.

**Comment by mikeapp** [comment]
Community call 12/20.  No objections to renaming.   Leaning toward one `homepage` per manifest, questions about permanent URLs vs catalog pages.

**Comment by tomcrane** [comment]
`homepage` is applicable to resources other than manifests.

BL use case - multiple recordings in a manifest, identified by Ranges.
Each Range has a web page (catalogue page).

UV's "more info" panel shows range-specific information, mostly metadata, but would show a link to the `homepage` of the recording, which would change from range to range.

**Comment by azaroth42** [comment]
I don't think there's any intent to change related/homepage away from the current model of any resource MAY have a related.

**Comment by zimeon** [comment]
Fixed by #1380
