### ISSUE TITLE
Perhaps a typo "Note well that Annotation Lists must not be embedded within the manifest"

### ISSUE THREAD

**Issue by mejackreed** [IIIF/api#1293]
This sentence reads a bit strange to me. 

`Note well that Annotation Lists must not be embedded within the manifest`

Source: http://iiif.io/api/presentation/2.1/#annotation-list

Maybe the `well` is leftover from something else?

**Comment by zimeon** [comment]
Note well = Nota bene, I think this is just a writing style issue not a leftover or error. Having said that, I'd be fine to ditch the 'well' since we end up with a simpler sentence that means that same thing

**Comment by azaroth42** [comment]
I agree that we shouldn't carry this over to the next version, but we're not going to issue 2.1.2 to change this (I assume).  So I propose closing.

**Comment by zimeon** [comment]
Have verified that this language is not present in v3 draft (see http://prezi3.iiif.io/api/presentation/3.0/#annotation-pages) so agree close.
