### ISSUE TITLE
Document non-painting representations (e.g. 3d, pdf, office docs, etc)

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1297]
There are representations of objects such as 3d models, PDFs, office documents, and so forth that are renderable to a human (sometimes in the browser, sometimes not) but are not paintable to a canvas.  It would be valuable to refer to these representations in a consistent way that would allow systems that do understand them to do something appropriate.

Proposal:  Document that `rendering` with an appropriate `type` and `format` is the appropriate place for these sorts of related representations.

**Comment by tomcrane** [comment]
Yes, an explicitly call out distinctions between linking to a PDF about the object (which might be reasonably linked via annotation) and a PDF version of the object (a rendering of a canvas/range/sequence).

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by edsilv** [comment]
:+1:

**Comment by zimeon** [comment]
Fixed by #1382
