### ISSUE TITLE
http://library.stanford.edu/iiif/image-api/1.1/context.json is defunct

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1300]
See https://github.com/IIIF/api/issues/1299.  Same issue.

**Comment by azaroth42** [comment]
This is an issue for @eefahy and @tomcramer.  Unsurprisingly, IIIF does not control the library.stanford.edu domain.

**Comment by azaroth42** [comment]
Closing as the Stanford domain is outside of the IIIF scope. Please take it up with Stanford directly.

**Comment by christopher-johnson** [comment]
The reference is published here: http://iiif.io/api/image/1.1/
There should be a deprecation notice in that document which is in the scope of the IIIF.  And furthermore, all implementations should be made aware that this `@context` no longer supported or maintained by the IIIF.
