### ISSUE TITLE
3.0 Spec issue: refine Object definitions for "string" and "URI"

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1314]
there are many references to "string" and "URI" in the specification.  As a programmer, my interpretation of these references as Objects is that they are ambiguous and not consistent with the JSON-LD spec. 

Specifically, I have a problem with "The value MUST be a string." where the "value" is actually a "[term](https://json-ld.org/spec/latest/json-ld/#dfn-terms)".  A JSON-LD value has a unique definition in that it is never an IRI.  The confusion between value and IRI terminology in the spec is significant enough to merit further review.

Recommend qualifying "string" as a "JSON string", "JSON-LD value", "IRI string" or "String".  Also, for clarity, a distinction between "IRI", "URI" and "URL" could be established similar to [this](https://www.w3.org/TR/activitystreams-core/#urls) with IRI being the default used in the specification

**Comment by azaroth42** [comment]
The documentation is written from a JSON perspective, so that developers do not need to understand the differences in the underlying model between a string that's a string and a string that's a URI.

 We have tried to be consistent with "URI".  The only use of URL in the current prezi3 document is right at the end in the Authentication section. We will change this to URI for consistency.

**Comment by christopher-johnson** [comment]
The use of property "value" in the spec actually refers to property "range".  IMO, a term like "value" should be used carefully since it has a meaning in JSON-LD that deviates from JSON.       

If the spec intent is to constrain _instance_ (ref. JSON schema) values as JSON primitive types, then the reference in 5.1 to `JSON-LD Objects` should be removed.

RE: IRI vs URI.  RDF 1.1 defines referents with IRI.  So, it seems a localization if the spec simply defines entities as JSON URIs.  Up to you, but I cannot see the justification for not using RDF terminology where it certainly adds _global value_ to the design.

**Comment by zimeon** [comment]
Closed with #1318
