### ISSUE TITLE
Consistency: "HTTPS" or "HTTP(S)" 

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1321]
The text is inconsistent with regards to how it refers to HTTP / HTTPS. Proposed is "HTTP" for only HTTP, "HTTPS" for only HTTPS and "HTTP(S)" for either.

**Comment by zimeon** [comment]
:+1: agree with proposal (which will mean that almost everywhere we say "HTTP(S)")

**Comment by mikeapp** [comment]
👍

**Comment by tomcrane** [comment]
> which will mean that almost everywhere we say "HTTP(S)"

But we wouldn't use HTTP(S) here:

> It is _RECOMMENDED_ that an HTTPS URI be used for all resources.

(from https://github.com/IIIF/api/pull/1307/files#diff-35b93d1a4cd76f02960d65b1ed15692bR304)

(just checking)

**Comment by zimeon** [comment]
@tomcrane - yes

**Comment by azaroth42** [comment]
Closed by #1324 , #1333
