### ISSUE TITLE
Does Prezi "type": sc:Sequence/sc:Canvas = web anno "type": "AnnotationCollection"?

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1323]
AFAICT, there are overlapping semantics between` sc:Sequence` and `sc:Canvas` as described in the Prezi 3.0 and the "AnnotationCollection" (i.e. `as:OrderedCollection`) as described in the [annotation protocol](https://www.w3.org/TR/annotation-protocol/).   It seems to me that both `sc:Sequence` and `sc:Canvas` are equivalent with `as:OrderedCollection` since  `sc:Canvas` is an [Annotation Container](https://www.w3.org/TR/annotation-protocol/#annotation-containers), and `sc:Sequence` is a collection of Annotation Containers.  

Do Web Anno / AS types/properties compliment or override Prezi 3.0 types/properties?  Or, do you just expect divergent implementations?  Also, since `AnnotationCollection` is defined in the 3.0 spec as distinct from `sc:Canvas` and `sc:Sequence`, it appears as though there is not an intended correlation, which may add confusion (for people who actually think about these things).

**Comment by azaroth42** [comment]
I don't think's so. Canvases refer to AnnotationPages, not Annotations directly. Therefore Canvases would be AnnotationCollections in this view. Thus a Sequence would not be a Collection.

However a Canvas is clearly defined as an abstract time and space with height/width and/or duration properties. It would be a very strange AnnotationCollection that had those things.
Also, we use AnnotationCollection for its intended purpose of collecting related Annotations. In 2.x we call it Layer, and in 3.x it's a real AnnotationCollection.

**Comment by christopher-johnson** [comment]
RE: Paging.  LDP has its own [paging](https://www.w3.org/TR/ldp-paging/) that depends on Link Headers.  The collection paging semantics in Web Anno, Prezi and AS add a lot of complexity to the serializations, and are not as robust as the LDP model, since they depend on assumptions about the client's ability to support paging and do not offer an interaction model for the client to communicate its preferences.  The [Github API](https://developer.github.com/v3/guides/traversing-with-pagination/), for example, also uses a Link Header based pagination.  Arguably, Link Header pagination is much cleaner and generally easier for fromRDF implementations.  
 
RE: Collection properties.  From [AS-Core](https://www.w3.org/TR/activitystreams-core/#collections) "Collection objects are a specialization of the base Object [...] In addition to the base properties inherited by all Objects, all Collection types contain the additional properties: items | totalItems | first | last | current"  The base Object allows `startTime` and `endTime`, so duration does not seem strange to me.  Spatial dimensions for a collection are perhaps unique to `sc:Canvas`, but still not that odd.

FYI: The primary use case here is an LDP CRUD API for web annotations.  One could simplify things by using just one container (i.e. "the canvas").  I do not see the wisdom in having a separate container for "images" and "annotations about the images" or however this has been previously defined in 2.0.

**Comment by christopher-johnson** [comment]
I now suspect that it is not required for `sc:Canvas` to be a collection, nor is it necessary to embed annotations in a canvas object or manifest.  A centralized annotation service could be completely decoupled from these resources.  The IRI of the annotation would thus not need to correspond to the manifest resource, which would make distributed/federated annotation service implementation (multi-domain) possible.  

A straightforward Web Annotation Presentation interaction model would have the client GET a manifest document structure, read the collection of targets, and SELECT the annotations by `target` from the service.   As this perhaps represents a sharp deviation from the 3.0 design intent (and what IIIF clients will expect), I close this issue and work independently.
