### ISSUE TITLE
"repeat" behavior

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1328]
Dave Beaudet, in #1264:
> consider use case where you'd have an in-exhibition viewer that cycles through via auto-advance and upon reaching the end, starts over from the beginning.

I think that this is a separate behavior from "auto-advance" and needs its own identity.  I could imagine both cases where you want to repeat from the first canvas (as above), and situations where you don't (watching a multi-canvas video).

Propose:  "repeat" value for `behavior`. When this value and "auto-advance" are present, the client _SHOULD_ continue from the last canvas back to the first once the last canvas has been completed.

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
Good use case!  👍

**Comment by zimeon** [comment]
:+1: to `repeat` + `auto-advance` as described.

Does `repeat` without `auto-advance` suggest that a next or forward button would allow user action to go round in a loop?

**Comment by azaroth42** [comment]
Discussion on AV Call was also :+1: 
See: https://docs.google.com/document/d/1QG_eMA-decmrKpE2UClE6XvVD_k32AOYQ1TD5Suf9rg/edit#heading=h.spc57zabacow
