### ISSUE TITLE
Consistently talk about properties, their cardinality and language map values

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1330]
Issue came up in #1326 that text like _"one or more `summary`s"_ might be taken to mean either of:

  * one `summary` property, which may have one or more `summary` strings by virtue of being a language map
  * one or more `summary` properties, each of which may have multiple `summary` strings by virtue of being a language map

I like the idea of calling them "`name` properties" so we can talk about how many properties separately from how many values in language maps.

**Comment by azaroth42** [comment]
I agree that the wording can be tightened up here.

To use as examples:
> The value of the property must be a JSON object, as described in the languages section.
> A Collection must have at least one `label`.

> The value must be a JSON array, with each item in the array being a JSON object that must have an id property and should have at least one of type and format
> A Collection should have exactly one `thumbnail`, and may have more than one.

The intent is, respectively, that there MUST be a `label` property and it MUST have at least one value present in its language map; and that there SHOULD be a `thumbnail` property and if there is, then there SHOULD be exactly one value (which is a JSON object), there MAY be more than one value, meaning that the type of the property's value is an array (of JSON objects).

The issue with calling them "`foo` properties" is the conflation of JSON object property and data model predicate ... there's only ever one `label` or `thumbnail` key on the JSON object, even if they have multiple values in the abstract data model.

For the language maps, how about:  

> A _ClassName_ MUST have at least one value in the `propertyName` property.

?

**Comment by azaroth42** [comment]
Adding another slightly different case of behaviors or `behavior`s or `behaviors` ...

> Valid on AnnotationCollection, AnnotationPage, Annotation, SpecificResource and Choice. If this `behavior` is provided, then the client should not render the resource by default, but allow the user to turn it on and off.

Where there is both the property and a IIIF defined value for the property.

OTOH, I do NOT think we should move the values from `behavior`, `viewingDirection` and `timeMode` down in to the new values section, separate from their property definition ... raising the spectre [or is it a meltdown?] of why we have it for motivations only ...

**Comment by azaroth42** [comment]
How about ...

Currently:
> A Collection MUST have at least one label.

Means:
> A Collection MUST have the label property with at least one value.

Or:
> A Collection SHOULD have one thumbnail, and MAY have more than one.

Means:
> A Collection SHOULD have the thumbnail property with at least one value, and there MAY be more than one value.

**Comment by zimeon** [comment]
Fixed by #1411
