### ISSUE TITLE
Use https://example.org/ for content URIs in examples

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1334]
We are promoting the use of HTTPS for IIIF resources so it would be best to show this in the spec examples. I think this means a search and replace of `http://example.org/` with `https://example.org/` in the prezi 3 spec.

**Comment by tomcrane** [comment]
👍

**Comment by mikeapp** [comment]
👍

**Comment by azaroth42** [comment]
:+1:

**Comment by zimeon** [comment]
Fixed by #1377
