### ISSUE TITLE
Use of "AnnotationCollection" section heading is inconsistent with "Annotation Pages"

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1336]
We should probably use the section heading "Annotation Collections" instead if [AnnotationCollection](http://prezi3.iiif.io/api/presentation/3.0/#annotationcollection) in order to be consistent with [Annotation Pages](http://prezi3.iiif.io/api/presentation/3.0/#annotation-pages) (or otherwise we should change that one).

**Comment by zimeon** [comment]
This is actually a more general style question: in Presentation API 2.x we used the style of referring to special terms like [Canvas](http://iiif.io/api/presentation/2.1/#canvas) or [Annotation List](http://iiif.io/api/presentation/2.1/#annotation-list) in "plain English" style  in running text, i.e. "canvas" and "annotation list". That hasn't been done with Annotation Collection and Annotation Pages. 

I think we should retain the capitals on all terms throughout (so say "Canvas" everywhere) but never concatenate words to match predicates (so say "Annotation Page" and "Annotation Collection").

**Comment by azaroth42** [comment]
:+1:

**Comment by zimeon** [comment]
Fixed by #1385
