### ISSUE TITLE
Excise remaining "Layer" references from Prezi3 draft

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1337]
The [Layer](http://iiif.io/api/presentation/2.1/#layer) section of prezi 2 has been replaced with [Annotation Collection](http://prezi3.iiif.io/api/presentation/3.0/#annotationcollection) but there are a number of remaining references to "layer" including:

  * Example in http://prezi3.iiif.io/api/presentation/3.0/#range
  * Several mentions in http://prezi3.iiif.io/api/presentation/3.0/#paging
  * Tables in http://prezi3.iiif.io/api/presentation/3.0/#a-summary-of-metadata-requirements

I think it would probably be sensible to do a quick terminology replacement to avoid confusion in the draft, work out remaining details later

**Comment by zimeon** [comment]
I'll add to this issue the remove of [AnnotationList](http://iiif.io/api/presentation/2.1/#annotation-list) that has been replaced by [AnnotationPage](http://prezi3.iiif.io/api/presentation/3.0/#annotation-pages). In the examples, replace `/list/` with `/annopage/` in URIs.

**Comment by azaroth42** [comment]
Closed by #1339
