### ISSUE TITLE
Consider `together`-like behavior for sequences within a manifest

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1342]
The currently ratified `together` behavior allows us to model, say, the packaging, libretto and disc images of a recording of _The Magic Flute_ as one manifest, and the audio content as another. These two manifests are `items` in a single Collection resource that represents the catalogued object. The `together` behavior instructs a client that the two manifests can be presented simultaneously; the user can interact with each independently (e.g., read the sleeve notes while listening to the music). Each of the two parts is a valid, complete manifest; you could look at the libretto in Mirador and listen to the audio in the UV if you want.

I'm not proposing that this is changed. I'm suggesting a simpler additional modelling approach, that allows the publisher to produce just one manifest (with just one set of metadata) for the object while still retaining the presentation semantics required. 

This would suit simpler and common scenarios, where the image-based material (e.g., packaging) is a few canvases and the audio material is a few canvases (e.g., album sides - maybe with complex ranges). Here, the single manifest has two sequences, that should be presented together. One sequence for the images, one for the audio.

The currently defined `together` can't be reused for this purpose. The `items` property of Manifest takes only the list of sequences (nowhere to put `together`), and we don't define `together` as a property of the things that should be shown together; it's a property of their parent.

The two sequences are both alternative representations of the same object, which doesn't deviate so far from current Sequence presentation semantics. 

cc @irv

**Comment by tomcrane** [comment]
@azaroth42 suggests this is an abuse of the (minimal) semantics we currently have for sequence.

Could it be done with ranges instead? This has issues too...

General consensus on call is negative on this proposal.

**Comment by azaroth42** [comment]
Propose `wontfix`.

**Comment by tomcrane** [comment]
A possible, though still problematic approach:

Two ranges, one for the audio, one for the images; one sequence?

`together` on top level range, sub-ranges to be presented together.

Wouldn't want both approaches, need one way or the other (collection+together or range+together).

**Comment by workergnome** [comment]
I'm still negative on this--it seems like a large amount of work for viewer implementers to handle one of many, many possible presentation styles of content.  I don't disagree that there's a real use case for this presentation, but I'm curious if it's of sufficient importance to be implemented within the spec.

**Comment by azaroth42** [comment]
Agreement on editors call and preceding AV call is close wontfix.
