### ISSUE TITLE
Rewrite Introduction and Core Classes sections of Prezi3

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1348]
Splitting from #1258, which motivates [ha!] the issue but is a specific normative change.

This issue is to rewrite the first two sections of the Presentation API to take into account the following current deficiencies:

- [ ] Be neutral regarding the types of content presented, rather than being heavily image-focused (as was appropriate for previous versions).
- [ ] Make Annotations a core resource type

(Others?)

**Comment by tomcrane** [comment]
This comment and the one that follows it: https://github.com/IIIF/api/issues/1258#issuecomment-350490464. For the two "deficiencies" listed, we can easily check that they have been dealt with. The harder test is:

[ ] Does the neophyte reader think "wow, I get this!" and feel eager to continue reading? Do they get what the Presentation API is for? 

What's our strategy for testing that?

The W3C Anno spec is an example of a spec that does this well.

**Comment by zimeon** [comment]
Closed by #1389
