### ISSUE TITLE
items or orderedItems?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1350]
The discovery TSG has decided to use ActivityStreams for publishing a stream of activities. It is also used in the Presentation API for the paging model, and the Web Annotation Model for Annotation collections.

In the core AS context, the 'items' predicate has two mappings -- one is `items` as an unordered set, the other is `orderedItems` as an ordered list.  In Prezi2 and current Prezi3, as well as the [AnnotationPage](https://www.w3.org/TR/annotation-model/#annotation-page) that we import, we use only `items` ... but as the ordered version, as we never need the unordered case.

If the Presentation API context comes before the ActivityStreams context, then the unordered form will overwrite the ordered form.   If the contexts are reversed, then the Presentation API `summary` (IIIF/discovery#6  and #1326) will overwrite the AS use of `summary`. 

Context collision catch 22s all round.

**Comment by workergnome** [comment]
Are we assuming that a client that understands ActivityStreams would ever interact with any of the IIIF components that use AS LOD URIs?  We certainly are with Discovery, but I'm unsure if we are for paging or annotation collections.  

If so, are we explicitly assuming that a client will reframe the document to use it thusly, or should we maintain JSON-level compatibility with the standards that we're using?

**Comment by azaroth42** [comment]
Eds call - Discovery is ActivityStreams primary, and hence should use orderedItems. 

Close, `wontfix`
