### ISSUE TITLE
format of attribute "label" for other types within IIIF resource

### ISSUE THREAD

**Issue by nicolasfranck** [IIIF/api#1359]
http://prezi3.iiif.io/api/presentation/3.0/#label

describes the format of the attribute "label" very clearly,
but later on

http://prezi3.iiif.io/api/presentation/3.0/#related
http://prezi3.iiif.io/api/presentation/3.0/#rendering

it can also be a simple string. Is this intended? Or just not documented?

**Comment by tomcrane** [comment]
Good spot, they should be like

``` "label": {"en": ["Related Web Page"]} ```

not

``` "label": "Related Web Page" ```

Cheers!

https://github.com/IIIF/api/pull/1360

**Comment by azaroth42** [comment]
Thanks for reporting @nicolasfranck, and thanks for fixing @tomcrane! Merged, so closing.
