### ISSUE TITLE
Consistency of normative statements for image and non-image resources

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1361]
The _SHOULDs_ and _MAYs_ on `height`, `width` and `duration` for Canvas (http://prezi3.iiif.io/api/presentation/3.0/#height) favour spatial coordinates over temporal (_SHOULD_ have a `width` but _MAY_ have a `duration`).

The normative language here could get very complex... _MUST_ have a height if it doesn't have a duration; _MAY_ have a duration if it has width and height; _MUST_ have duration if no width/height... and so on.

Also. as a sometime front end developer I suggest that dimensions of all content resources are _SHOULDs_ rather than _MAYs_, subject to the same combination clarifications.

**Comment by tomcrane** [comment]
Agreement that content resources are _SHOULD_.

**Comment by tomcrane** [comment]
I was going to have a go at this... and wondered whether introducing a new properties section would make it clearer:

### 3.3 Dimension Properties

...where `height`, `width` and `duration` are defined separate from the other current technical properties, and are introduced with a short piece of text that covers the normative requirements of these properties in combination.

Worth seeing what that looks like as a PR?

**Comment by azaroth42** [comment]
To the SHOULD vs MAY point ... I agree. It's completely dependent on what is being modeled / presented by the Canvas as to which dimensions it has.  I think they should thus all be MAY.

To the complexity ... when you're in one definition there's only the other two to refer to.
e.g. http://prezi3.iiif.io/api/presentation/3.0/#height 

> A Canvas MAY have exactly one `height`, and MUST NOT have more than one. If it has a `height`, it MUST also have a `width`.

If everything is MAY, then there's no need to refer to `duration` as it's still just MAY... so in practice, the only cross-property requirement is that height and width are a pair.

**Comment by azaroth42** [comment]
I think the only change needed is in section 3, to make all of them MAY.

Section 5.3 on Canvas already has:
> A Canvas _MUST_ have a rectangular aspect ratio (described with the `height` and `width` properties) and/or a `duration` to provide an extent in time. 

Which is the requirement that canvases must have some set of dimensions, from the three possible options of:

* d
* w,h
* w,h,d
