### ISSUE TITLE
Clarify use of particular Image API request for Image resource

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1362]
Prezi 2 has

>  If a IIIF Image service is available for the image, then the URL _MAY_ be the complete URL to a particular size of the image content...

http://iiif.io/api/presentation/2.1/#image-resources

In Prezi 3 that _MAY_ is a _MUST_ 

> If a IIIF Image service is available for an image, then the URI _MUST_ be the complete URI to a particular size of the image content...

http://prezi3.iiif.io/api/presentation/3.0/#annotations-1

I think this should remain a _MAY_. 

The change in the next sentence is correct though:

> (P2)  It _SHOULD_ have an `@type` of “dctypes:Image”.

> (P3)  It _MUST_ have a `type` of "Image".

Although the language should be unambiguous that all of the rest of this paragraph is part of the "If... **for an Image**..." and not for other types of content resources.

**Comment by azaroth42** [comment]
I recall the context now ... it was that people were putting the URI of the image API in to the URI of the image, and not a representation URI.  So a non Image API aware client would fail, as the base endpoint URI redirects to info.json, not full/max/0/default.jpg

Thus the wording needs to convey:  You can have any actual image here, but if you have the Image API and you want to reference it, then this URI is not the Image API endpoint, that's in service. This is any particular image derivative made available by the endpoint.

**Comment by azaroth42** [comment]
Closed by #1405
