### ISSUE TITLE
Consider definition of quality parameter

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1363]
from https://groups.google.com/forum/#!topic/iiif-discuss/KwI-x6FkdO8

On behalf of Alex Dolski:

I'd like to propose a change to the Image API spec:

"color: The image is returned in full color."

Would become:

"color: The image is returned with all of its color information."

This would make it clearer that subsets of `color` (which bitonal and grayscale could be considered to be even though quality isn't meant to be a gradient) can be returned when they are the best that's available.

Otherwise, it's easy to misinterpret "full color" to mean "true color" a.k.a. 8-bits-per-sample RGB... and then conclude that because a source image is grayscale, or 8-bit indexed color, the `color` quality can't be offered, because "full color" isn't available.

**Comment by adolski** [comment]
Thanks for creating this, @tomcrane.

**Comment by azaroth42** [comment]
Closed by #1520
