### ISSUE TITLE
Compliance link header usage is unclear

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1365]
In http://iiif.io/api/image/2.1/#compliance-levels it states that 

> The compliance level URI _MAY_ also be given in the HTTP Link header (RFC5988) with the parameter rel="profile", and thus a complete header might look like:

But is unclear as to which responses this link header would be returned on.

The link header is most valuable on the image bitstream responses, as the compliance level is embedded within the info.json already. It would not be wrong, however, to assert against the info.json as well.  The rationale for the inclusion of the link header at all is to keep the image response a little more self-contained.

Proposal:

Replace the text with:

> The compliance level URI _MAY_ also be given in the HTTP Link header (RFC5988) with the parameter rel="profile", on both Image and Image Information responses. A complete header might look like: [...] 

Thanks to @jbaiter for bringing this up!

**Comment by zimeon** [comment]
(Updated initial comment to fix quote of current text)

I agree with this proposal, much clearer

**Comment by azaroth42** [comment]
Closed by #1519
