### ISSUE TITLE
Define structure and process for cookbook and recipes

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1367]
In order to get to parity with Presentation 2.1, we need the cookbook to exist for all of the annotation examples in section 6.

Some initial questions that need to be answered:

* Are there cookbooks for other specs, such as Auth?  If so, what would a search or image recipe look like?
* Within the prezi cookbook, what are the sections?
* What are the requirements for a good enough recipe? What are the desirable features of a recipe?
* What is the process for getting recipes accepted into the cookbook?
* Once the cookbook has a number of recipes, it will be hard to find the ones you're interested in. What do we need to do up front to allow for a recipe search in the future?

**Comment by azaroth42** [comment]
From discussion of @mikeapp @zimeon @azaroth42 as to structure of an entry:

* Name
* Use Case (why this pattern is important, including introduction, rationale and real world scenarios where it is applicable)
* Implementation Notes (how to implement the pattern, with links to the relevant sections of the specifications)
* Restrictions (when the pattern can or cannot be used)
* Example (Actual cut/paste-able JSON that works with fixture resources)
* Similar Recipes (links to other related recipes)

Considered and rejected:

* Credit line -- Likely to have many contributors, as we only want one recipe per use case. Also likely to have many recipes from the same people (e.g. editors) which would /disincentivize/ other submissions rather than encourage. While not specifications, the cookbook is a resource that we build as a community, not individual entries we build individually.
* Estimation of complexity -- too hard to get right, and dangerous / discouraging.
* Specification version -- We only have 3.0 today, and all recipes from 3.0 will work until 4.0, so we can solve this later when there's a 3.1

**Comment by jronallo** [comment]
Consider whether we'd add compatibility with clients/viewers. May be hard to maintain.

**Comment by glenrobson** [comment]
but very useful :-)

**Comment by randystern** [comment]
Tags might be useful - eg Mirador, UV, Presentation server

**Comment by azaroth42** [comment]
Added linkable, persistent identifier in comment above to address the compatibility with viewers issue. Then viewer documentation or third party systems like caniuse can refer directly to the recipe with confidence.

**Comment by glenrobson** [comment]
Discussion on call relating to images/video used in cookbooks. Currently the A/V assets are in a s3 bucket which isn't linked to the iii.io domain but could be. 

Fixture images are in the reference implementation:

https://github.com/IIIF/docker-image-api-reference/tree/master/images

We would need to consider how many images we need for fixture references. If its a small number the above method seems OK. If we want lots then we would probably need to look at s3 and maybe moving to Cantaloupe or another server that supports s3.

**Comment by azaroth42** [comment]
Untagging presentation, as it's for all IIIF specs :)

**Comment by azaroth42** [comment]
Documented in cookbook-recipes README
