### ISSUE TITLE
max should not exceed native resolution

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1370]
The current documentation says that the size parameter of `max` returns the largest size available, as indicated by `maxHeight, maxWidth, maxArea`.  If the server supports `sizeAboveFull`, and uses these properties (correctly) to give the absolute maximum size available, being greater than the native resolution, then the server must return the expanded image.

Either there should be a way to keep `full` as a shortcut to the full height and width, or `max` should be limited by the full height and width.

Related to #693. 

(Thanks to @jbaiter)

**Comment by robcast** [comment]
I would prefer for `max` to stay below (or equal to) full size. I don't think it makes any sense otherwise. 

If my server supports `sizeAboveFull` and doesn't have `maxHeight` or `maxWidth` then `max` should not request an infinitely big image :-D

**Comment by tomcrane** [comment]
If a server supports `sizeAboveFull`, should `maxWidth` (at least) be mandatory? All servers will have limits, whether imposed explicitly by config further up the line (e.g., IIPImage's `MAX_CVT`) or practically (server may attempt it but will melt in the process).

Removing `sizeAboveFull` (#693) solves this too of course.

**Comment by azaroth42** [comment]
Assuming `sizeAboveFull` is maintained, we would then need a distinction between full size natural resolution (call it ... "full"), and maximum possible size.  This would call into question #678 which was otherwise approved.  

(Tagging it as `discuss` given this)

**Comment by robcast** [comment]
I still don't see why `max` can't just be "`full` or less". I think the semantics is what everybody implementing a server or a client would expect. Am I to sanely minded?

I don't see a use case for wanting a shortcut for an image that is maxWidth x maxHeight. If I wanted one I could just request /full/maxwidth,maxHeight/0/default.jpg

I think the current "This is the same as full if none of these properties are provided." proposes the same semantics but of course we have to change the description if `full` is removed.

**Comment by robcast** [comment]
I don't think the API spec should mandate anti-DDOS measures like setting `maxWidth` when `sizeAboveFull` is supported. This is not an API concern. It could go into an implementation note.

**Comment by tomcrane** [comment]
> I don't see a use case for wanting a shortcut for an image that is maxWidth x maxHeight. If I wanted one I could just request /full/maxwidth,maxHeight/0/default.jpg

I think this is quite a common use case - I can ask for `.../full/max/0/default.jpg` from *any* image service, without having to request and process an info.json to deduce what the appropriate w,h params need to be.

**Comment by robcast** [comment]
> > I don't see a use case for wanting a shortcut for an image that is maxWidth x maxHeight. If I wanted one I could just request /full/maxwidth,maxHeight/0/default.jpg

> I think this is quite a common use case - I can ask for .../full/max/0/default.jpg from any image service, without having to request and process an info.json to deduce what the appropriate w,h params need to be.

Of course i would use /full/max/0/default.jpg but I would assume it to be the original size of the image (what used to be `full`) or a smaller size if it is not allowed.

My point is that I don't think `max` should mean "the biggest image technically possible" but "the biggest image up to the original size".

**Comment by jpstroop** [comment]
I think we can close?

**Comment by jpstroop** [comment]
Fixed by 05fff0ea352ef54f2a94d578984e866bece37cf2 or thereabouts. `sizeAboveFull` will not be supported in 3.x
