### ISSUE TITLE
Clarify !w,h can return both dimensions less than request

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1372]
If the client asks for !1000000,1000000 and the image can only be delivered at 500,500, that is a valid response.  This should be noted in the API documentation for clarity.

**Comment by jpstroop** [comment]
Is there a use case for this, or should we say that `x` or `y` MUST be <= the maximum size available of the long dimension of the image?

**Comment by azaroth42** [comment]
This is CogApp's request for (e.g.) !800,800 so that they can then fill the space as much as possible. It's already fine, given the spec's definition:

> The image is scaled for the best fit such that the resulting width and height are less than or equal to the requested width and height. 

In this case both height and width are less than the requested. I think the definition could be modified to define "best fit" a little better.

**Comment by jpstroop** [comment]
Yeah...something is determining `800` in your e.g. I'd think they can either use that or `max`. They're going to have to deal with the possibility of getting a smaller image anyway.

**Comment by jpstroop** [comment]
Oh...but the the max long dim. is > 800px. I get it.

Still don't like it.

**Comment by azaroth42** [comment]
Right. 800,800 could distort, and max could be 150k pixels. The only way is !w,h ... and the best fit without scaling up is max.

**Comment by workergnome** [comment]
Is this the same as the "quality" thing, where asking for an invalid quality shouldn't fallback?  Enough info is around to figure this out in the info.json--you just can't cheat and not check.

**Comment by jpstroop** [comment]
@workergnome, we've sort of established precedent for cheating with `square`, i.e. you _could_ get the `info.json` and figure out that request for yourself, but the shorthand is useful when you want to load a page full of square thumbnails.

So again, I wonder about the use case.

**Comment by zimeon** [comment]
I think the reason to do this is to clarify that there is a sensible and well defined non-error response to a request for large `!w,h` -- better/easier than defining an error IMO

**Comment by tomcrane** [comment]
General +1 on call

**Comment by azaroth42** [comment]
Closed by #1521
