### ISSUE TITLE
info.json does not need to list features/values that are implied by the level

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1373]
Follow on from #1275 

In, e.g.:

```
  "qualities": ["default", "color", "gray", "bitonal"],
  "formats": ["jpg", "png", "tiff", "webp"],
  "features": ["sizeAboveFull", "arbitraryRotation"]
```

`default` quality and `jpg` format _never_ need to be listed because they are required at level 0. Level 2 doesn't need to list `png` format, etc. 

Careful w/ `qualities` though, as those may vary by image (beyond `default`) at any level of compliance

**Comment by zimeon** [comment]
I agree that we should not need to specify anything already in profile, but I also think it should not be an error to repeat something in the profile.

**Comment by azaroth42** [comment]
:+1: It would also not be an error to have the same string listed twice in a given property... just meaningless repetition.

eg:  
```
  "extraFormats": ["tif", "tif", "tif"]
```

**Comment by azaroth42** [comment]
Agree close, fixed.

**Comment by tomcrane** [comment]
:+1:
