### ISSUE TITLE
multi-dimension fragments are not canonicalized

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1391]
The order of the spatial and temporal parts of a media fragment are not canonically ordered.  For processing the meaning (pick this spatial region and this temporal region) ordering is unimportant as the dimensions are orthogonal.  However, the two orders will create two different URIs.

This will be most common with space/time regions of Canvases.  These are referenced from multiple places -- Ranges, the body or target of Annotations and `start`.  They might have information asserted about them as part of those references (is this true?) at which point there would be a disconnect between the various forms of the URI.

Part of the issue cluster: #1386, #1320, #1338, #953.

/ht @barmintor

**Comment by zimeon** [comment]
We have in the current draft of the specification

> ... Spatial parts of Canvases, when referenced from outside an Annotation, must be rectangular and are described by appending an xywh= fragment to the end of the Canvas’s URI. Similarly, temporal parts of Canvases must be described by appending a t= fragment to the end of the Canvas’s URI. Spatial and temporal fragments may be combined, using an & character between them, and **the temporal dimension should come first**. ... <http://prezi3.iiif.io/api/presentation/3.0/#canvas>

so this issue has already been addressed.
