### ISSUE TITLE
Consistency: be clear about what "embedded" means

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1396]
@tomcrane:
>How do we make it clear that if a resource is "embedded inline", we mean that the full JSON of the resource has been included, not some reduced version? Variations on "embedded" appear quite a few times in the spec, do you think we should define this formally? In Terminology?

Define "embedded" and "referenced" in Terminology?

**Comment by azaroth42** [comment]
Eds call: +1 on putting it in terminology. First time we talk about it in the spec, give a back ref to terminology.

**Comment by zimeon** [comment]
Closed with #1404
