### ISSUE TITLE
Consistency: cardinality of MAY ... exactly one ... is weird

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1397]
From @zimeon:
> as I read it, it seems at odds with MAY (if I were to use exactly I'd have some like "MUST have exactly zero or one")

There are two ways to express a cardinality of 0-1:

* MAY have [exactly] 1
* MUST have 0 or 1

Both result in the same range, but to me the use of MAY reinforces that the property is optional. 

Preferences?

**Comment by zimeon** [comment]
I'm OK with "MAY have one" (no *exactly*)

**Comment by tomcrane** [comment]
👍

**Comment by azaroth42** [comment]
I'm fine with that.

**Comment by azaroth42** [comment]
Closed by #1403
