### ISSUE TITLE
Rename 'none' behavior to 'hidden'

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1398]
To fit in more consistently with 'no-nav' and 'non-paged'. A behavior of "none" makes less sense than a viewingHint.

**Comment by tomcrane** [comment]
Is there some consistency work to be done on these names, as values of a property called `behavior`?

e.g., 

`behavior: not-paged`
`behavior: not-displayed`
`behavior: not-for-nav`

`behavior: non-paged`
`behavior: not-displayed`
`behavior: not-for-nav`

etc, variants of.

**Comment by azaroth42** [comment]
Agreed. Having patterns and clearer semantics will let us stay more consistent moving forwards as well.

**Comment by azaroth42** [comment]
(template)

|Current | Adjective | Directive|
|--------|-----------|---------|
| individuals |  |  |
| paged |  | |
| continuous |||
| multi-part |||
| non-paged |||
| facing-pages |||
| none |||
| no-nav |||
| thumbnail-nav |||
| auto-advance |||
| together |||
| repeat |||

**Comment by azaroth42** [comment]
Ed's discussion:  none --> hidden

**Comment by zimeon** [comment]
While there isn't a consistent voice for the other terms as properties or directives, the churn we'd introduce by changing to get that consistency does not seem justified

**Comment by azaroth42** [comment]
Closed by #1402
