### ISSUE TITLE
Allow no-nav behavior on Sequence

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1407]
We could allow the no-nav behavior to also be added to Sequences. This would mean that the Sequence should not be used for navigation, only for managing Canvases.  This would be a way to implement #1238, by having only hierarchical ranges used rather than a master ordering, without significant changes to the model (such as in #1072).

A Sequence that was flagged as `no-nav` would not be used to generate a thumbnail strip, or next/prev UI affordances. Instead the ordering would all be local, within Ranges.

**Comment by jpstroop** [comment]
I'd prefer the inverse: a range with `"behavior" : "sequence"` and rename `structures` to `items`.

**Comment by azaroth42** [comment]
Closing in favor of #1417.  Can reopen if it is rejected.
