### ISSUE TITLE
Rename attribution to requiredStatement in Image API

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1415]
See #1287 (closed by #1413 as complete for Presentation API 3), we need to replicate this for Image API 3.

**Comment by zimeon** [comment]
* Also corresponding change of `license` to `rights` in Image API to match Presentation API
  * `logo` remains same in both

**Comment by azaroth42** [comment]
(@zimeon agreed to make this change on 2018-03-21 eds call, assigning)

**Comment by zimeon** [comment]
Should mirror #1504 PR for prezi3

**Comment by azaroth42** [comment]
Closed by #1518
