### ISSUE TITLE
Tidy language in Image API 3.0

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1425]
We have a number of inconsistent uses of language in the Image API spec that should be tidied, things to look at include:

  * image / region / extracted region
  * image / image content
  * determined / defined / requested/ specificed

**Comment by azaroth42** [comment]
"this specification defines ..."

**Comment by zimeon** [comment]
Suggested terms/usage:
  *  "underlying image content" -- way to refer to the source image or equivalent
  * "image service" -- the service with base URL that we have previously sometimes called "the image"
  * "image content" -- way to refer to image as it moves along pipeline
  * "image" -- response to image request
  * "specifications define" -- as @azaroth42 suggested above, avoid "specifications specify"
  * "extracted region" ... of the ... "underlying image content" -- what you get after region step

**Comment by zimeon** [comment]
I think we need to define the "complete image' or "full image" -- the possibly imaginary image that would be generated with width,height given in info.json. We've tried to avoid that and it really doesn't work as we have then several implied definitions. I think "underlying image content" is the best term we have for the source image or whatever other information backs the service. I think "full image" would be the best term -- it doesn't sound overly technical and ties nicely with `/full/` region.

I propose that we add a low-key definition to section 4:

> This specification makes no assumptions about the form of the underlying image content. The term **full image** is used to refer to the entire area of the underlying image content, with the pixel dimensions given in the image information response, and which is imagined as the starting point for image requests.

**Comment by zimeon** [comment]
Concepts: underlying image content (no assumptions: may be single image, set of images, code to generate, extraction from video, etc.) -> full image (start for transforms, with width, height) -> extracted region (after region step) -> image content (intemediate stage in transforms, not likely serialized) -> image (thing you get out in specific format at end)

**Comment by tomcrane** [comment]
Fixed by #1462
