### ISSUE TITLE
Verify canonical use of `w,h` compatible with `sizes` and remove consistency warning

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1434]
Image API 2.1 has:

> Warning There is an inconsistency between the specification of the sizes list and the canonical URI syntax. Clients should use the Canonical URI Syntax when making image requests based on entries in sizes. For maximum compatibility, servers should support both the w, and w,h forms of the size parameter for values in sizes that maintain the aspect ratio. This inconsistency will be addressed in the next major version of this specification.

This should be resolved and removed in 3.0. See #544 & #607

**Comment by tomcrane** [comment]
Closed by #1437
