### ISSUE TITLE
Acknowledgements: s/members of the IIIF/members of the IIIF community/

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1441]
In both image and presentation 2.1 we have the acknowledgement:

> Many thanks to the members of the IIIF for their continuous engagement, innovative ideas and feedback.

which seems a bit off because IIIF is a framework and we don't mean just IIIF-C members. I propose instead:

> Many thanks to the members of the IIIF community for their continuous engagement, innovative ideas and feedback.

**Comment by azaroth42** [comment]
Closed by #1442
