### ISSUE TITLE
Dimension matching should apply to painting motivation only, not transcribing

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1443]
From AV working group meeting - 

spec says:

> "...it is an error to associate a Video resource (which has height, width and duration) with a Canvas that does not have all three dimensions"

(section 5.3)

This does not allow a link from Glenn Gould playing the Goldberg Variations to an annotated score.

Rule needs to be relaxed for `painting` only. 

`items` on a Canvas can only have `painting` annotations; all other annotations, including `transcribing` annotations, must go in the `annotations` property.

**Comment by azaroth42** [comment]
Closed by #1465
