### ISSUE TITLE
Type scoping doesn't work for extensions

### ISSUE THREAD

**Issue by workergnome** [IIIF/api#1459]
in [4.6](http://prezi3.iiif.io/api/presentation/3.0/#linked-data-context-and-extensions), we say "...must be retrofitted to use a scoped context based either on a property or type, as per the examples in the definition of the service property. Care should be taken to use the mappings defined by those contexts, especially with regard to id versus @id, and type versus @type, to ensure that clients receive the keys that they are expecting to process."

As per @azaroth42 and my explorations at the BL, `Type` scoping doesn't work in this pattern. The current implementations of the JSON-LD spec appear to only allow defining one scoped context per Type, which makes Type nesting prone to unintentional conflicts.

**Comment by tomcrane** [comment]
Fixed by #1461
