### ISSUE TITLE
Consider order of property descriptions

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1464]
I think we're implicitly ordered by perceived importance -- everything should have a label, so we put label first.

Is this true? Does it align with the Clients MUST/SHOULD/MAY statements?

**Comment by azaroth42** [comment]
Or should we reorder somehow else within the sections?  I'm wary of simply alpha-sorting as the understandability of the spec goes down.

**Comment by azaroth42** [comment]
Current exceptions:

* requiredStatement is after metadata, even though it's all MAY and following are some SHOULD.
* id comes before type, even though Annotation Pages are only SHOULD for id, and type is MUST for all.
* height, width, duration are odd in that they're MAY but some combinations are MUST ... but are probably in the right place

I think the only one that deserves discussion is the first one.  Does it move down to between thumbnail and posterCanvas?

**Comment by jronallo** [comment]
Another way to consider the ordering here is with regards to how we might teach creating and building up a manifest. The technical properties in 3.2 seem in the right order. Maybe consider an ordering for descriptive properties of label, summary, requiredStatement first as they're the easiest to understand and add the least to an initial manifest. Then metadata which requires diving deeper into some of the conceptual decisions of IIIF with regards to metadata. Then follow with the others which may not be added in an initial pass at creating a manifest, but can be added later. Just a thought.

**Comment by azaroth42** [comment]
:+1: to @jronallo's order.  That builds up nicely in terms of complexity.

label, summary, requiredStatement, metadata, thumbnail, ... 

label is essential and obvious
summary has the same pattern (language map) but less essential, slightly less obvious
requiredStatement adds structure of label/value
metadata adds a list of the above structure

**Comment by azaroth42** [comment]
Move navdate above postercanvas

**Comment by azaroth42** [comment]
Closed by #1504
