### ISSUE TITLE
Misc. style stuff

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1466]
* [x] Serial commas
 * [x] Objects have properties
 * [x] JSON Arrays (not Lists) have items (not members), and define as precisely as possible what those items are (string, object, int, float)
 * [x] Kill double spaces with:
    ```bash
    #!/bin/bash
    for md_file in $(find . -name "*.md"); do
      # Test changes:
      # ggrep -E --color -e "[a-z]\.\s{2,3}[A-Z]" $md_file
      gsed -r -i -e 's/([A-z])\.\s{2,3}([A-Z])/\1. \2/g' $md_file
    done
    ```
 * What else?

* [x] Use of backticks in prose

**Comment by azaroth42** [comment]
:-1: on lists and members.

JSON has objects and arrays:  https://tools.ietf.org/html/rfc8259#section-5 
List is also overloaded in RDF, as JSON arrays are both sets and lists.

**Comment by jpstroop** [comment]
> 👎 on lists and members.

Arrays / items is fIne w/ me, let's just be consistent. Can you update the list at the top of the issue?

**Comment by azaroth42** [comment]
✈️ PR fixed objects, arrays.   #1473 fixed double spaces.
Serial commas seems like a final read-through?  

An editorial style guide document to capture these would be valuable so we can close the issue, otherwise it seems like it will be permanently open.

**Comment by azaroth42** [comment]
@jpstroop Are you willing to write up a style guide, or shall we close?

**Comment by azaroth42** [comment]
Propose close, fixed?

**Comment by azaroth42** [comment]
#1533 for backticks.
