### ISSUE TITLE
Consider advice/formatting of floating points in Image API spec

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1468]
We have:

> Size and region parameters in percentages and the rotation parameter _MUST_ be positive floating point numbers or integers. These should have at most 10 decimal digits and consist only of decimal digits and "." with a leading zero if less than 1.0. Intermediate calculations may use floating point numbers and the rounding method is implementation specific.

do we want or need to specify like this? or is there something else to refer to?

**Comment by zimeon** [comment]
I think having that prescription is ugly and fairly unnecessary, it would be nice to refer to some other spec for formatting guideline... but I can't find a good one.

There is [xsd:precisionDecimal](https://www.w3.org/TR/xsd-precisionDecimal) from which we could define floating point as `noDecimalPtNumeral | decimalPtNumeral` (not including scientific notation or special codes like `+Inf` and `NaN`). However, this format allows arbitrary precision.

**Comment by azaroth42** [comment]
I think it could be reframed as a URI canonicalization issue, rather than a request syntax requirement.

**Comment by zimeon** [comment]
@IIIF/editors agree to move into canonicalization section, forward reference,  avoid repetition with rotation parameter description, omit the 10 character limit

**Comment by azaroth42** [comment]
Closed by #1513
