### ISSUE TITLE
Re-re-rename `includes` to `transcription` or similar?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1480]
Now that we have a `transcribing` motivation, and the intent of `contentLayer` (now `includes`) is the textual (or similar) content of the range, we could be more precise and more helpful with the use of the relationship by using a name like `transcription` that reflects the annotation motivations.

**Comment by tomcrane** [comment]
From the AV work, we have many stretching use cases of the `transcribing` motivation:

https://github.com/IIIF/api/issues/1378, https://github.com/IIIF/api/issues/1443 and various things like multiple camera angles, musical scores, dance notation and other multi-representation but not `painting` use cases.

These could all be handled by `transcription` as their Presentation requirements are all similar; content, but not content that must be painted.

If we keep `transcribing` as the motivation name then I agree that `transcription` is a good term for the linking property. My concern is that `transcribing` may start to look very odd for some AV multimedia use cases. But that's a separate issue. No odder than painting sound into a t-only canvas.

**Comment by azaroth42** [comment]
Agreed.  Happy to replace both terms, but I think they should be tied together.

**Comment by mikeapp** [comment]
+1 on consistency

**Comment by azaroth42** [comment]
Eds' call:  
* Agreed that the intent is the set of transcribing annotations for the area defined by the range.
* In the absence of a change to "transcribing", then "transcription" is a good name.

**Comment by jpstroop** [comment]
Closed by #1499
