### ISSUE TITLE
Rename `Collection` to avoid curated set of CHOs implication

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1481]
"Collection" is very overloaded in the cultural heritage domain, which is also our primary domain.
We have an opportunity at this point to rename Collection to something less charged.

**Comment by tomcrane** [comment]
I agree that it is massively overloaded, but it is so overloaded that its overloadedness actually helps strip it of meaning, and it is well established by now in the IIIF community. The problem would be to come up with another easily comprehended but less overloaded way of describing:

- The volumes of a multi volume work
- My bookmarks
- Manuscripts A-D
- All works tagged "cats"
- Books by Jane Austen
- The top level node of Digital Bodleian
- Manifests matching a search for ?q=overloaded

...where these are lists and can be hierarchical.

Not `Set`. For many reasons.

**Comment by azaroth42** [comment]
:+1: Happy with close wontfix, but wanted to raise it for consideration.

**Comment by zimeon** [comment]
I'm also for `close wontfix` because I don't think we'll find a better word

**Comment by mikeapp** [comment]
Also 👍 to `close wontfix`

**Comment by jpstroop** [comment]
👍

**Comment by zimeon** [comment]
Agreement on `close wontfix`... closing
