### ISSUE TITLE
Rename `within` to `partOf`

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1482]
We should rename `within` to `partOf` to follow ActivityStreams and the Web Annotation Model.
Otherwise we would have AnnotationPages being `partOf` AnnotationCollections, but Canvases being `within` Manifests.

See: 
  * https://www.w3.org/TR/annotation-model/#annotation-page
  * https://www.w3.org/TR/activitystreams-vocabulary/#dfn-partof

**Comment by tomcrane** [comment]
:+1:

**Comment by zimeon** [comment]
Agreed

**Comment by azaroth42** [comment]
Closed by #1495
