### ISSUE TITLE
Clarify possible targets of transcribing and painting annotations

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1483]
Can they annotate resources other than Canvases?

**Comment by tomcrane** [comment]
`painting` - no, as Canvases are the only things with dimensions to paint into.

`transcribing` - maybe; but there is also `rendering` for attaching a full text transcription of the object represented by the manifest.

Possible use case - I have a single text file that I know is a transcription of the 10 images of the manuscript, but I don't have any information about the divisions of the text across pages, so I can't chunk it up into transcribing annos on each canvas. 

However, what would a client do with such an annotation, that it couldn't do with a `rendering` on the Manifest?

My first reaction is that content annos (transcribing and painting) should target the content carrier, the Canvas only, and you should use rendering for representations that can't be mapped to canvases.

**Comment by azaroth42** [comment]
> content annos (transcribing and painting) should target the content carrier, the Canvas only

:+1:  Agreed. These are very specific motivations useful only within the IIIF Presentation API, and not more broadly.

**Comment by azaroth42** [comment]
Closed by #1494
