### ISSUE TITLE
homepage cardinality

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1484]
Is currently 0-n, but I thought we decided on 0-1 ?  What was the use case and expected behavior for multiple home pages?

Was it that there might be the same abstract page in multiple languages or formats? And if so, we should clarify in the description.

**Comment by tomcrane** [comment]
I think we decided on 0-1 too. Differentiating by language, and maybe format (but probably not) would be the only reasonable way of dealing with multiple home page links.

FOAF says:

> FOAF allows a thing to have multiple homepages, but constrains homepage so that there can be only one thing that has any particular homepage.

...which is probably not quite what we want.

**Comment by mikeapp** [comment]
I recall (and am fine with) 0-1.

**Comment by zimeon** [comment]
Me too. We agreed 0 or 1

**Comment by azaroth42** [comment]
Closed by #1493
