### ISSUE TITLE
Name of the `transcribing` motivation

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1490]
Presentation 3 introduces an additional annotation motivation, `transcribing`

> Resources associated with a Canvas by an Annotation with the “transcribing” motivation may be presented to the user as part of the representation of the Canvas, or may be presented in a different part of the user interface.

Source: http://prezi3.iiif.io/api/presentation/3.0/#values

This is an obvious, clear and useful motivation name for familiar transcription use cases - OCRed text, human transcribed manuscript, musical notation and other representations. 

The _mechanism_  also works for many AV use cases like multiple camera angles and other forms of graphical representation that stretch the common meaning of the word "transcribing". The motivation means that this content is part of the representation (not commentary, etc), and is directly associated with regions of the canvas, and _could_ be painted but doesn't have to be, a client can be flexible.

Is the word "transcribing" misleading or too domain specific? Especially if #1480 uses the same word form ("transcriptions"). 

Is there a better term?

See https://github.com/IIIF/api/issues/1480 and https://github.com/IIIF/api/issues/1483

**Comment by zimeon** [comment]
Discussed possible use of Icelandic for "side-car": hliðarvagn, but perhaps this won't be the most obvious term for most readers

**Comment by azaroth42** [comment]
Ed's call: We think that the content of the transcribing annotation is an alternate or additional representation of the primary content displayed in the target canvas / part of canvas.  

Propose:  `supplementing`
And thus #1480 would be `supplementary` as the property name?

**Comment by tomcrane** [comment]
Captain's log: `supplemental`

Although that usage is more US. Compare the British and American English usage of supplementary here: https://www.collinsdictionary.com/dictionary/english/supplementary

**Comment by jpstroop** [comment]
Closed by #1499
