### ISSUE TITLE
Clarify Objectives of IIIF

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1491]
http://prezi3.iiif.io/api/presentation/3.0/#objectives-and-scope
http://iiif.io/api/presentation/2.1/#objectives-and-scope

Currently, and historically, the objectives of IIIF are described by the three bullet points in the links above. The P3 version expands to non-image content.

We should stress a fourth objective of the Presentation API. It's not just about _Presenting_. It's also about the provision of a shared _annotation space_ for an object. It enables more than just the seeing of the object: by publishing as IIIF, we provide targets for new content creation, by ourselves and anyone else on the web. Eventually, the notion that publishing as IIIF means publishing into a shared annotation space could become the most important point of all.

**Comment by jpstroop** [comment]
Closed by #1498
