### ISSUE TITLE
Is `language` MAY or SHOULD?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1492]
SHOULD: 
  * It's the International I.I.F. !
  * It's now very hard to have embedded strings without a language, so SHOULD on external language would be consistent

MAY:
  * If you just don't know the language of an external resource, then a warning that `language` is missing is unhelpful.

**Comment by azaroth42** [comment]
I think I prefer _SHOULD_ but not dogmatically.  I'm not in favor of "_SHOULD_ if known" or other untestable conditional.

**Comment by zimeon** [comment]
On reflection I agree that qualifying SHOULD with `if known` is a bad mix of RFC requirements and an untestable condition -- bad suggestion. I suppose I'm OK with SHOULD but wouldn't want a validator to harshly penalize a site that simply can't

**Comment by jpstroop** [comment]
_SHOULD_ is OK, I guess. Doesn't really solve anything.

**Comment by mikeapp** [comment]
SHOULD is good!

**Comment by azaroth42** [comment]
Eds call: Everyone is loosely in favor of SHOULD.

**Comment by zimeon** [comment]
@tomcrane [previously wrote](https://github.com/IIIF/api/pull/1474#discussion_r172016786) As we now have a spec where it's hard not to declare a language for a string, should this MAY be a SHOULD?

**Comment by jpstroop** [comment]
Closed by #1497
