### ISSUE TITLE
Only allow http, https, and mailto in href attr of a tag in HTML values

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1505]
e.g. whitelist the three useful ones, rather than just blacklisting javascript: per #1501

**Comment by azaroth42** [comment]
:+1: to this change. The HTML should be as simple as possible and restricting the schemes/protocols for href attributes closes many attack vectors.

**Comment by mejackreed** [comment]
👍 . It seems like additional protocol adoptions could happen outside of spec compliance.

**Comment by tomcrane** [comment]
Make it a client concern to sanitise, but the publisher can put other protocols in if they want - they just shouldn't expect a client to render them.

**Comment by azaroth42** [comment]
Consensus on the 2018-04-11 Community Call:

Express as a client requirement, and be explicit that it is not a publication requirement.  In other words, content MAY include protocols such as irc: or info: or dat: or z3950r: but typical clients are expected to strip them out.  Experimental clients, or custom built systems, can ignore this and process them as desired.  The requirement is to keep client implementations as simple as possible, both for security and consistency of behavior.

**Comment by azaroth42** [comment]
Closed by #1523
