### ISSUE TITLE
IIIF and image protection against direct download

### ISSUE THREAD

**Issue by modou33** [IIIF/api#1506]
Hello.

I am actualy implementing the presentation API of IIIF. For the Image API, i'm working with IIPImage server and everything rolls very nice.

However I'm embarrassed with the protection of originals images against the direct download. In fact, the manifest file permits to build easily an IIIF query for accessiing directly to the files repository.
For exemple, this query: http://<IIIF server>/full/full/0/default.jpg offers almost the direct access to the original jpeg version.

I'm working in heritage sector and for legal reasons controling the access on ressources is important.

thereby, first of all i want to know if there is a way for protecting securely the warehouse against direct access (ex: direct download without using a viewer like mirador) ?

Second of all, if i open my warehouse with IIIF, is it possible to block complety the access for some subdirectory ?

thanks.

**Comment by azaroth42** [comment]
Process wise, I think this isn't an open issue, but a question for iiif-discuss.  I would propose to close it as already fixed, and continue the discussion on the mailing list if the above answer is insufficient.
