### ISSUE TITLE
Should navDate be tied to the start time of the Range?

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1512]
At an LDCX session we just had a discussion of a use case where one might have many videos that all have a real-time synchronization (say lots of phone videos from a march in Washington where the difference in times is comparable to or less than the video lengths) we might want to support user-interfaces that present these on a timeline. `navDate` is designed to purposes such as this but [currently doesn't specify](http://prezi3.iiif.io/api/presentation/3.0/#navdate) where in relation to the included AV time the `navDate` applies to. Cases:

  * Canvas: `navDate` is not allowed on a Canvas
  * Range: seems like the simple solution is to specify that `navDate` refers to the start time of the first item in the Range if the item has a time dimension
  * Manifest: in simple case seems like Range but not sure what would be case for unordered per #1508 (seems then like Collection where it is hard to have specific meaning)
  * Collection: don't see specific meaning in this case

**Comment by azaroth42** [comment]
:+1: to the start of the duration of the resource.

**Comment by azaroth42** [comment]
Closed by #1522
