### ISSUE TITLE
Allow navDate on Canvas

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1532]
`navDate` is permitted on Collection, Manifest and Range: http://prezi3.iiif.io/api/presentation/3.0/#navdate

Allowing it on Canvas would allow the creation of resources like this, where each entry is a Canvas and the Manifest is the whole timeline:

https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/genetics-timeline

(currently not IIIF - predates Presentation API)

**Comment by zimeon** [comment]
Agreed to allow and added in #1536
