### ISSUE TITLE
Review policy on use of backticks in Image and Prezi 3

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1533]
[Image 2.1]() - uses backticks for verbatim parameter values (e.g. `max`), uses normal font for variable names (e.g. w and h)

[Prezi 2.1](http://iiif.io/api/presentation/2.1/)- uses backticks for property names (e.g. `behavior` property) and _some_ verbatim examples (e.g. `application/json`), uses quotes for verbatim parameter values (e.g. "image/jpeg")

**Comment by azaroth42** [comment]
Proposed rules...

URI pattern text
* normal text: normal font
* variables: italicised backticks
* values in URIs: backticks
* variable and value in URL: italicised backticks for the whole parameter
* URL templates follow the RFC6570 pattern with {}s and everything in backticks

eg:  _`pct:n`_ 

JSON feature formatting:

* Property names are backtick
* Class names are normal, Capitalized (and plural when appropriate)
* Values are backticks and rework to be `property` value `value`

**Comment by azaroth42** [comment]
Closed by #1549
