### ISSUE TITLE
Introduce highlighting on inline <code>

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1550]
...in the spec stylesheet, so that `backticked` values render like GitHub markdown.

This produces the desired effect for inline code blocks:

```
  code, kbd, pre, samp {
    font-family: 'Ubuntu Mono', monospace;
    font-size: 1em;
    background-color: #eee;
    padding: 1px 4px;
    border-radius: 3px;
  }
```

(the last three lines are the additions)
... but needs more work to avoid these styles overriding the other code sample blocks.

Also needs:

```
    .api-table {
      tr {
        font-size: 15px;
      }
      td:first-child code {
        padding:0;
        background: none;
      }
      td {
        font-family: sans-serif;
      }
    } // .api-table
```

NB GitHub uses `padding: 0.2em 0.4em;` - but the current line spacing is too tight for this to work well in the API.

**Comment by azaroth42** [comment]
Closed by #1549
