### ISSUE TITLE
Prezi Introduction needs to mention AV

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1568]
Its currently image-centric, e.g.:

>A composite object may comprise a series of pages, surfaces or other views; for example the single view of a painting, the two sides of a photograph, four cardinal views of a statue, or the many pages of an edition of a newspaper or book. The primary requirements for this specification are to provide an order for these views, the resources needed to display a representation of the view, and the descriptive information needed to allow the user to understand what is being seen.

**Comment by azaroth42** [comment]
Close, fixed :)
