### ISSUE TITLE
Refinement of introduction

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1572]
Consider breaking up section 1.2 for more impact and understanding:

1.2 first para becomes the very opening section of the spec
1.2 second paragraph is moved into section 2 to introduce the model

...and other improvements.

**Comment by tomcrane** [comment]
Related to this - the word "viewer" appears three times in the spec; the one in the intro is OK but the other two should be "client".

**Comment by tomcrane** [comment]
Can close this now?
http://preview.iiif.io/api/image-prezi-rc1/api/presentation/3.0/#introduction

**Comment by azaroth42** [comment]
+1 Closing.
