### ISSUE TITLE
Is there a better way of describing "this resource"?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1574]
When a property is defined in the spec, we use the term "this resource" to refer to the resource with the property being defined. While consistent, this often reads oddly when _the_ resource, or _a_ resource, is being discussed. 

For example:

> ### summary
> 
> A short textual summary of this resource...

What's "this"? 

Although consistency is desirable in a spec, it needs to be balanced against readability and cater for the reader who is looking something up and may not have seen (or has forgotten) the special meaning of "this resource" defined earlier.

Where the spec is talking about a property that links to another resource, we need a precise way of talking about the resource with the property and the resource the property links to. Where there is only one resource, we can use _the_ or _a_ as suits.

What terms would work?

subject resource - too RDF-y
"resource with this property" maybe.

**Comment by azaroth42** [comment]
Fixed in image-prezi-rc1 branch. Can we close?

**Comment by zimeon** [comment]
I think fix/merge to image-prezi-rc1 branch is now reason to close. Closing, done in 2557ff744883d10f958647062bb4453c6537635
