### ISSUE TITLE
Image API: more specific content type

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1587]
At http://iiif.io/api/image/3.0/#image-information-request it is said that the content type must be either 
`application/json` or `application/ld+json` but the example includes a content type parameter:

    Content-Type: application/ld+json;profile="http://iiif.io/api/image/3/context.json"

It might be made explicit that content type parameters are optional (e.g. JSON can be extended with `charset=utf-8`) and that `profile="http://iiif.io/api/image/3/context.json` is RECOMMENDED parameter for JSON-LD mime type.

**Comment by azaroth42** [comment]
:+1: The normative text should be clear that the profile is required, and that other parameters are possible.

**Comment by zimeon** [comment]
Agreed, this language should be made clearer as it is also important for client builders to understand that they might receive other parameters

**Comment by azaroth42** [comment]
Related to #1606

**Comment by azaroth42** [comment]
Closed by #1654
