### ISSUE TITLE
Image API: Enforce URIs as right identifiers

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1588]
At http://iiif.io/api/image/3.0/#rights-related-properties the `rights` property is described as "A string that identifies a license [...]". This should be "An URI that identifies a license".

**Comment by nichtich** [comment]
The discussion mainly talks about URIs only to come up with strings at the end. At least a "should be an established URI" could prevent people using identifier strings such as "CC" which can hardly be made use of.

Am 27. April 2018 17:52:14 MESZ schrieb Rob Sanderson <notifications@github.com>:
>It can also be a registered string, following this design pattern:
>http://iiif.io/api/annex/notes/design_patterns/#use-consistent-structural-conventions
>
>
>See the (long) discussion in #1479.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/IIIF/api/issues/1588#issuecomment-385013245

-- 
Jakob Voß via Android

**Comment by azaroth42** [comment]
Oh, my apologies, I see the clarification you're trying to make now.  Yes, when the text was ported across from the Presentation API v3.0, the CC/RSS URIs are URIs got weakened.

**Comment by azaroth42** [comment]
Closed by #1646
