### ISSUE TITLE
Image API: less strict logo requirement

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1589]
At http://iiif.io/api/image/3.0/#rights-related-properties the `logo` property is described as required to be shown. This requirement, however depends on the actual license. Attribution requirement is already covered by field `requiredStatement`. Either change "The logo MUST be clearly rendered" to "The logo SHOULD be clearly rendered" or rename the field into `requiredLogo` (although logos are rarely required legally).

**Comment by zimeon** [comment]
I also note that `logo` was MUST display in 2.x. I don't think loosening that makes sense.

Perhaps some of the confusion is the difference in language between `requiredStatement` and (perhaps not required) `logo` -- I really don't want to reconsider the discussion #1287 that got us to `requiredStatement` (as opposed to, say, `statement`)  as I don't think we have better naming options. The key issues seems to be distinguishing from other metadata-like properties while generalizing the notion of `attribution` that we had in 2.x.

**Comment by nichtich** [comment]
Ok I better understand. I have rarely encountered logos other than license icons at image rights metadata but that's a different kind of logo. If applications can easily guess CC license badges from rights URI that's fine but these are not required to be shown anyway.

**Comment by azaroth42** [comment]
Consensus on community call of 2018-08-01 to not change from status quo. Closing, wont fix.
