### ISSUE TITLE
Clarify CORS statement regarding Image Information Requests

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1591]
In [5.1. Image Information Request](http://iiif.io/api/image/3.0/#image-information-request) we have:

> Servers should also support CORS on image information responses.

which I think should be:

> Servers SHOULD support CORS on image information responses.

to parallel the earlier _Servers should support CORS on image responses._. The "also" doesn't make sense to me in the current context.

**Comment by zimeon** [comment]
and link to CORS to [CORS section](http://iiif.io/api/image/3.0/#71-cors)

**Comment by azaroth42** [comment]
Closed by #1655
