### ISSUE TITLE
Image API requiredStatement example should use array

### ISSUE THREAD

**Issue by mikeapp** [IIIF/api#1601]
http://iiif.io/api/image/3.0/#55-rights-related-properties has 
```
"label": { "en": "Attribution" }
"value": { "en": "Provided by Example Organization" }
```

**Comment by azaroth42** [comment]
:-1: `requiredStatement`was decided to be singular (IIRC) to avoid publishers putting in ALL their metadata as required.

**Comment by azaroth42** [comment]
Oh the *values* ... sorry, you're completely correct!

**Comment by azaroth42** [comment]
Should be `["Attribution"]` (etc)

**Comment by mikeapp** [comment]
This is already done, see merge above.
