### ISSUE TITLE
bikeshed: Is timeMode the best name?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1602]
It's a behavior for rendering the body time-based media resource. [`timeMode`](http://iiif.io/api/presentation/3.0/#timemode) is pretty unintuitive.

**Comment by tomcrane** [comment]
Are its three possible values just `behavior`s that are only permitted on Annotation?

**Comment by zimeon** [comment]
I suppose if we went that route then we'd have to change names to indicate what they are talking about, something along the lines of `trim` -> `trimDuration`, `scale` -> `fitDuration`, `loop` to stay? But, given the specific use, I wonder whether hiding these three behaviors inside an already large set of behaviors is just going to be more confusing? On balance I lean toward the status quo, though we could also consider alternate names

**Comment by azaroth42** [comment]
After 6 months, clearly we don't care enough to come up with a new name :)
