### ISSUE TITLE
posterCanvas use is ambiguous for audio only

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1605]
Should the audio of the poster be played while the main content is buffering, or should it be played as ambient content while the user interacts with the main canvases?

Seems like we need a behavior on the canvas? Or ( 😖 ) two separate properties?

**Comment by zimeon** [comment]
Hmm... and should a video poster repeat, etc.. I note that this would seem to be an exception to any idea of inheritance of behaviors in #1612

**Comment by azaroth42** [comment]
After the call on 2018-06-26, my feeling is now that we should have two properties (with all the 😖 that results in). 

Rationale:
* We have agreed that both pre-play or during-play use cases are in scope (image while buffering, background music while playing) so can't solve it by saying it's one or the other alone
* If we solve it with a behavior on the canvas, then 
  * posterCanvas needs to be an array for the situation when there's both ...
  * If the behaviors aren't present, then either there would need to be a default or an exception handling routine. This seems complicated
  * If the same behavior is present in multiple canvases, a client would need to distinguish which to use somehow based on other metadata ... in a presentation driven environment. This seems very difficult, if not impossible.
* If we solve it with multiple properties, we document two relationships each of which can be present and has exactly one Canvas. That seems cleaner for everyone.

**Comment by tomcrane** [comment]
`placeholderCanvas` and `accompanyingCanvas`...

with sensible observations or rules about where each of these make sense.

**Comment by tomcrane** [comment]
And clearly showing through recipes the difference between `accompanyingCanvas` and the `together` behavior.

**Comment by zimeon** [comment]
Discussed on [2018-08-29 Technical Community Call](https://docs.google.com/document/d/1Rx-sUh2STNf6_GxRC1ghqsEuoj5LymRDsxi0_WpqCJ4/edit) - noted that proposal https://github.com/IIIF/api/issues/1605#issuecomment-414746302 was outcome of A/V group discussion. Consensus in favor of using `placeholderCanvas` and `accompanyingCanvas`, with good explanation and recipes

**Comment by azaroth42** [comment]
Closed by #1658

**Comment by zimeon** [comment]
Approved by TRC, already merged into `image-prezi-rc2`.
