### ISSUE TITLE
Recommend application/ld+json for Image info.json

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1606]
In Presentation 3.0 we recommend application/ld+json, with a fallback if necessary to application/json.  We should do the same in Image 3.0: http://iiif.io/api/image/3.0/#51-image-information-request

**Comment by urrape** [comment]
please do it!!! json-ld is the way

**Comment by zimeon** [comment]
I agree that Image 3.0 should have he same recommendation as Presentation 3.0

**Comment by zimeon** [comment]
Discussed on [2018-08-29 Technical Community Call](https://docs.google.com/document/d/1Rx-sUh2STNf6_GxRC1ghqsEuoj5LymRDsxi0_WpqCJ4/edit) - consensus in favor of `application/ld+json`

**Comment by azaroth42** [comment]
Closed by #1652
