### ISSUE TITLE
Appendix A tables have 99 problems, but being useful ain't one

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1608]
- [x] The new images from prezi3 are gone. Probably they needed to go to IIIF/website?
- [x] Canvas SHOULD have `label`
- [x] Range SHOULD have `label`
- [x] AnnotationCollection SHOULD have `label`
- [x] Merge Image and Other Content (identical requirements)
- [x] Canvas MAY have `thumbnail` is the primary requirement
- [x] `navDate` is under descriptive now
- [x] Range MAY have `navDate`
- [x] Canvas MAY have `navDate`
- [x] Annotation MUST have `id`
- [x] AnnotationPage SHOULD have `id` but see #1607 
- [x] `language` is missing from the tables completely
- [x] As is `profile`
- [x] As is `duration`
- [ ] Canvas `height`, `width` and `duration` are ... complicated
- [x] Collection MAY have `viewingDirection`
- [x] AnnotationCollection MUST NOT have `viewingDirection`
- [x] `timeMode` is missing from the tables
- [x] `logo` is now a linking property
- [x] Manifest MAY have `start`
- [x] `supplementary` is missing from the tables
- [x] Exceptions should be noted with a backlink to the right section 
- [x] Deref table is probably worthless. If it's entirely embedded, it MAY be also dereffed. If it's not, then it MUST be dereffed. Should fix in the prose.

Thanks to @jronallo for bringing up the first few issues that led to the extensive list above.

**Comment by tomcrane** [comment]
Halfway through PR here
https://github.com/IIIF/api/pull/1599#discussion_r186431090

There is still a discrepancy in the (non-table) text for label requirements for AnnotationCollection.

**Comment by azaroth42** [comment]
Closed by #1663
