### ISSUE TITLE
posterCanvases can have posterCanvases

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1615]
For canvas level fractal generation while loading.

Should be disallowed.

**Comment by tomcrane** [comment]
Observation on AV call - no use cases for allowing posterCanvas on posterCanvas

+1 to explicitly disallowing this in spec

**Comment by tomcrane** [comment]
Easy enough to disallow this in spec, but should wait for rewrite depending on outcome of #1605

**Comment by azaroth42** [comment]
Closed by #1658

**Comment by zimeon** [comment]
Approved by TRC, already merged into `image-prezi-rc2`.
