### ISSUE TITLE
Consider how to specify version of Image API to be used in order to interpret URL

### ISSUE THREAD

**Issue by beaudet** [IIIF/api#1616]
content negotiation is the proposal for presentation API, but unclear whether / how Image API would handle this, particularly for requests producing images (v.s. info.json) although I imagine the mechanism should be the same regardless?

**Comment by azaroth42** [comment]
I'm not sure that we even need content negotiation for the pixels, as the content doesn't change.  A v2 URL that uses `/full/full/...` could just redirect to `/full/max/...` and the requesting client won't notice anything different.

The content negotiation for the info.json however would need to use the same pattern as for the Presentation API if the same URI is to be used for both v2 and v3.

**Comment by beaudet** [comment]
One of the changes proposed for v3 is to disallow upscaling of region to WxH larger than the region.  That would result in a change in the pixels returned for certain requests depending on whether the server in use has implemented upscaling as per this note in v2.1.1: "The image server may support scaling above the full size of the extracted region."  In such cases, I suppose client implementations are dependent upon a particular server implementation anyway and should be programmed defensively to check the actual size returned rather than making an assumption about it.  In cases where the client implementation and server implementation are coordinated, it's not as big of a deal since switch to v3 can be better coordinated.

**Comment by azaroth42** [comment]
The major version of the API is able to be easily determined by the context URI of the info.json. A client that needs to know whether the API is v2 (and hence upscaling might work) or v3 (and hence upscaling might work, but by using ^) would be advised to simply grab the info.json and see. There were more widely breaking changes that happened between 1 and 2 (e.g. grey->gray, and native->default), and we haven't seen any issues that would warrant a version in the URI.

Propose close won't fix.

**Comment by beaudet** [comment]
I see the versioning of requests for pixels as a different problem from requests for info.json and I agree that client side code can be relied upon to adapt to info.json specific versioning issues. 

However, my concern with the proposal to close this issue for pixel requests is that it necessitates custom coding (minimally JavaScript) to be put in place to make version determinations before constructing IIIF URLs.  If I'm assembling a web page full of IIIF URLs, I would rather not have to rely on a JavaScript interpreter being available nor do I want to have to make a server call for each image on a page just to render that image.  That's a lot of back-end overhead. 

On the other hand, if ALL v2 requests for pixels can in fact (by virtue of the Image API v3 spec) be upgraded to equivalent v3 requests through IIIF server-side redirection, I think the capability to do so should actually be a requirement of the v3 spec and the conformance tests should test for that capability explicitly.  e.g. "servers SHALL redirect deprecated v2 syntax to the equivalent v3 URLs."

**Comment by tomcrane** [comment]
The problem with this is that whether an implementation of the 3.0 spec chooses to honour a previous version syntax, or redirect to the current version syntax, it needs to understand a previous version of the spec.

In practice:

>  If I'm assembling a web page full of IIIF URLs

Does that only apply to full/full => full/max? Other forms should just work if the client assumes 2.1 Image API at the other end.

**Comment by azaroth42** [comment]
And it seems unlikely that anyone would assemble a web page full of max size (as opposed to region) images.  Thumbnails should be unchanged. Also, it's a major version and this syntax change has been warned about in the current version of the spec for 18+ months.

Editors agree (2018-11-12): close wontfix
