### ISSUE TITLE
Should new icons in Presentation tables replace the existing ones in previous specs?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1617]
The icons in the summary of metadata requirements tables are in the website repo, so need to be be updated there. But should we keep the old icons in the old specs and give new names to the icons in P3, or just overwrite the old icons so that the older specs also get the new icons?

I favour keeping the old icons in the old specs.

**Comment by azaroth42** [comment]
:+1: I prefer to keep the old icons for the old specs. They're not as good, but we shouldn't just go changing them.

**Comment by tomcrane** [comment]
Agreed - maybe at this point we put the new icons in here:
https://github.com/IIIF/api/tree/image-prezi-rc1/source/api/presentation/3.0/img

... so that they live in the api repo rather than the website repo.

And leave everything else where it is for now.

**Comment by tomcrane** [comment]
Fixed by #1624
