### ISSUE TITLE
Update Image Change-log description of canonical URI syntax to include image tile request

### ISSUE THREAD

**Issue by mejackreed** [IIIF/api#1619]
The v3 change from `w,` to `w,h` http://zimeon.com/tmp/image-changes.html#4 specifically lists a `sizes` image request. It might also be useful to include a tile image request example here.

**Comment by zimeon** [comment]
Discussed in eds' call 2018-09-05: Agree that we should add an extra sentence to the change log 1.1.2 that describes how the change impacts tile requests.

**Comment by zimeon** [comment]
And for completeness, extra slide about tiles added in https://zimeon.github.io/iiif-v3-changes/image-3-changes.html#5
