### ISSUE TITLE
Content resources SHOULD have dimensions

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1622]
Thumbnails without width and height aren't much use to a client. It doesn't know whether the thumbnail is any good for the UI it wants to use it in.

But `width` and `height` on Content Resources are just _MAY_ and our example doesn't use width and height on the the thumbnail.

I suggest that Content Resources _SHOULD_ have width and height, where those dimensions are applicable, and that the examples in the spec show this use.

**Comment by tomcrane** [comment]
Addressed in #1626

**Comment by tomcrane** [comment]
Unanimous agreement on AV call 2018-07-24

**Comment by azaroth42** [comment]
Close fixed :)
