### ISSUE TITLE
Technical properties table doesn't include duration

### ISSUE THREAD

**Issue by cjcolvar** [IIIF/api#1630]
The technical properties table under http://iiif.io/api/presentation/3.0/#a-summary-of-metadata-requirements doesn't include `duration` and still has `width` and `height` as required for `Canvas`.  This doesn't reflect the rest of the 3.0 spec.

**Comment by tomcrane** [comment]
This is the unmerged RC1 branch:

http://preview.iiif.io/api/image-prezi-rc1/api/presentation/3.0/#appendices

**Comment by azaroth42** [comment]
Closing, already fixed :)
