### ISSUE TITLE
iiif.io automatic redirect from http to https

### ISSUE THREAD

**Issue by glenrobson** [IIIF/api#1640]
Due to the impending change with Chrome in 'July' (not sure of the exact date) to require SSL I am looking at changing the iiif.io website to use SSL.

In the first instance I would like to run the site on both http and https before moving to a place where we can implement a redirect from http to https. After this change it will mean all traffic will go through https. This will mean for example that contexts like the following:

http://iiif.io/api/presentation/2/context.json

Will automatically redirect to:

https://iiif.io/api/presentation/2/context.json

In discussion with the editors we are proposing the following plan:

 * Specifications before 3.0 (1.x and 2.x) will still point to http://iiif.io resources. 
 * 3.0 will be updated to use the https://iiif.io resources. 
 * Fixtures for 3.0 will also be updated to use https://iiif.io links. 

`https://iiif.io` is currently available if you type in the address directly. Also when you navigate between the /api/ and the rest of the website you will move from http to https. Progress and issues on the existing side by side site can be raised on:

https://github.com/IIIF/website/issues/11

Please raise any issues that an automatic redirect from http to https will cause your infrastructure here. If you would like to test this automatic redirect you can use the following context:

http://preview.iiif.io/api/https/api/presentation/2/context.json

**Comment by jpstroop** [comment]
We should probably update the 3.0 specs to use `https` in the links to the contexts, e.g. under [4.5](http://iiif.io/api/presentation/3.0/#45-linked-data-context-and-extensions).

**Comment by azaroth42** [comment]
Strong -1. We should continue to use http for context documents, and redirect up to https.

**Comment by jpstroop** [comment]
OK - let's cover on the call

**Comment by glenrobson** [comment]
@azaroth42 for posterity would you mind adding a rational to this ticket on our decision to retain http links in specifications that was agreed in the community call on the 1st of August? 

For info minutes are available at: 

https://docs.google.com/document/d/1Hcz50Rmhz9HMjgY8rKmW1tXxFMzUToGKliIsObMiMBQ/edit

Thanks

Glen

**Comment by azaroth42** [comment]
Rationale:  The http forms are used as identifiers for the structure, such as in the openseadragon implementation for detecting IIIF.  If those identifiers were not to resolve that would make it much more difficult to follow your nose to determine what is going on.

The actual protocol is "http". https is a shorthand for http+tls ... in the future, http 3.0 might do what http 2.0 was unwilling to and /mandate/ the +tls.  At which point https and http would be identical, and (one would presume) the protocol scheme would be just http.

**Comment by glenrobson** [comment]
Closing but will re-open if there are issues.
