### ISSUE TITLE
define v3 service profiles in a context / registry

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1641]
service profiles are not defined in the v3 context.  client deserializers (e.g. manifesto) need to be able to reference a registry of supported values/terms/URIs.  It looks like this document specifies that intention:
http://iiif.io/api/annex/registry/services/ though it is not implemented as a context.

I opened an issue in manifesto for this: https://github.com/IIIF-Commons/manifesto/issues/34 .  For example, "level2" is not a known reference.

**Comment by azaroth42** [comment]
They are indeed not defined.  When we had separate contexts, they were, and when we combined them, they got lost. Thanks for the catch!

**Comment by edsilv** [comment]
woops, posted my reply on the wrong repo!

**Comment by azaroth42** [comment]
The profiles defined here: https://iiif.io/api/presentation/3.0/#service 

Are in the context here: https://github.com/IIIF/api/blob/master/source/api/presentation/3/combined-context.json#L269-L345 

(As seen at:  http://iiif.io/api/presentation/3/combined-context.json)

Closing, already done
