### ISSUE TITLE
Support structured vocabulary properties for metadata values

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1642]
The metadata list can be consumed both by humans in the presentation interface and machines for indexing.  It would be beneficial for machine processing if the manifest includes a supplementary context that provides vocabulary references for the metadata labels.  This would facilitate the interoperability of the values, particularly in the 3.0 api where there can be multiple language labels.  I believe that the current specification and context does not restrict metadata to rdfs:label and rdf:value pairs, so supporting this would not be a breaking change, but perhaps a recommendation or option to faciltiate cross-domain discovery.

**Comment by zimeon** [comment]
See #438 ... the last time we considered this would likely undermine the practice we really need which is good `seeAlso` links to the real structured metadata

**Comment by azaroth42** [comment]
I agree with @zimeon. Propose close, won't fix. It's a presentation API, and mixing semantic / presentation data is not good practice, nor within the scope or design.

**Comment by christopher-johnson** [comment]
I found an example of how seeAlso can be used with types, though the "profile" links are all 404.  Used here, "profile" is equivalent to type, so I do not see any added value with the use of this property if its value does not provide a dereferenceable context.
````json
{  
   "seeAlso":[  
      {  
         "@id":"https://wellcomelibrary.org/data/b18035978.json",
         "format":"application/json",
         "profile":"http://wellcomelibrary.org/profiles/res"
      },
      {  
         "@id":"https://wellcomelibrary.org/resource/schemaorg/b18035978",
         "format":"application/ld+json",
         "profile":"http://iiif.io/community/profiles/discovery/schema"
      },
      {  
         "@id":"https://wellcomelibrary.org/resource/dublincore/b18035978",
         "format":"application/ld+json",
         "profile":"http://iiif.io/community/profiles/discovery/dc"
      }
   ]
}
````
This could be simplified into:
````json
{  
   "@context":[  
      "http://iiif.io/api/presentation/2/context.json",
      "http://iiif.io/api/discovery/context.json"
   ],
   "seeAlso":[  
      {  
         "@id":"https://wellcomelibrary.org/data/b18035978.json",
         "format":"application/json"
      },
      {  
         "@id":"https://wellcomelibrary.org/resource/schemaorg/b18035978",
         "format":"application/ld+json",
         "@type":"discovery:schema"
      },
      {  
         "@id":"https://wellcomelibrary.org/resource/dublincore/b18035978",
         "format":"application/ld+json",
         "@type":"discovery:dc"
      }
   ]
}
````
Adding a standard base discovery context could be an improvement.

**Comment by christopher-johnson** [comment]
RE: "mixing semantic / presentation data is not good practice".  I do not understand this point.  data is data.  It is possible to index metadata that has embedded html, and then have a client render the html from a "semantic" search hit.  Check this: https://collections.iiif.cloud/collection/uc?view=list

**Comment by zimeon** [comment]
Re. https://github.com/IIIF/api/issues/1642#issuecomment-412250659 -- "simplification" of `"profile":"http://iiif.io/community/profiles/discovery/dc"` to `"@type":"discovery:dc"` is only a simplification for a JSON-LD aware client. It is a design principle that [IIIF JSON-LD should be of sufficiently regular form that a plain JSON client can understand it](https://iiif.io/api/annex/notes/design_patterns/#json-ld-design-patterns), and we are also avoiding `@` to make working with various languages easier (this latter point is already addressed by aliasing `@type` to `type`)

**Comment by christopher-johnson** [comment]
I think I have a solution for the type of a seeAlso reference.  It is possible to serve this as plain html and add a [dataLayer](https://www.optimizesmart.com/google-tag-manager-data-layer-explained-like-never/).   I have experimented with this in conjunction with Google Tag Manager with schema.org json-ld objects [here](https://collections.iiif.cloud/collection/harvard).  An indexing implementation could then simply access this dataLayer.  There remain a few issues that I have yet to solve, but it seems a reasonable path forward,

**Comment by christopher-johnson** [comment]
I close this issue, since I generally agree that structured data is out of scope in the manifest metadata directly.
