### ISSUE TITLE
Interactions between behaviors

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1643]
What should the Presentation API spec say regarding interactions between multiple [`behavior`](http://iiif.io/api/presentation/3.0/#behavior) values on a resource (either directly specified or inherited)? Should there be documentation so that clients handle non-obvious interactions consistently (e.g. `repeat` with and without `auto-advance` cases are currently described)?

**Comment by zimeon** [comment]
Discussed on [2018-08-29 Technical Community Call](https://docs.google.com/document/d/1Rx-sUh2STNf6_GxRC1ghqsEuoj5LymRDsxi0_WpqCJ4/edit) in relation to #1612 (Inheritance of behaviors).

Two alternative approaches were suggested:
 1. clarify individual definitions but don't define interactions, thus behavior might be client dependent
 2. define the set of possible interactions (note permutation issue) for more consistent client behavior

A suggestion was that in 3.0 we might adopt 1) with a warning that clarifications of interactions (2) are expected in later revisions. It was agreed that such clarification in a 3.x would not be a breaking change.

**Comment by azaroth42** [comment]
As a proposal for unblocking this issue:

* In the specification we note any disjoint behaviors (e.g. a Manifest cannot be both paged and continuous). This would be testable and allow for error conditions to be generated.
* Interaction and the resulting rendering / user interface implications between the permissible permutations are client dependent, but recommendations are made in the algorithms document. 
* Add a warning that further clarifications are to be expected in subsequent minor releases.

**Comment by azaroth42** [comment]
Closed by #1681
