### ISSUE TITLE
Require format for content resources?

### ISSUE THREAD

**Issue by irv** [IIIF/api#1645]
`format` is currently a _SHOULD_ in the 3.0 spec for content resources.

For a `type` of `Image`, where the browser natively renders (most) of the formats supported by the image API, there's little point in being verbose and requiring `image/jpeg` etc.

For audio and video, where not all browsers support all codecs and formats, falling back to javascript implementations is the established practice. Having a `type` of `Audio` is helpful, but not as helpful as a `format` would be, letting you know if you need to load DASH.js or HLS.js for example. Otherwise the client has to make an additional call to the resource, inspect the content type, then potentially re-request it using the necessary javascript library.

Awesome clients like UniversalViewer are already relying on the `format` property of a content resource to work out how to render it appropriately, which is obviously going above what the spec says and failing when a (valid) manifest without a format is present

I can see this was discussed in the context of `seeAlso` in #1227, where the editors agreed it was a bad idea. Is it a bad idea for content resources?

**Comment by azaroth42** [comment]
Given that it doesn't help a lot for images, or for basic Audio/Video that is rendered directly via HTML5, as compared to DASH or HLS, I'm in favor of leaving it as SHOULD.  I could see a more editorial guidance note about when it is most useful to include?

**Comment by zimeon** [comment]
@irv are the media types for A/V specific enough for a client to understand the codec etc. and whether it can play it? My sense has been that this is not the case.

I think that requiring a `format` for **all** content resources would be a potentially burdensome requirement. It would make any manifest without `format` values invalid so I think we'd need a strong case to require it.

**Comment by azaroth42** [comment]
Discussion on 2018-09-26 call: Consensus to leave as `SHOULD`, and that `format` will be obvious when it's needed (such as adaptive bitrate video). Browsers have other ways to figure out what to do with content links. Nothing between `SHOULD` and `MUST` and must is too high a burden.

**Comment by azaroth42** [comment]
Thus, close won't fix.
