### ISSUE TITLE
Resource type `Application` has no examples in 3.0 Prezi Spec.

### ISSUE THREAD

**Issue by benwbrum** [IIIF/api#1676]
The Presentation API Alpha 3.0 document [lists `Application` as a resource type](https://iiif.io/api/presentation/3.0/#type) with the description "Software intended to be executed", but these resources appear nowhere else within the document.  

What is an `Application` resource, what does a client do when it encounters a reference to one?

**Comment by azaroth42** [comment]
Good call!

The intent of the table was to provide the list of types that might be encountered other than the core Collection, Manifest, Range and Canvas. We took the list from the W3C Annotation spec, but Application isn't necessary, I agree, only the content ones.

The properties that have non-IIIF types:

* `thumbnail` -- any content type
* `homepage` -- Text
* `logo` -- Image
* `rendering` -- any content type
* `service` -- I guess this could be `Application`, but the example has `Service`
* `seeAlso` -- Dataset

Propose to remove Application from the list of types and instead recommend `Service` as a type under the `service` property, and clarify the above list throughout.
