### ISSUE TITLE
Resource type `Service` in example manifest not documented in Prezi 3.0 spec

### ISSUE THREAD

**Issue by benwbrum** [IIIF/api#1677]
The [example manifest](https://iiif.io/api/presentation/3.0/#52-manifest) in the Presentation 3.0 spec document lists a `service` element with the resource type `"Service"`:

```
  "service": [
    {
      "id": "https://example.org/service/example",
      "type": "Service",
      "profile": "https://example.org/docs/example-service.html"
    }
  ],
```

However `Service` is not listed as a valid resource type in the [list of resource types acceptable in a `type` element](https://iiif.io/api/presentation/3.0/#type).

I suspect that `"Service"` and `"Application"` may mean the same thing?

**Comment by azaroth42** [comment]
Per #1676 comment, I agree. The only place a Service can appear is referenced by the `service` property, so we should list it there along with the other Service types from the other IIIF specs.

**Comment by tomcrane** [comment]
* Type list is for content types
* Add "Model" as a content type - or similar - for 3D objects
* Don't add all the IIIF classes
* Add a 3D recipe to cookbook

**Comment by azaroth42** [comment]
Actually, there should never be a vanilla `Service`, as the properties that the object can have are defined by a context document, that then needs to be referenced from `@context`. So the types of Services should be reasonably distinct to try and forestall namespace collisions.

Removing Service from the doc and as per Tom's notes in the comment above.
