### ISSUE TITLE
@context @container value must be one of the following: @list, @set, @index, @language

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/api#1700]
in the 3.0 presentation api `@context`, there are several terms with `@container` keys defined with arrays.  For example,
````json
"label": {
   "@id": "rdfs:label",
   "@container": [
     "@language",
     "@set"
   ]
}
````

When tested on the json-ld dev playground, the processor reports that `@container` only expects one value, not an array.  Removing (unnecessary?) `@set` assignment corrects this.  e.g. http://tinyurl.com/yazf3wtg

**Comment by azaroth42** [comment]
`"@container": ["@language", "@set"]` is part of JSON-LD 1.1. See https://www.w3.org/TR/json-ld11/#ex-71-indexing-languaged-tagged-strings-in-json-ld-with-set-representation 

The playground is behind the spec.

**Comment by christopher-johnson** [comment]
hmm, ok thanks for the reference.  it looks like they are using the most current jsonld.js library on the dev site, but the processing mode must still default to 1.0.  Related to https://github.com/json-ld/json-ld.org/issues/589

**Comment by azaroth42** [comment]
Yes. @dlehn has volunteered to update the playground, so I anticipate that it will be up to date before too much longer :)
