### ISSUE TITLE
restrict search to collections

### ISSUE THREAD

**Issue by eroux** [IIIF/api#1701]
Our use case for annotations include the user selecting the web annotation collections they want to see displayed.

Ideally we would implement a small widget that would:
- retrieve annotation collection relevant to the target (in a separate API, although something of the sort would probably be nice in the IIIF Search), which depends on the auth (some users might have private annotations)
- display a UI where the users selects the annotation they want to see / search in
- when the user uses the IIIF Search, only the results in these collections are returned
- the results indicate clearly which annotation belongs to which collection

I have no idea how to implement that in a nice way though (it would probably clutter the query url)... Or did I miss something and is it already possible?

**Comment by eroux** [comment]
(just to be clear, I'm talking about [AnnotationCollection](https://www.w3.org/TR/annotation-model/#annotation-collection)s, not IIIF collections)

**Comment by azaroth42** [comment]
For searching an individual AnnotationCollection, you would associate the search service with the Collection.

**Comment by azaroth42** [comment]
Editors call 2018-11-12:

Noted that the specification defines the possible resources that can have search services associated in 3.1:

> Any resource in the Presentation API may have a search service associated with it. The resource determines the scope of the content that will be searched.

Do not believe that there are any changes to the specifications needed.  @tomcrane to provide example of the JSON to use for this service, and then consider it closed.

**Comment by tomcrane** [comment]
```
"supplementary": {
  "id": "https://example.org/iiif/book1/annocoll/introTexts",
  "type": "AnnotationCollection",
  "service": [
    {
      "@id": "https://example.org/iiif/book1/annocoll/search",
      "@type": "SearchService1",
      "profile": "http://iiif.io/api/search/1/search"
    }
  ]
}
```

**Comment by eroux** [comment]
thanks!
