### ISSUE TITLE
Mapping of 'profile'

### ISSUE THREAD

**Issue by aisaac** [IIIF/api#1702]
We may have a problem with the pattern to refer to (metadata) profile according to which the metadata about a IIIF resource is provided (in the seeAlso): https://iiif.io/api/presentation/3.0/#seealso

Currently the IIIF Presentation API uses 'profile' which is mapped to doap:implements in the JSON-LD context (https://iiif.io/api/presentation/3/combined-context.json).

But recent work I've been exposed to uses dcterms:conformsto for this, including:
- the revised DCAT: https://www.w3.org/TR/vocab-dcat-2/#Property:resource_conformsto
- Schema.org https://github.com/schemaorg/schemaorg/issues/1516

To have IIIF patterns aligned with this practice, "profile" should be mapped to dc:conformsTo instead of doap:implements.

This could cause a conflict with "protocol", which is currently mapped to dc:conformsTo. That mapping could be changed to. Or kept the same - maybe it doesn't matter so much.

We had this discussion in the past, in the context of the IIIF profile for the Europeana Data Model: https://github.com/IIIF/api/issues/558
I feel that the observations above could be enough to raise the issue again, if just for acknowledging what is done in other spaces for solving the same information need.

**Comment by aisaac** [comment]
@azaroth42 here's the issue I've promised during TPAC. But I can't label it appropriately!

**Comment by mikeapp** [comment]
11/7 Proposal: change to dc:conformsTo and find another mapping for `protocol`

**Comment by azaroth42** [comment]
dcterms:type ?

> The nature or genre of the resource.

**Comment by azaroth42** [comment]
Closed by #1722
