### ISSUE TITLE
Please clarify case sensitive of types (and more generally for property values on which data model depends?)

### ISSUE THREAD

**Issue by beaudet** [IIIF/api#1703]
I pose the question: Are the values for model-dependent properties, e.g. "type", generally case sensitive or not? e.g. @type":"sc:Manifest" == "SC:manifest" ???

**Comment by zimeon** [comment]
Yes, everything is case sensitive as follows from the underlying specs. I wonder whether we need to spell this out somewhere?

**Comment by beaudet** [comment]
That's what Rob thinks.  I was chatting with him on Linked.Art about similar requirements there and he suggested to create this ticket in both IIIF and Linked.Art issue lists for tracking.

**Comment by azaroth42** [comment]
Yep, :+1: from me. I think we should be clear in all of the specs that the terms we specify are all case sensitive.

**Comment by azaroth42** [comment]
Closed by #1704
