### ISSUE TITLE
Remove /annex/ from /registry path, add text-granularity under /extensions/

### ISSUE THREAD

**Issue by mikeapp** [IIIF/api#1706]
Proposal to add description of extension property proposed by the Text Granularity group under `extensions/text-granularity/`

Also proposed to move `registry` immediately under `/api/` (i.e., no longer a child of `/annex/`).

**Comment by zimeon** [comment]
I agree with both of these ideas. I think now is our last opportunity (before we put any real content under registry and release the 3.0 specs) to move `registry` up one level. I don't see why it should be under `annex` as opposed to a peer

**Comment by azaroth42** [comment]
Re adding an extension for TG, :+1:.

For /api/registry/ ... I think that should be part of a more comprehensive discussion of what /annex/ is. It has so far been thought of as everything API related that isn't itself an API.  I know we're unlikely to have a registry API separate from the description of the registry, but name collision is an issue if we're expanding the scope of what goes in the base path.

**Comment by azaroth42** [comment]
Notes from community call:

* Should discovery import to viewers be a separate document? 1705, 1706
  * TG WG will likely also have a forthcoming extension.
  * Having a consistent site architecture, is useful.
  * Two new API level paths, registry and extensions

**Comment by azaroth42** [comment]
Site Structure proposed:

/api/(api)
/api/registry/
/api/extension/
/api/cookbook/
/api/annex/

**Comment by azaroth42** [comment]
Closed by #1716
