### ISSUE TITLE
Why include anno.jsonld when it's scoped?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1710]
Apart from the beneficial side effect of @context always being an array, we don't need to include the annotation context directly. The prezi (or indeed master) context scopes in the annotation context at the appropriate places (Canvas.items and *.annotations).

Including it at the global level just lengthens any processing, as it gets re-inserted later.

What am I missing?

**Comment by azaroth42** [comment]
Editors agree remove anno context from instance docs (but may still be array due to extensions)

**Comment by zimeon** [comment]
We already have language for single string or array `@context` in Image 3.0: https://iiif.io/api/image/3.0/#52-technical-properties

**Comment by azaroth42** [comment]
Closed by #1719
