### ISSUE TITLE
auth: clarify client workflow

### ISSUE THREAD

**Issue by eroux** [IIIF/api#1732]
Continuation of https://github.com/UniversalViewer/universalviewer/issues/624 : it seems that the way UV handles the login workflow is by trying external first, then move to the login interaction pattern if that fails. This is a reasonable solution as it solves the problem explained in the UV issue, but it doesn't seem to be documented or recommended neither in the spec or in the technical guidelines. It would be very helpful to have that as a standard behavior for clients, that would simplify server implementations.

**Comment by tomcrane** [comment]
This is documented in the spec in section 4, _Workflow from the browser client perspective_:

https://iiif.io/api/auth/1.0/#workflow-from-the-browser-client-perspective

The diagram and the following text describe the order in which services should be attempted.

**Comment by atomotic** [comment]
it's not clear to me why the idea of using token is not considered in IIIF Auth spec
i've asked a question on this topic in this ticket: https://github.com/UniversalViewer/universalviewer/issues/631

my endorsement in using token is due basically to the "**Delegation script**" feature of **Cantaloupe** server, that would make extremely easy to write a logic behind user authorization
https://medusa-project.github.io/cantaloupe/manual/4.0/access-control.html#example-7
