### ISSUE TITLE
License for context (etc) resources is not clear

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1734]
From https://groups.google.com/forum/#!topic/iiif-discuss/fEY12g6cpjk

It is not clear under what license the auxiliary technical files are published. I think they should be CC0, but could equally be CC-BY?

**Comment by zimeon** [comment]
I think all of the contexts / examples / fixtures / frame (when we have them) should be CC0.

**Comment by zimeon** [comment]
On technical grounds, public domain declarations (such as CC0) fit at the root of license compatibility trees such as that shown on https://en.wikipedia.org/wiki/License_compatibility , but CC-BY requires thought or guesswork (and actually doing the BY).

**Comment by azaroth42** [comment]
Propose that this can go in the [disclaimer document](https://preview.iiif.io/api/image-prezi-rc2/api/annex/notes/disclaimer/) for machine readable documents.

**Comment by azaroth42** [comment]
Closed by #1803
