### ISSUE TITLE
Add agent around logo in Image 3

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1735]
For consistency w/ Prezi

https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#provider

**Comment by azaroth42** [comment]
This is a normative change, but one that would be painful if we didn't do.

**Comment by azaroth42** [comment]
Propose that we use this as the easy introduction / test case for the TRC process.  The change is (one hopes) entirely uncontroversial.

**Comment by zimeon** [comment]
Issue approved by TRC vote

**Comment by tomcrane** [comment]
This TRC issue approved `provider` for the Presentation API:
https://github.com/IIIF/trc/issues/7
(Provider property/Agent with logo, homepage, etc.)

And this TRC issue approved multiple logo images in Image and Presentation:
https://github.com/IIIF/trc/issues/3

So, I can make a PR that has providers in both APIs, with multiple logos premitted.

But do we have approval for adding the whole `provider` structure to the Image API?
https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#provider

**Comment by azaroth42** [comment]
I think the opposite is true. It's fine for Presentation, but we should be removing logo and requiredStatement/attribution from Image, per discussions.

We asked on two calls now, plus an email to -discuss and no one has spoken up in favor of keeping it. 

I'll make an issue now that we're at that stage!

**Comment by tomcrane** [comment]
So, the immediate action is then to allow multiple logos in Prezi, to reflect TRC #3, and leave `logo` in Image (which is already `[ .. ]` in RC2) until a decision on https://github.com/IIIF/api/issues/1787, which will need TRC approval.

I'll do the former now.

**Comment by azaroth42** [comment]
Superceded by #1787. Now invalid.
