### ISSUE TITLE
Inconsistency in patterns for representing translations (wrt 'supplementary')

### ISSUE THREAD

**Issue by aisaac** [IIIF/api#1738]
Imagine a French manuscript with an English translation.
According to the new 'supplementary/supplementing' pattern, the English translations (annotations) would be 'from' the content, and thus can be grouped into as a Range.
It seems not possible to group the French transcriptions into their own Range though, as Ranges look like they're restricted to refer to collections of supplementary annotations (https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#supplementary and the diagram in 2.1).
If this understanding is correct, it is an odd situation. While there is a difference between the English and the French text, it is desirable to use similar patterns to represent them.

**Comment by mixterj** [comment]
@aisaac is the primary concern here the difference between 'translation' and 'transcription' and the semantic relationship they have to the item on the Canvas?

If I understand correctly the concern is that the French 'transcription' could be modeled as a relationship with the Canvas BUT the English 'translations' could be modeled as an Annotation Collection which is connected to a Range which is ultimately connected to the Manifest.

**Comment by zimeon** [comment]
I'm not sure I understand the issue correctly but I note that the [`annotations`](https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#annotations) property may exist on a Range (also Canvas etc.) and may contain `supplementing` annotations grouped in Annotation Pages which could express themselves to be `partOf` and Annotation Collection. Similarly, the [`supplementary`](https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#supplementary) property may exist on a Range (only) and may contain `supplementing` annotations grouped in an Annotation Collection (containing Annotation Pages).

I don't recall why `supplementary` is restricted to point to a single Annotation Collection. On the face of it I can image multiple Annotation Collections on a single Range (taking the [spec example](https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#58-annotation-collection) one might have the "Diplomatic Transcription" and the "Less Diplomatic Transcription").

Perhaps one outcome of this discussion should be a cookbook pattern for "Manuscript with transcription and two translations", to go in the [Textual and other supplementary content]()
https://preview.iiif.io/api/image-prezi-rc2/api/cookbook/#textual-and-other-supplementary-content) section? Could be comment on https://github.com/IIIF/cookbook-recipes/issues/16 or an extra case.

**Comment by aisaac** [comment]
@mixterj yes this is the issue
@zimeon maybe the issue is not one of cardinality, but that the Range used as anchor for the transcription can have other ranges, but then they should be 'supplementary'. So the two lists of annotations would have to be attached to different levels in the diagram of 2.1. Maybe a cookbook combining transcriptions and translation patterns would indeed show that this is not so big an issue, but I thought I would flag it, and it's not going to be trivial for implementers.

**Comment by azaroth42** [comment]
Editors agree - the supplementing motivation is the correct one for transcriptions, and this is adequately is adequately specified already.  However a transcription use case in the discussion of `supplementary` would be valuable to clarify this.

**Comment by azaroth42** [comment]
In trying to add this to `supplementary`, I couldn't think up an easy Range that would usefully distinguish the translation / transcription. Is the use case that some of the content is transcribed and a different part is translated, and thus for the user to navigate to those sections, there needs to be a Range?

**Comment by tomcrane** [comment]
Summary comment added to PR but it should be flagged here too:

https://github.com/IIIF/api/pull/1807#issuecomment-483641344

**Comment by zimeon** [comment]
Merged #1807
