### ISSUE TITLE
Prezi 3.0 RC2: anchor for language of property values does not resolve

### ISSUE THREAD

**Issue by anarchivist** [IIIF/api#1744]
References to the "languages section" (4.4, Language of Property Values,  in e.g. `homepage`) in the Prezi 3.0 RC2 do not resolve. The links are pointing to the anchor `#43-language-of-property-values` instead of `#44-language-of-property-values`.

**Comment by azaroth42** [comment]
Good catch!

**Comment by tomcrane** [comment]
Closed by #1748
