### ISSUE TITLE
Cookbook recipe process clarification

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1746]
Issue for recipe may be redundant if the pull request explains the recipe clearly.

Can the process be short-circuited, so that the PR and the issue for it can be created by the recipe proposer at the same time? This may be better for straightforward recipes.

**Comment by zimeon** [comment]
Editors' discussion 2019-01-23 -- if the PR is simple and immediately available then the issue need only be a brief description, but it is simplest if we always have both
