### ISSUE TITLE
Clarify that level2 image API MUST for extra qualities should be in the info.json

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1754]
Rather than omitting as they MUST be there at level 2

**Comment by azaroth42** [comment]
e.g. in the Image API spec, make it clear that if at level 2, that color or gray is supported (which is most of the time) then they MUST be present in `extraQualities` in the image's info.json description

**Comment by jpstroop** [comment]
i.e., if the 'source' image is grayscale, you can't produce color, and there is no way to infer this from the compliance level.

**Comment by zimeon** [comment]
IIIF/trc#19 approved, can move ahead with PR #1809
