### ISSUE TITLE
Cookbook technical infrastructure issues

### ISSUE THREAD

**Issue by glenrobson** [IIIF/api#1756]
Issue for technical related issues raised during the cookbook session:

 * Investigate code highlighting javascript options
     * https://ace.c9.io/
 * Fixture hosting at fixtures.iiif.io from s3 and ensure reference image API uses s3 version.

**Comment by glenrobson** [comment]
* How do we both include json into the cookbook but also allow it to be accessible as a separate JSON file .

**Comment by mikeapp** [comment]
Another possible library: https://prismjs.com

**Comment by glenrobson** [comment]
Looking at how to integrate the theme from the API and website into the cookbook website and the way to do it properly would be to create a theme in a gem file:

https://jekyllrb.com/docs/themes/

but for now just going to copy across the minimum as doing it correctly would mean changing the `api` and `website` to use this new theme...

**Comment by glenrobson** [comment]
Look at manifest ids and if we can use jekyll varibales like `page.major` in:

https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0001-mvm-image/manifest.json

but make it work at:
https://preview.iiif.io/cookbook/themed/recipe/0001-mvm-image/

This would be something similar to:

https://github.com/IIIF/website/blob/discovery_list/source/community/groups/discovery/collection.json

**Comment by glenrobson** [comment]
Also need to work out how links between recipes work see A/V example.

**Comment by glenrobson** [comment]
Done
