### ISSUE TITLE
Create recipe issues in new repo

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1758]
...and a directory per recipe in this new repo, with _name_/index.md with the template markdown.

This allows us to set milestones and track progress, use a project board, etc.

**Comment by azaroth42** [comment]
Also so we can have more committers than just the editors, without opening up the /api repo. People can self-assign, etc.

Need a merge script to bring them into /api

**Comment by glenrobson** [comment]
Do we also need a preview setup for cookbooks? I think so...

**Comment by tomcrane** [comment]
https://github.com/IIIF/cookbook-recipes

These were started by copying from the cookbook-session branch from the Edinburgh WG, so are the latest work.

Still to do:

- [ ] Link all the issues to their index.md pages
- [ ] Add the checklist in the readme to all the issues (and the issue template) once we agree what that checklist is
- [ ] Link the index.md
- [ ] Decide on formatting, highlighting etc

I've done the first for the recipes tagged "Edinburgh", e.g. https://github.com/IIIF/cookbook-recipes/issues/4 (those that were already started, or started in Edinburgh)

Oddity - we have two recipes for https://github.com/IIIF/cookbook-recipes/issues/38.

I've used a naming convention for the name of each recipe's directory - it includes the issue number, padded. There's no need to continue with this if we don't like it, it just made the initial job easier.

**Comment by tomcrane** [comment]
https://github.com/IIIF/cookbook-recipes/pull/95 adds in just enough Jekyll to create recipes locally and see what they look like.

It also demonstrates the use of prism.js, which has the benefit of including source.json files, and therefore avoiding duplication of code - the recipe fixtures (the JSON parts at least) live with the recipe in the cookbook repository, can be served direct as JSON, but can also be included in recipe pages, with line numbers, line highlights and so on.

I don't know what the build process would be after that point - when a recipe is approved by the TRC, it moves across to (or gets replicated in) the cookbook area of the site. 

The prism library includes code samples client side (it makes XHR requests for them). We might want a server side build process to do this once the recipe becomes part of the site.

There is some more work to do with prism.js


Experiments:

**Comment by glenrobson** [comment]
The prism stuff looks good! How does this relate to needing github pages?

**Comment by tomcrane** [comment]
@glenrobson This still needs a deploy/preview-branches, in the same way the website / api is a Jekyll build that works locally.  

The difference here, I think (but am not sure) is that this particular repo never needs to build a complete "cookbook" public facing site for official approved recipes, because they get pulled in to the main site by the merge script mentioned in https://github.com/IIIF/api/issues/1758#issuecomment-444942936

If that is the case, is a gh-pages view of `master` site enough? Or not? We could get away with a GitHub-run Jekyll build if we don't need to do anything particularly complex (unlike the main site).

Perhaps the ability to preview branches is the clincher, don't think we can do that with GitHub.

**Comment by glenrobson** [comment]
I was thinking rather than having a merge script which would lose any history / discussion regarding the recipe that we have something like:

`https://cookbooks.iiif.io`

which is proxyed into the correct place in the website (similarly to how `/api/` is done). You could then also have `https://cookbooks.iiif.io/preview/<branch_name>` or `https://preview.iiif.io/cookbooks/<branch_name>` to match the others. 

This would mean the TRC approval would be merging it to master rather than moving it between repos.

**Comment by tomcrane** [comment]
Yeah, that makes sense to me.

I was coming at it from having a large, semi-planned structure (recipes in a particular order) that we're picking finished recipes out of as they are approved.

Several people might want to work on a lot of related recipes at once and see how they fit together, but that could be done with more preview branches.

So the absolute minimum Jekyll build would actually become something more like the current site.

**Comment by glenrobson** [comment]
Yes, I would go ahead an merge the minimum Jekyll build. I can upgrade it to pull the minimum it needs to theme it to fit in the IIIF site.

**Comment by tomcrane** [comment]
Will do - might as well add gh-pages as it does no harm and gives us something to look at in the interim. The only problem is that `master` is then in no fit state to be echoed to the live site, as it is full of placeholders. But maybe that's OK for this early stage.

**Comment by glenrobson** [comment]
Cookbook discussion 22nd May 2020.

Can we close this seems done? :-)

**Comment by azaroth42** [comment]
Closing, well and truly done
