### ISSUE TITLE
Logos with internationalized text

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1760]
Related to #1759, if an organization has multiple logos with text in different languages, then the current restriction of one logo per Agent does not allow the set of logos to be included.

No one has actually asked for this, but to go from single external resource to an array would be a breaking change if it is asked for.

And even still, perhaps it's Anglo-centricity, but I don't think this is important to make without at least canvassing the community to see if anyone would use it.

**Comment by eroux** [comment]
We would definitely use that. An idea that just popped up is that our logo is black so ideally there would be a different logo if the background of the viewer is dark (like in UV or Mirador) vs. when it's light (like in Diva).

**Comment by azaroth42** [comment]
We (Getty) also have dark and light logos, but how the manifest would declare which one to use seems difficult (and beyond the scope of the current issue). However if we allow multiple logos, then there would be the scope to add it in a future release without (hopefully) a backwards incompatible change.

**Comment by azaroth42** [comment]
Eds (non quorate discussion)  - allowing multiple would enable extensions to clarify light/dark or other situations beyond language. Without multiple, then this would be invalid.

**Comment by tomcrane** [comment]
:+1: No objection to multiple logos.

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
:+1:

**Comment by jpstroop** [comment]
👍
