### ISSUE TITLE
AnnotationPage Processing Order requirements conflict

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1763]
Prezi3 beta says:
> Embedded Annotation Pages SHOULD be processed by the client first, before externally referenced pages.

And also:
> Clients SHOULD process the Annotation Pages and their items in the order given in the Canvas.

So the processing model for an external Annotation Page followed by an embedded Annotation Page is at a deadlock as to which to do first, as both are SHOULD.

**Comment by azaroth42** [comment]
Proposed resolution:  Process in order of the canvas and recommend that if you want internal ones processed first, you put them first in the order.

**Comment by tomcrane** [comment]
:+1: - much more flexible for the publisher and easier to understand for the client impl.

**Comment by zimeon** [comment]
IIIF/trc#22 approved, we can move ahead with merge of #1815
