### ISSUE TITLE
Annotation homepage vs IIIF homepage

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1765]
In changing to use `homepage` from `related` we added a new conflict between IIIF and the Annotation model, which also uses `homepage` for agents.
The context definition will mean that the right definition (assuming that homepage on an Annotation's agent is the Annotation version) but we might need to spell it out in the API docs, like we do with `value`.

Conversely if we want agents to always use the same (IIIF) homepage definition, we would need further changes to the specs.  I'm not averse, but something that should be discussed again perhaps now we're closer to the end of the road.

Related to #1764

**Comment by azaroth42** [comment]
Same solution as #1764.

**Comment by zimeon** [comment]
Editors agree that no change `homepage` name but will point out difference from Annotation model `homepage` in text for resolution of #1764

**Comment by azaroth42** [comment]
Closed by #1804
