### ISSUE TITLE
Image API version 2 level2.json contains `profileLinkHeader`

### ISSUE THREAD

**Issue by lutzhelm** [IIIF/api#1766]
A little late for that one, but:

https://iiif.io/api/image/2/level2.json lists `profileLinkHeader` in `supports` which it shouldn't according to https://iiif.io/api/image/2.1/compliance/#http-features .

**Comment by azaroth42** [comment]
:+1:  The technical files are not governed by the same semantic versioning requirements as the specifications, so I propose that we fix this one.

**Comment by zimeon** [comment]
Not part of v3 milestone as this is an issue with v2 specs. However, we need to create corresponding files in /3/ without this problem --> #1796
