### ISSUE TITLE
Can cookbook recipes include extension ingredients?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1773]
Example - a while back there was a discussion about improving viewer thumbnail performance by including thumbnails for the manifest as a sprite sheet (a single image), or set of sprite sheets for paging.

This would require an extension property to hold the data - for a viewer to know that the linked resource is a sprite sheet, and to understand a further resource (might be an anno list) that links regions of the sprite sheet image (i.e., individual sprites) to canvases.

If the extension made its way into the registry, it would be great for a recipe to accompany it - but would that recipe go into the cookbook? Into an _Extensions_ section of the cookbook for recipes for blessed IIIF extensions?

**Comment by azaroth42** [comment]
I think so. They'll need to be approved, so no chance of people sneaking in craziness.

**Comment by tomcrane** [comment]
`transcription` and `translation` are good examples too.

**Comment by tomcrane** [comment]
Close?

**Comment by glenrobson** [comment]
Cookbook group 22nd May 2020 comments:

OK to have extensions in cookbook but only if they are live extensions that have gone through the TRC. 

We agree with closing this issue and we can take the above rule into the recipe process descriptions.

**Comment by kirschbombe** [comment]
The cookbook has recipes for the navPlace extension, so yes :) For example, https://preview.iiif.io/cookbook/thumbnail-canvas/recipe/0139-geolocate-canvas-fragment/
