### ISSUE TITLE
Can a machine negotiate the clickthrough auth interaction pattern?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1778]
Short answer - no:

> Non-user-driven clients must not use access cookie services with the Clickthrough interaction pattern, and instead halt.

https://iiif.io/api/auth/1.0/#clickthrough-interaction-pattern

Solution - publisher provides the external service as well. Cookbook recipe to follow at https://github.com/IIIF/cookbook-recipes/issues/85 (some notes there).

Reason for this **_API_** issue - should Auth vNext provide an additional interaction pattern to make this easier for publishers to support? Clickthrough for machines? Or is that too much of an edge case?

(I want to mine data from text in images protected by clickthrough auth).

**Comment by azaroth42** [comment]
What about a login that just auto-accepts every request? The advantage of click through is that you don't leave the UI ... but that's of no importance to a machine.

IMO it's too much of an edge case. It also starts to get into actual authentication, rather than just orchestration of the workflow.

**Comment by tomcrane** [comment]
Would be made obsolete by #2035

**Comment by tomcrane** [comment]
Close?
