### ISSUE TITLE
Terms defined in API drafts missing in combined-context.json

### ISSUE THREAD

**Issue by lutzhelm** [IIIF/api#1779]
While playing around with version 3 I noticed that the following terms are defined in the Presentation API or Image API drafts but have not yet been defined in the combined-context.json. I don't know at what point any term definition is added to the context document...

Image API types (already fixed via #1774):

- ~~`Tile`~~
- ~~`Size`~~

Image API values:
- `sizeUpscaling`

Presentation API properties:

- `placeholderCanvas`
- `accompanyingCanvas`
- `provider`

Presentation API values:

- `no-auto-advance`
- `no-repeat`

**Comment by zimeon** [comment]
Closed by merge of #1810
