### ISSUE TITLE
using the term BCP47 instead of RFC5646

### ISSUE THREAD

**Issue by eroux** [IIIF/api#1781]
RDF1.1 spec [specifies](https://www.w3.org/TR/rdf11-concepts/#h3_section-Graph-Literal) that the lang tags must be well formed according to [BCP47](https://tools.ietf.org/html/bcp47)

IIIF Presentation API 2.1.1 and 3.0 refer in 4.3 ([2.1.1](https://iiif.io/api/presentation/2.1/#language-of-property-values), [3.0](https://iiif.io/api/presentation/3.0/#43-language-of-property-values)) to [RFC5646](https://tools.ietf.org/html/rfc5646)

It's a bit cosmetic, but I think it would avoid a little bit of confusion (at least it would have on my side) if IIIF was referring to BCP47. I don't think it has any concrete consequence (BCP47 includes RFC5646), it's just a choice of words...

what do you think?

**Comment by zimeon** [comment]
I'll admit to not being well up on the status of BCP's as opposed to RFC's but from a little digging and following @eroux's links it makes sense to me to cite BCP47. 

I note that this affects (in some abstract sense) the Image API spec too. However, no change is necessary because the Image API spec just refers to the Presentation API spec, rather than to the RFC.

**Comment by azaroth42** [comment]
Agreement on 2019-02-27 call to make the change, and that it's editorial only.

**Comment by sdellis** [comment]
I think it would be a lot simpler to advise people to use the [IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), which the W3C identifies as [best practice](https://www.w3.org/International/geo/html-tech/tech-lang.html#ri20030112.224623362) and is referenced in BCP47. This is the format that is most useful to screen readers as well.

**Comment by eroux** [comment]
I disagree: bcp47 also allows tags in the Unicode registry (which consists of tags for transliteration) and there are many legitimate cases where one must use tags outside of the IANA registry... plus advertising something else than what json-ld advertises will probably be more confusing than helping... adding a link to the registry is not a bad idea, but I think the bcp47 requirement is more important
