### ISSUE TITLE
'w,h' as canonical size param vs. compliance level requirements

### ISSUE THREAD

**Issue by lutzhelm** [IIIF/api#1785]
Version 3 will have `w,h`as the canonical size URI parameter syntax, but arbitrary `w,h` requests are only required for level 2 compliance. So at level 1, servers are able to serve tiles proportionally scaled to an arbitrary width or arbitrary height, but if clients want to use that feature, they can't use the canonical URI syntax. So if clients want to request tiles via canonical URIs, they can only request them for the listed `tiles` / `scalefactors`. If no `tiles` are given in the info.json, requests for tiles to level 1 services can't be done in canonical form. Same applies to `sizes`.

On the other hand, having `w,h` required for level 1 would require those image servers to also serve non proportionally scaled images.

**Comment by lutzhelm** [comment]
See also #301

**Comment by tomcrane** [comment]
For clarity, this issue refers to this table in the compliance level document:

https://preview.iiif.io/api/image-prezi-rc2/api/image/3.0/compliance/#32-size

The suggestion is that this table is wrong, and that _REQUIRED_ should be for the now-canonical `w,h` form, and not for the `w,` and `,h` forms.

**Comment by jpstroop** [comment]
I feel like we did discuss this at some point, but we must have lost the thread, unless I'm remembering all the way back to the issues @lutzhelm references [above](https://github.com/IIIF/api/issues/1785#issuecomment-470024974), which seems unlikely. I can't think of a reason why @tomcrane's solution isn't the best way to correct for this.

**Comment by zimeon** [comment]
If we add _REQUIRED_ for `w,h`, I don't see any reason not to leave _REQUIRED_ also for `w,` and `,h`. Implementation would likely just translate a `w,` or `,h` to a `w,h` internally so it places no additional burden regarding image manipulation. Leaving those as required is less churn from v2 too.

However, as @lutzhelm points out, making `w,h` _REQUIRED_ does imply distorting scaling at level 1. Following on from https://github.com/IIIF/api/issues/879 discussion, I don't really think this is an issue. Do we know of a case where it would be?

**Comment by zimeon** [comment]
Editors agree that we need to add `w,h` as REQUIRED at level1, also leave `w,` and `,h` as REQUIRED -- change to https://preview.iiif.io/api/image-prezi-rc2/api/image/3.0/compliance/#32-size

**Comment by zimeon** [comment]
IIIF/trc#18 approved, we can move ahead with merging #1799
