### ISSUE TITLE
Remove logo and attribution/requiredStatement from Image 3

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1787]
Given the (now TRC approved) change to Presentation API to add a provider structure around the logo and other information about the organizations and/or people that should be attributed as providers of the information, there was a discussion about whether that should be done or not.  The result of the discussion on the community calls was that everyone believed that it would be too much of a stretch for the Image API to deal with this, and it would remain unimplemented.

A call for input was sent to iiif-discuss to solicit opinions if there was disagreement, and no-one responded.

Thus this issue is to remove logo and requiredStatement from the info.json of the Image API v 3.0 and instead recommend that the content be represented in the Presentation API, using the `provider` construct.

**Comment by zimeon** [comment]
Closed by merge of #1818 (which undid the revert of #1817 which reverted #1800)
