### ISSUE TITLE
What to do with multi-language strings?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1793]
Section 4.4, the language of property values, says about each entry in the array of the language map ...
> ... where each item is the content in the given language.

This does not include the situation where a single string contains multiple languages.  For some situations there is a dominant language with a few foreign words, and in others there could be equal usage.

For the dominant language with a few words (that might still be tagged as such in HTML <span>s), I think these should be recorded once against the dominant language.

```
{
"en": ["<span>The <span lang="fr">raison d'etre</span> for this thing is bla bla bla more words in english here.</span>"]
}
```

However for situations where there are multiple, approximately equal languages, the string should be recorded in all of the languages.

```
{
"en": ["<span><span lang="en">As they say</span>, <span lang="fr">c'est la vie</span></span>"]
"fr": ["<span><span lang="en">As they say</span>, <span lang="fr">c'est la vie</span></span>"]
}
```

The rationale being that both the English speaking and the French speaking users should see the same string, and our internationalization patterns depend on the language map keys.

/ht https://github.com/w3c/json-ld-syntax/issues/105

**Comment by tomcrane** [comment]
{
"en": ["cul-de-sac"]
"fr": ["impasse"]
}

**Comment by azaroth42** [comment]
Editors agree: It's a real problem, but outside of our scope to solve, and while we know of this issue in other situations, no IIIF manifest publisher has asked for a solution to this problem. We believe that it's a clarification when needed, not a breaking change, and thus `defer` until 3.1 or later

**Comment by jpstroop** [comment]
Same problem comes up w/ language tags for accessibility in library catalogs with transcribed titles.

**Comment by nichtich** [comment]
ISO 639 2 includes language code `mul` for multiple languages. Instead of inventing a custom solution, just mention the existing standard for language tags of multiple language strings:

~~~
"mul": ["As they say, c'est la vie"]
~~~
