### ISSUE TITLE
Describe mapping of JSON-LD keywords to avoid @ signs?

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1819]
From #1805 discussion. 

I think the places where `@type` and `@id` are currently mentioned are not the right places to mention `@none`.

We could add a short "4.7 Keyword Mappings" along the lines of:

> The JSON-LD keywords `@id`, `@type` and `@none` are mapped to `id`, `type` and `none` by the Presentation API linked data context. Thus in Presentation API 3 content the only JSON key beginning with `@` will be `@context`. However, the content may include data conforming to older specifications or external specifications that use keywords beginning with `@`.

**Comment by azaroth42** [comment]
I don't think it's necessary, but not averse to it if others think it would be useful.

**Comment by tomcrane** [comment]
I think this would be useful, especially 

> However, the content may include data conforming to older specifications or external specifications that use keywords beginning with @.

...which otherwise may be the source of much confusion.

**Comment by zimeon** [comment]
I think I'm a weak :+1: on including something, I think this kind of thing will be a source of confusion so it is helpful to add explanation

**Comment by mikeapp** [comment]
👍
