### ISSUE TITLE
Do we need version specific Prezi class aliases?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1820]
In the Image API, we can link to Presentation API resources that the image is `part_of`. Following the patterns, there _MUST_ be a `type`.  However, what should that type be?

Given that new major versions have new ontologies, `Manifest` in Image3 context currently refers to a version 3 Manifest. So how does an Image 3 image say that it is part of a Presentation 2 Manifest? Does it need to be clear about the version at all, or is "Manifest" sufficient?

**Comment by tomcrane** [comment]
Although it's technically going to be `http://iiif.io/api/presentation/3#Manifest`, what does it mean for the thing at the other end of an `id` from the image API to turn out to be a v2 Manifest?  Would that have any real world consequences for any consuming system? Is it even wrong? Does the `type` of the actual manifest override the asserted `type`?

**Comment by zimeon** [comment]
An unversioned term might be <http://iiif.io/api/presentation/3#Manifest> which will then resolve to the current spec

**Comment by azaroth42** [comment]
Eds agree ... close wontfix. The cure is worse than the symptoms.
