### ISSUE TITLE
Update Presentation API 3.0 Changelog

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1831]
Leave open until TRC issues are approved and included in change-log.

**Comment by zimeon** [comment]
#1832 was a step toward this

**Comment by zimeon** [comment]
Keeping this issue but moving forward to RC3 (hopefully final)

**Comment by zimeon** [comment]
We think these are now up to date but need a review. @azaroth42 and @zimeon will review

**Comment by zimeon** [comment]
We did review and looks good
