### ISSUE TITLE
Description of thumbnail & logo implies type is not mandatory

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1835]
Both thumbnail and logo say: ... where each item ... SHOULD have at least one of the `type` and `format` properties.
It MUST have the `type` property!

I think this is a holdover from previous spec text. Debatable if this is normative (rfc SHOULD) or editorial ... tagging as normative for now.

**Comment by tomcrane** [comment]
Not sure where that comes from, it's not in 2.1 like that, and earlier discussion is clear about `type` from the start, e.g.,, https://github.com/IIIF/api/issues/1147#issuecomment-309120923

Anyway, agree that it should be a _SHOULD_ for format, but need it mention the MUSTness of type at all? `provider` doesn't, for example. It's covered by the section on `type` itself.

**Comment by azaroth42** [comment]
Editors agree MUST for type. Better to (consistently) repeat the requirement.

Take to TRC as a normative fix, and should be an easy one.

**Comment by zimeon** [comment]
Approved by TRC in IIIF/trc#27
