### ISSUE TITLE
Bad `label` in example in Presentation 5.1

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1840]
From Andy Irving: there is a badly formatted `label` in https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#51-collection

```
   "label": { "en": "Example Manifest 1" },
```

**Comment by zimeon** [comment]
While we are at it: https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#42-resource-representations

```
      "label": "Example Book (pdf)",
```

and https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#58-annotation-collection

```
  "label": [ "Diplomatic Transcription" ],
```

**Comment by azaroth42** [comment]
The 5.8 label is currently correct, it just looks like an error. This is issue #1834 ... and evidence towards that we should fix it.
