### ISSUE TITLE
seeAlso for collections?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1856]
At the conference, @zimeon asked if the number of requests required to index a large IIIF collection is setting us up for a scalability problem. What if `seeAlso` could be used on collections as well and (perhaps) returned a structure like:

```json
{
  "https://example.org/1/manifest" : { "structured" : "descriptive metadata"},
  "https://example.org/2/manifest" : { "structured" : "descriptive metadata"},
  "https://example.org/3/manifest" : { "structured" : "descriptive metadata"}
}
```
making it possible to grab all of the metadata for a collection in one call? 

I suppose even:

```json
{
  "https://example.org/1/manifest" : "https://example.org/1/my_metadata.xml",
  "https://example.org/2/manifest" : "https://example.org/2/my_metadata.xml",
  "https://example.org/3/manifest" : "https://example.org/3/my_metadata.xml"
}
```

Would be helpful in a slightly different way, in that one could at least get all of the metadata independently from the manifests. This starts to brush closely (maybe too closely) against what we're doing with Activity Streams for harvesting.

Not arguing for or against yet, just thinking through the use case.

**Comment by azaroth42** [comment]
:-1:

Too closely, IMO. 
Also - the number of bytes of metadata is trivial compared to the number of bytes of pixels. 
Fearing the network for a network oriented index of resources is fruitless.

The scalability issue is real ... and not solved by trying to reduce the number of requests, but by being more explicit about when those requests are necessary to take place at all. (e.g. discovery api)

**Comment by jpstroop** [comment]
>Too closely, IMO.
Yeah. Might at least be interesting to think about how to link to a discovery/sync service from a collection. "I found this collection; how do I keep track of changes?"

**Comment by zimeon** [comment]
My question wasn't aimed at the factor of 2 that comes from the need to make both manifest and `seeAlso` requests.  As Petr Knoth (CORE, UK) has commented at OR2019 and other places, there are real issues with harvesting resource-by-resource. From an abstract point of view we typically cite HTTP/2 as a way around latency with many requests. However, transport latency may not be the limiting factor as many systems we produce are not very fast at responding, or get overloaded with rapid requests. With only 86400 seconds in a day harvests of millions of resources can quickly become burdensome. Properly managed change lists help with updates (often infrequent in our space) but I still wonder about  packaged responses (ala Dumps in ResourceSync). I'm not sure there is a good opportunity to deal with this in IIIF specs at the moment ... but I wonder about this issue.

**Comment by jpstroop** [comment]
Happy to close, or leave this as a spot for discussion?

**Comment by tomcrane** [comment]
(Many collections will have descriptive metadata `seeAlso` already, e.g., because the IIIF Collection represents an archival series, or a three vol book.)

If someone wants to add another seeAlso to a collection that exists for the purposes of aggregation, that links to a dump of metadata for all the manifests in the collection, they can do that and mint a profile for it, without the specs having to have an opinion about it any time soon.

```
  "seeAlso": [
        {
          "id": "https://example.org/collections/a",
          "type": "Dataset",
          "format": "application/ld+json",
          "profile": "https://extensions.org/dmd-dump"
        }
   ]
```

Almost by definition, because it's an aggregation of descriptive metadata, the IIIF spec would have nothing to say about what any Dataset conforming to that profile would look like, so we can see if this technique just emerges.

**Comment by zimeon** [comment]
@tomcrane - yes, maybe that is the right way to think about it. We keep everything clean and resource focused but understand that we could have an "aggregated descriptive metadata for all items in this collection" profile used within `seeAlso` for a Collection. The same pattern could be applied to an [Ordered Collection Page][https://iiif.io/api/discovery/0.3/#orderedcollection] in the change discovery API.

**Comment by azaroth42** [comment]
Propose close?

**Comment by zimeon** [comment]
Agree, close. Can be addressed through extension if there is interest, per https://github.com/IIIF/api/issues/1856#issuecomment-506693737
