### ISSUE TITLE
Faulty 'preferredFormats' in complete response example

### ISSUE THREAD

**Issue by lutzhelm** [IIIF/api#1861]
The [Complete Response](https://iiif.io/api/image/3.0/#59-complete-response) example has `png` and `gif` as `preferredFormats`, but at level 1 and with the `extraFormats` `gif` and `pdf` only `jpg`, `gif` and `pdf` are supported.

The description for `preferredFormats` states:

> The format parameter values listed must be among those specified in the referenced profile or listed in the `extraFormats` property.

Furthermore, should the "must" in that description be marked as a RFC 2119 keyword? If so, that would be an additional issue.

**Comment by azaroth42** [comment]
:+1:

Agree this is a bug in the example, good catch!

Also agree that the "must" in https://iiif.io/api/image/3.0/#55-preferred-formats should be a normative _MUST_.

**Comment by zimeon** [comment]
Fixed by #1895
