### ISSUE TITLE
Add @context change to 3.0 image change log 

### ISSUE THREAD

**Issue by glenrobson** [IIIF/api#1864]
Just looking through the change-log and can't see the `@context` change from `http://iiif.io/api/image/2/context.json` to `http://iiif.io/api/image/3/context.json` in:

https://iiif.io/api/image/3.0/change-log/

**Comment by azaroth42** [comment]
Agree, and doubtless the same in Presentation's change log too.

**Comment by azaroth42** [comment]
Closed by #1907
