### ISSUE TITLE
Mention of protocol requirements being summarized in Appendix A is obsolete

### ISSUE THREAD

**Issue by regisrob** [IIIF/api#1866]
Section "6.3. Responses" of P-API 3.0 still refers to requirements regarding the dereferencibility of resources, even though the "Protocol Behavior" table has been removed (see #1618):

> The different requirements for which resources must provide a response is summarized in Appendix A.

I may have not seen it, but it seems there is no mention of such requirements in Appendix A at all anymore...

So the first paragraph of 6.3. should be reviewed a little bit to reflect that... Maybe we should just keep the last sentence "While some resources do not require their URI to provide the description, it is good practice if possible", if this is desirable.

**Comment by azaroth42** [comment]
Good catch!  Agree we should remove that text.

**Comment by azaroth42** [comment]
For later reference: #1618 is where the table was removed.

**Comment by azaroth42** [comment]
Closed by 1885
