### ISSUE TITLE
Should type be mandatory for tiles and sizes in Image API 3.0?

### ISSUE THREAD

**Issue by glenrobson** [IIIF/api#1867]
The 3.0 change log says:

"1.2.4. Require the type property on all resources, with new values

The type property with a single value is now required on all resources, including content resources and services. This serves several purposes, including facilitating object mapping code libraries, and forcing the serialization to generate a JSON object for the resource, not just a string with the resource’s URI. The values for type have been changed to version-specific strings that avoid the namespace structure, for example from iiif:Image in 2.1 to ImageService3 in 3.0. Note that the @type property is used only when referring to object from older specifications such as the Authentication API 1.0." 

https://iiif.io/api/image/3.0/change-log/#124-require-the-type-property-on-all-resources-with-new-values 

But type on tiles and sizes is optional.

**Comment by azaroth42** [comment]
Agree we should be clearer in the changelogs that not /absolutely/ every resource needs to have it, as tiles and sizes don't need them.

**Comment by azaroth42** [comment]
Editorial to do in changelog: Editors agree be specific about which types are required, not including features, sizes, or tiles.

**Comment by azaroth42** [comment]
Closed by #1906
