### ISSUE TITLE
Inconsistency with requiring id and type in image service

### ISSUE THREAD

**Issue by glenrobson** [IIIF/api#1868]
In the `service` entry of the first table in the following:

https://iiif.io/api/image/3.0/#58-linking-properties

it says its ok to have `@id` or `@type` but in the second table it says `service` can only have `id` or `type`.

**Comment by azaroth42** [comment]
This is the weirdness of crossing between v2 and v3 :(
Agree it should be clearer, per https://iiif.io/api/presentation/3.0/#service

**Comment by zimeon** [comment]
Fixed by #1901
