### ISSUE TITLE
Show type on service annex and give type for Auth as an example

### ISSUE THREAD

**Issue by glenrobson** [IIIF/api#1869]
In the linking properties the table says that a service must have a `type` or `@type` from:

https://iiif.io/api/image/3.0/#58-linking-properties

and links to the Service Registry:

https://iiif.io/api/annex/services/

but most of these examples don't have a type. The text also mentions this service could be used to link to an authentication service but a type is present in the auth spec and auth isn't in the annex services document.

**Comment by azaroth42** [comment]
GeoJSON and Physical Dimensions won't be services any more in v3, per #1358.  That leaves Auth (which we need to update to be aligned with 3.0) and Image, which is documented in Presentation API 3.0 for the backwards versions. We should link from Image to the `service` description as well as the list of `types`.

**Comment by azaroth42** [comment]
Editorial to do: Add example of Auth Service to example in section 5.8

**Comment by azaroth42** [comment]
Closed by #1905
