### ISSUE TITLE
relative link in iiif-presentation-3 webpage

### ISSUE THREAD

**Issue by OyvindLGjesdal** [IIIF/api#1872]
> see the **terminology** section for an explanation of “embedded”

https://iiif.io/api/presentation/3.0/#13-terminology  ->  https://iiif.io/api/presentation/3.0/#12-terminology

**Comment by azaroth42** [comment]
:+1: Probably from the kramdown change to the section heading link syntax, combined with moving content around.

Thanks for reporting!
