### ISSUE TITLE
Use JSON-LD 1.1 @included for services

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1873]
*Background:*

In version 2.x, feedback about attaching services to the object(s) that the service relates to was that this was painful to use, as only the first occurrence of a service was included in full -- other occurrences simply have the URI, and the client is expected to search through the entire document to find the previous reference.

This feedback was taken to the JSON-LD 1.1 Working Group in the W3C, and made it into the specification (though only just, it was the last issue to be resolved). The solution adopted is to allow a key at the root of the document tree called `@included`. This is described in the [latest draft spec](https://www.w3.org/TR/json-ld11/#included-nodes), but is an array of nodes.

*Issue:*

It's hard to find shared nodes in the document, such as Authentication services. They should be somewhere convenient for implementers.

*Proposal:*

Replace the current `service` pattern with the `@included` pattern, such that all services are described in full in the `@included` property (which can be aliased to get rid of the `@`), and all references to them are only by URI.

*Issue:*

There is a significant issue with this approach though.  The `service` property is used for all services, and the most common one is likely to be the IIIF Image API being referenced from the Presentation API. It makes no sense to take all of the Image API services out, along with the Auth services. I don't think we can use scoped contexts, as the same image might have both auth and image API services (or any other service). We could have a `shared` property that just references included things ... but then you need to look in two places on the resource ... `service` and `shared`.

Thoughts?

**Comment by azaroth42** [comment]
The issue was resolved in JSON-LD for expansion, which is all we care about.  You can have both embedded and included links in the same property :)

**Comment by tomcrane** [comment]
This sounds solved then.

Auth service in one place referenced by URI, separate image service per image resource as now, everyone's happy.

**Comment by azaroth42** [comment]
@azaroth42 to create example JSON to demonstrate before Oct 25.
Need to discuss when/if the pattern is required (and the various edge-y cases).
Discuss with community in Ann Arbor on Thursday morning.
Take to TRC for discussion November 13th.

**Comment by azaroth42** [comment]
Example that expands and flattens in @gkellogg's [distiller](http://rdf.greggkellogg.net/distiller?command=flatten&format=jsonld&output_format=jsonld) as expected:

```
{
	"@context": {
	  "eg": "https://example.org/",
	  "id": "@id",
	  "type": "@type",
	  "includes": "@included",
	  "items": "eg:items",
	  "service": "eg:service",
	  "body": "eg:body"
	},
	"id": "a",
	"type": "Manifest",
	"items": [
		{
			"id": "b",
			"type": "Canvas",
			"items": [
				{
					"id": "c",
					"type": "AnnotationPage",
					"items": [
						{
							"id": "d",
							"type": "Annotation",
							"body": {
								"id": "e",
								"type": "Image",
								"service": [
									{
										"id": "f",
										"type": "ImageService3",
										"service": [
											{
												"id": "https://auth.example.com/login",
												"type": "AuthCookieService"
											}
										]

									}
								]
							}
						}

					]
				}
			]
		}
	],
	"includes": [
		{
			"id": "https://auth.example.com/login",
			"type": "AuthCookieService",
			"profile": "http://iiif.io/api/auth/1/login",
			"...": "more details here"
		}
	]
}
```

**Comment by zimeon** [comment]
Seem to me that we should adopt this pattern as an option (_`services` with an `id` property MAY be described by a resource with that `id` value in a top-level `includes` block_) but RECOMMEND that the pattern be used only for repeated services descriptions such as auth.

**Comment by azaroth42** [comment]
Merged to branch after TRC approval, closing.
