### ISSUE TITLE
Clarify image API canonical URI

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1875]
The [canonical URI syntax](https://iiif.io/api/image/3.0/#47-canonical-uri-syntax) is documented with:

> Size and region parameters given as percentages and the rotation parameter allow positive floating point number values

but a canonical size can never be a percentage value.

**Comment by azaroth42** [comment]
Agreed. Clarification needed that this is a recommendation about use of the syntax generally, rather than about the canonical URI specification. Perhaps by separating into a separate sub-section.

**Comment by zimeon** [comment]
I agree that it is confusing to have this general information in the Canonical URI section. I think we should have a separate "Floating Point Values" section before the "Canonical URI Syntax" section.

**Comment by zimeon** [comment]
Fixed by #1899
