### ISSUE TITLE
Presentation 2.x: clarify format of metadata block values

### ISSUE THREAD

**Issue by scossu** [IIIF/api#1876]
The [2.1 specs](https://iiif.io/api/presentation/2.1/#repeated-properties) indicate: 

> Many of the properties in the API MAY be repeated. This is done by giving a list of values, using either of the representations described above, rather than a single string.

However, in regard to the [metadata block](https://iiif.io/api/presentation/2.1/#metadata), they say: 

> The value [in the metadata block] SHOULD be either simple HTML, including links and text markup, or plain text

This leads to the assumption that metadata values should not be lists. However, this contradicts the paragraph about repeated properties as well as some examples in the specs themselves, e.g. in [5.1](https://iiif.io/api/presentation/2.1/#manifest):

```
 "metadata": [
    [...]
    {"label": "Notes", "value": ["Text of note 1", "Text of note 2"]},
    {"label": "Source",
     "value": "<span>From: <a href=\"http://example.org/db/1.html\">Some Collection</a></span>"}
  ],
```
Can the specs be more explicit about the fact that the values in metadata block MAY be lists (if that is indeed the intention?

Maybe the SHOULD in 3.1 is referring to the format of possible individual values in a list?

**Comment by azaroth42** [comment]
This raises a process question of whether we expect to make editorial updates to 2.x versions after 3.x is released.

I (personally) think that the 1.x and 2.x era specs are frozen, warts such as this one and all, rather than documents to be improved.

**Comment by tomcrane** [comment]
I agree, I think - and do so for this case. 
I'm trying to imagine what would happen if we spotted something obviously and fundamentally wrong - unlikely, and it would have to be pretty big. And in that hypothetical case it should probably be a red warning box, rather than a transparent edit that you'd have to do a bit of work in version history to understand.

**Comment by scossu** [comment]
I generally agree, especially for minor issues as this one. For more severe issues, it may be more complex. 

Is there a life cycle policy for the specs? I find it reasonable to consider 2.x as a "stable" but not "deprecated" or "frozen" version, i.e. there are no new features added but non-breaking edits for major/critical issues are possible (in this my opinion diverges slightly from @tomcrane 's). I understand that this may create additional work for the editors but it seems like more transparent communication. 

If there is no official life cycle and deprecation policy and we thnk that one is needed, I would be glad to contribute to the discussion (and take it out of this specific ticket).

**Comment by azaroth42** [comment]
Propose to close this issue in favor of a new one to discuss the life cycle question: https://github.com/IIIF/api/issues/1888

**Comment by azaroth42** [comment]
This is clear in 3.0, as the value is a language map. https://iiif.io/api/presentation/3.0/#metadata
Process issue remains open.

Closing, on editor's call of 2020-05-13
