### ISSUE TITLE
3.0 label collision with auth cookie service?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1880]
The `label` property of the Auth 1.0 service description is required: https://iiif.io/api/auth/1.0/#service-description 
And is a raw string, not internationalized like 3.0 labels with a language map.

Have we considered this collision when referencing 1.0 Auth services from within a 3.0 Manifest?

I think the context will work as expected -- label in the `AuthCookieService1` resource will be overridden by the auth 1.0 context.  Given that it's *required*, we might want to do a little more due diligence though

**Comment by azaroth42** [comment]
Verify that this works as expected before release.

**Comment by tomcrane** [comment]
https://tinyurl.com/yajl5vdt works
