### ISSUE TITLE
Presentation Context in Image response example

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1892]
The second example in [section 5.8](https://iiif.io/api/image/3.0/#58-linking-properties) has the Presentation API context.

The requirement is not expressed in the prose of the specification.  Either this is a bug in the example (because the Image API context has all the necessary terms) or a bug in the spec and should be explained as a requirement (because the terms are not in the Image context).

**Comment by zimeon** [comment]
I think it is a bug in the example and should be removed.

I don't like the idea of a rule on any property mentioned in the image spec that _"If you include this property then you must add the Presentation API `@context`..."_.

**Comment by azaroth42** [comment]
Editors agree that this is a bug in the example, should remove presentation context.

**Comment by zimeon** [comment]
Addressed by #1904
