### ISSUE TITLE
What do maxArea, maxWidth, maxHeight refer to?

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1897]
From the specification it's not fully clear whether `maxArea`, `maxWidth`, and `maxHeight` refer to the region or to the final image dimensions. These numbers can differ when an image is rotated, e.g. the response image to request `^max/45` will have twice the image size as `^max`. Checking the constraint against final image [requires some trigonometry](https://stackoverflow.com/a/622172/373710) that may be not obvious to some implementers.

**Comment by zimeon** [comment]
Per https://iiif.io/api/image/3.0/#4-image-requests:

> ... the requested image content is first extracted as a region of the full image, then scaled to the requested size, mirrored and/or rotated, and finally transformed into the requested color quality and format.

and then in definition of `^max` in https://iiif.io/api/image/3.0/#42-size:

> The extracted region is scaled to the maximum size permitted by `maxWidth`, `maxHeight`, or `maxArea`

and then in https://iiif.io/api/image/3.0/#43-rotation:

> In most cases, rotation will change the width and height dimensions of the returned image. The service _SHOULD_ return an image that contains all of the image contents requested in the region and size parameters, even if the dimensions of the returned image file are different than specified in the size parameter.

so I think it is expected and the size of the returned image may be larger (up to twice the number of pixels for a square region rotated 45deg as you point out) than the extracted image from the `/size/` step of the transform. This order avoids the need for any trigonometry to check the `maxWidth` etc. constraints.

**Comment by azaroth42** [comment]
Editors agree that that the question is answered, and the text in the spec is clear enough.
Closing.
