### ISSUE TITLE
Allow downscaling oversized images in Image API?

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1909]
The [IIIF Image API 3.0 specification](https://iiif.io/api/image/3.0/) tells on `max`:

> The resulting image will have the pixel dimensions of the extracted region, unless it is constrained to a smaller size by maxWidth, maxHeight, or maxArea as defined in the Technical Properties section.

The spec says:

> Clients MUST NOT expect requests with a height greater than this value to be supported

so are server expected to return an error for request `imageid/full/max/0/default.png` if image `imageid` is larger than `maxWidth`, `maxHeight` and/or `maxArea`? Or should the image better be downscaled to the maximum size? 

Given there are "small images" (smaller than maxWidth, maxHeight, maxArea) and "large images" (larger than allowed to be served directly):

* `^max` will upscale on small images and downscale on large images
* `max` will server in best resolution on small images and return error on large images

So clients interested in the best resolution (no scaling) have to compare image size and maximum dimensions and build different requests for small images and for large images.

**Comment by azaroth42** [comment]
A request for `full/max` will retrieve the largest allowed size, for the full region of the image. There is no ambiguity here.

`^max` is also clearly defined:

> The extracted region is scaled to the maximum size permitted by maxWidth, maxHeight, or maxArea as defined in the Technical Properties section. If the resulting dimensions are greater than the pixel width and height of the extracted region, the extracted region is upscaled.

If you set your maxHeight to be greater than the image's height, then asking for `max` will return the image's height, and asking for `^max` will return the content upscaled to the maxWidth height.

**Comment by nichtich** [comment]
> A request for `full/max` will retrieve the largest allowed size, for the full region of the image. There is no ambiguity here.

What if maxHeight is set *smaller* than the image's height? Will `full/max` return the image *downscaled* to maxHeight or will it return an error?

**Comment by azaroth42** [comment]
Yes, `full/max` will return the full region of the image, downscaled to max height.
