### ISSUE TITLE
Request directives needs clarification

### ISSUE THREAD

**Issue by ahankinson** [IIIF/api#1918]
In the v3 spec, section 6.2 it says:

"Clients must not attempt to construct resource URIs by themselves, instead they must follow links from within retrieved descriptions or elsewhere."

I think this needs further clarification. IIIF viewers must, by necessity, take image IDs such as `"id": "https://example.org/iiif/book1/page1/full/max/0/default.jpg"` and construct derived URLs for the purposes of making tiling work. Any tiling-capable viewer needs to remove the `full` and `max` parameters and rewrite the URL with specific tile sizes, which seems to fall foul of the guidance given here.

A note clarifying request behaviours for clients' dynamically-generated Image API requests would be helpful, particularly since there is now a requirement that the `id` of the Image can no longer simply be a request for the Image service, and it must be a full URL to an image (section 5.7).

**Comment by azaroth42** [comment]
The intent is must not create *Presentation API* URIs by themselves, as it's in the presentation api documentation. But yes, reading API as _any_ API is clearly wrong.

**Comment by ahankinson** [comment]
I think my confusion comes from the term "resource URIs," since images are referred to as "[Content Resources](https://iiif.io/api/presentation/3.0/#57-content-resources)", so image URIs could reasonably be interpreted as "(Content) Resource URIs"

(I am still concerned about what the correct behaviour is for `@id` on image Annotation `body`, since you have to provide a full URL to an image that would be manipulated and dynamically constructed by IIIF clients, but perhaps that's a separate question?)

**Comment by zimeon** [comment]
Closed by #1942
