### ISSUE TITLE
highlight subcollection

### ISSUE THREAD

**Issue by eroux** [IIIF/api#1921]
This is a proposal for a new "highlight" property in the presentation API. It would be in some way an equivalent of `start` but for items in a collection. Basically the goal is to present a collection in the context of a greater collection. To give a visual example, I currently have my main collection displayed like this:

![Capture d’écran de 2020-02-09 11-29-55](https://user-images.githubusercontent.com/60868/74100614-6187ec80-4b31-11ea-8f87-321d05d5e081.png)

what would be very useful for our users is instead having the same collection but with a sub collection highlighted, which would give the following display:

![Capture d’écran de 2020-02-09 11-30-41](https://user-images.githubusercontent.com/60868/74100625-7f555180-4b31-11ea-96e4-98dcb3293acf.png)

**Edit:** The same mechanism could be applied to ranges: a manifest could be open at a certain range, or even a certain image within a certain range.

**Comment by eroux** [comment]
I'm not sure how redundant it is with the [content state API](https://iiif.io/api/content-state/0.2/), it may be a duplicate

**Comment by azaroth42** [comment]
This might be accomplished via the content state API, but you couldn't guarantee the UI implementation would in fact highlight the entry.
Start for collections was discussed in #1761 and deferred based on your same observation that content state might accomplish the goal, and there wasn't any implementations chomping at the bit for this. I think these are related, but perhaps worth considering separately.

However either way, we can't add new features to 3.0 at this stage so I've tagged as defer.

**Comment by eroux** [comment]
sure, thanks!

**Comment by azaroth42** [comment]
The highlight aspect is viewer dependent, but selection of the sub-collection (or other aspect) can now be done in content state. Closing.
