### ISSUE TITLE
clarification on "if applicable"

### ISSUE THREAD

**Issue by eroux** [IIIF/api#1922]
The [Image API 3.0 compliance level spec](https://iiif.io/api/image/3.0/compliance/#34-quality) has a puzzling and unexplained wording in section `3.4 Quality`, where `color` and `gray` at `level 2` are `required (if applicable)`. What does this mean? Who determines if it's applicable and how is communicated? In other words: if I have a client that fetches an image info and sees that it is compliant with `level 2`, how does it determine if `gray` or `color` are `applicable`?

related to https://github.com/IIIF/api/issues/1920

**Edit:** I suspect this means "if `color` / `gray` are listed in `extraQualities`"? But in that case that makes the info redundant, and the `quality` section of the compliance level useless

**Comment by jpstroop** [comment]
"If applicable" is there because if the source image data is only grayscale, then you can't support `color`, and, similary, if the source image data is only bitonal, then you can't support `gray`.

**Comment by eroux** [comment]
ok yes, I think that should be indicated in the spec (that it's a decision the server makes based on the source image data)

**Comment by eroux** [comment]
just to be clear: the reason why I think it should be clarified is that if I have a bitonal source image, our server can create a version on the image in 3 8-bit channels, the question is: should the server consider "color" and "grayscale" applicable then? 

It's not quite clear in the spec itself, for instance for the "color" quality, the spec says "The image is returned with all of its color information.". For bitonal images, bitonal is in fact "all of its color information" so it also conforms to "color", so it seems applicable...

**Comment by azaroth42** [comment]
This is related to https://github.com/IIIF/trc/issues/25 (FWIW)

**Comment by zimeon** [comment]
See related https://github.com/IIIF/trc/issues/25

**Comment by azaroth42** [comment]
Closed by #1943 :)

**Comment by eroux** [comment]
thanks!
