### ISSUE TITLE
Mappings between JSON-LD context and RDF vocs - and documentation

### ISSUE THREAD

**Issue by aisaac** [IIIF/api#1923]
I'm wondering where changes in the mappings between context and RDF vocabularies between v2 and v3 have been documented. I.e. `profile` is now `dcterms:conformsTo` instead of `doap:implements`, `protocol` is now `dcterms:type` instead of `dcterms:conformsTo` and `service` is `schema:potentialAction` instead of `svcs:has_service`. Maybe there are others?

Why the last one, by the way? This doesn't feel right at first sight. In https://github.com/IIIF/api/pull/1722 I didn't find a reference to this property. The type `Service` is mapped to `schema:WebAPI`, which is not really a `schema:Action`. Or am I misreading the JSON in the context files? Well, having this documented in the change log may fix my wrong interpretation then ;-)

**Comment by azaroth42** [comment]
They're not documented, because the context files aren't part of the normative specification.

I think this is a process issue that should be discussed and resolved - documentation of the ontology and profile for the predicates. Probably in /annex/ ?

**Comment by aisaac** [comment]
An annex would sound good!

**Comment by azaroth42** [comment]
Editors agree - not going to document non-semantically-versioned changes as there's nowhere useful to put them, and the number of people who would use that document is likely under 5.
