### ISSUE TITLE
Language tag for unknown an non-linguistic content

### ISSUE THREAD

**Issue by nichtich** [IIIF/api#1927]
ISO 639-2 includes special language tags `und` for unknown and `zxx` for non-linguistic content. See also https://www.w3.org/International/questions/qa-no-language. IIIF should better recommend to use this tags instead of `none`.

**Comment by azaroth42** [comment]
No, then they're `rdf:langString`s with a language which is already permitted - just put them into the language map. This is the case when they're `xsd:string`s without _any_ language.
