### ISSUE TITLE
missing OA aliases in IIIF prezi v3 context

### ISSUE THREAD

**Issue by eroux** [IIIF/api#1929]
Looking at [this example](https://iiif.io/api/presentation/3.0/#57-content-resources) from the spec:

```json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://example.org/iiif/book1/annotation/p0001-image",
  "type": "Annotation",
  "motivation": "painting",
  "body": {
    "id": "https://example.org/iiif/book1/page1/full/max/0/default.jpg",
    "type": "Image",
    "label": { "en": [ "Page 1" ], "es": [ "Página 1" ] },
    "format": "image/jpeg",
    "service": [
      {
        "id": "https://example.org/iiif/book1/page1",
        "type": "ImageService3",
        "profile": "level2"
      }
    ],
    "height": 2000,
    "width": 1500
  },
  "target": "https://example.org/iiif/book1/canvas/p1"
}
```

I think this json-ld is invalid, and it actually makes the [json-ld playground](https://json-ld.org/playground/) hang. The main problem I see is that `"body"` is actually undefined in the [context](http://iiif.io/api/presentation/3/context.json). Note that it would work if it was replaced with `"oa:body"`, but if you want `"body"` to work, there needs to be an alias in the context for it. This is true of all the other web annotation properties.

**Comment by azaroth42** [comment]
That's a bug in the JSON-LD playground.

The OA context is scoped in for the Annotation related types, in order to then override the `label` property to use a language map rather than be just a string.

**Comment by eroux** [comment]
I'm sorry, I don't understand what you mean by 

> The OA context is scoped in for the Annotation related types,

?

**Comment by azaroth42** [comment]
Line 99 of the context ...

```
    "Annotation": {
      "@id": "oa:Annotation",
      "@context": [
        "http://www.w3.org/ns/anno.jsonld",
        {
          "label": {
            "@id": "rdfs:label",
            "@container": ["@language", "@set"],
            "@context": {
              "none": "@none"
            }
          }          
        }
      ]
    },
```

This embeds the Annotation context within any reference to an Annotation, via `@type`.

See:  https://www.w3.org/TR/json-ld11/#scoped-contexts and especially example 46: https://www.w3.org/TR/json-ld11/#example-46-defining-an-context-within-a-term-definition-used-on-type

**Comment by eroux** [comment]
Ah ok thanks!
