### ISSUE TITLE
start requires id, but example doesn't have one

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1930]
@ksclarke via Slack:
> In the v3 presentation spec the `start` section says: "The value must be a JSON object, which must have the `id` and `type` properties." The example below of the Canvas start has both but the Specific Resource example only has a type (no id property). Am I reading `id` too literally (and the selector counts as an ID)? 

This should be considered for consistency ... I think that the text is correct, but the example should be fixed.  If so this is just a minor editorial tweak.

**Comment by tomcrane** [comment]
Agree that example should have `id`

**Comment by zimeon** [comment]
Closed by #1939
