### ISSUE TITLE
Language lists rights property and shouldn't

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1933]
>  it may also be used for resources referenced (see the terminology section for an explanation of “referenced”) from `homepage`, `rendering`, **`rights`,** and `partOf`.

Clearly `rights` cannot have a language as it's just a raw URI as a string. 

Thanks to Mark Matney on Slack for catching this!

**Comment by zimeon** [comment]
Closed by #1938 (though not automatically)
