### ISSUE TITLE
Should 'Rights' section allow Open Knowledge Foundation references to CC Zero license?

### ISSUE THREAD

**Issue by hadro** [IIIF/api#1962]
[Prezi 3.0 Rights section](https://iiif.io/api/presentation/3.0/#rights) states: 
"A string that identifies a license or rights statement that applies to the content of the resource, such as the JSON of a Manifest or the pixels of an image. The value must be drawn from the set of Creative Commons license URIs, the RightsStatements.org rights statement URIs, or those added via the extension mechanism. The inclusion of this property is informative, and for example could be used to display an icon representing the rights assertions."

The Natural History Museum in London is using CC Zero licenses, but using this URI as a rights value:
https://opendefinition.org/licenses/cc-zero/
(I discovered this when trying to see if their manifests validate in our 3.0 validator; it does, except for the issue under discussion here)

Example manifest here:
https://data.nhm.ac.uk/iiif/resource/8d76e3e4-bcef-48f3-a32c-b72e2b8b300b/record/386

Is this kind of reference of CC Zero statements something the spec should accommodate, or is this something that should be pushed back to publishers to address (which seems potentially less likely to happen...)?

**Comment by azaroth42** [comment]
No, in my opinion it should follow the spec and be the official CC Zero URI so that clients can process the URI as an identifier. If the intent is to have users view that particular representation of the license, then it can go in `metadata` or `requiredStatement` as HTML with a link.

**Comment by zimeon** [comment]
I agree that the `rights` value should be the CC Zero URI https://creativecommons.org/publicdomain/zero/1.0/

**Comment by kirschbombe** [comment]
I agree with Rob and Simeon that it should be the official CC URI

**Comment by mikeapp** [comment]
👍 for the official CC URI (but should it be `http` per IIIF/trc/issues/32 ?)

**Comment by azaroth42** [comment]
Propose close, wont-fix

**Comment by zimeon** [comment]
2022-02-02 Editors' meetings - agree, close wontfix
