### ISSUE TITLE
info.json for tiered access

### ISSUE THREAD

**Issue by scossu** [IIIF/api#1970]
[Auth 1.0](https://iiif.io/api/auth/1.0/#tiered-access) says: 

> If a server supports multiple tiers of access, then it must use a different identifier for each Description Resource and its corresponding Content Resource(s). For example, there must be different Image Information documents (/info.json) at different URIs for each tier. 

And: 

> When a Description Resource is requested and the user is not authorized to access it and there are lower tiers available, the server must issue a 302 (Found) HTTP status response to redirect to the Description Resource of a lower tier.

I am not clear on which parts of the info.json should reflect the restrictions imposed on the request, and how. I can see a few key parts that may or may not be affected: 

`width`, `height`: These could likely change to the maximum allowed dimensions. However, it seems like maintaining the ratio between the dimensions is important, so these two parameters should be calculated with that in mind. E.g. if a tier prescribes a maximum bounding box of 800x600, and the image is 4000x2000 pixels, the `width` and `height` values of he degraded image should be `800` and `400`, respectively.

`maxWidth`, `maxHeight`: these seem clearly related to server, not auth, limitations. The Image 3.0 specs says in this regard: 

> The maxWidth, maxHeight, and maxArea parameters provide a way for image servers to express limits on the sizes supported for the image. [...]
> Clients should not make requests that exceed size limits expressed.

`sizes`: I assume this would be the maximum available size for the current request, and all the tile sizes up to the closest one to the maximum allowed. 

`tiles`: it seems like this should change too, if the tile unit size is larger than the allowed size.

`extraQualities`: I am unsure if these are supposed to indicate a feature/limitation of the server, as for `maxWidth` and `maxHeight`, or an access-driven limitation. 

Anything else? 

Unless I am missing an obvious part of the documentation, I think it would be important to add some clarification on how  these individual properties relate to Auth restrictions, either in the Auth and or Image API documentation, or both.

**Comment by azaroth42** [comment]
The info.json should reflect what the capabilities available for requests on that particular image, if you have the credentials to access it. If you don't have the credentials, and there are lower tiers, then as you quoted, the server should redirect the client to the next lower tier, which would describe its capabilities or continue to redirect downwards.

**Comment by scossu** [comment]
@azaroth42 That is quite clear in the spec, however my doubt comes with parts of the info.json that may be driven by server capabilities. E.g. `maxWidth`, `maxHeight` are hard-coded in iipsrv to fixed values, so that seems logical to leave unchanged in lower tiers. `extraQualities` is less clear to me. I am wondering if the specs should have more explicit language about which values should be affected by access restrictions and ideally include examples of full-access and restricted-access description  resources.

**Comment by azaroth42** [comment]
I don't think it should be in the Image API specifications directly - there's no notion of a "server" in the specs, nor authentication, just URI patterns to access image content, and a service document (info.json) that describes the capabilities when interacting with that image content. 

For the Auth spec, it could be there, but one could imagine tiers where any of the features are either changed or stay the same compared to other use cases for tiered access. Perhaps degrading from color to greyscale is good in one situation, but if the base content is black and white, then that would be meaningless. Or perhaps one installation caches JPGs only, so restricting access to TIFF or PNG or JP2 based on authentication would be a way to keep the cache small. Or rotation is computationally expensive, so perhaps that requires authentication. Or the obvious one of image size. Or any permutation of these.

**Comment by azaroth42** [comment]
I think we can close this issue? Unless there's further questions, @scossu?

**Comment by scossu** [comment]
Yes. Thanks for the clarification.
