### ISSUE TITLE
Change api repo to use `main` branch

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1977]
I think the editors are all happy to do this whenever convenient but I assume we need to coordinate with @glenrobson to make sure we don't break the integrations to check and publish API content. This change will have no impact on the specs themselves so there is no need for TSG review

**Comment by glenrobson** [comment]
I've spoken to Josh, happy to look into this.  Ill test it first with the validators before trying on api and website to see the affects. The only worry currently is travis but it may be an easy fix...

Relevant info: https://github.com/github/renaming and https://docs.github.com/en/github/administering-a-repository/renaming-a-branch

**Comment by azaroth42** [comment]
Done, closing :)
