### ISSUE TITLE
Add warning to Auth API 1.0 re: browsers and third-party cookies

### ISSUE THREAD

**Issue by kirschbombe** [IIIF/api#1979]
Should we add a warning to the top of the Auth 1.0 spec that Chrome and other browsers will stop supporting third-party cookies, which will break the current auth workflow?

The Auth TSG mentions it here: https://iiif.io/community/groups/auth-tsg/, but a warning on the spec would be useful to alert those looking to adopt the Auth workflow.

**Comment by kirschbombe** [comment]
per @glenrobson "It would be useful to add something to say it does work in the first party use cases. Thats something I didn't pickup on until the last auth call."

**Comment by azaroth42** [comment]
Editors agree on 2021-03-25 call - useful to have a warning and pointer to ongoing work in the 1.0 spec.

**Comment by kirschbombe** [comment]
Here's a first stab at a warning statement - apologies if I don't fully understand all the implications!

"Warning: Recent developments in the browser community to discontinue support for third-party cookies has meant that IIIF Authentication API 1.0 workflows that rely on third-party cookies are now, or will soon be, obsolete in most browsers. The IIIF Authentication TSG is currently working on the next iteration of the Auth specification, which should address the third-party cookies issue. Workflows relying on first-party cookies should remain unaffected by these developments."

Should we share a draft with the Auth TSG for review?

**Comment by scossu** [comment]
The next Auth TSG meeting is on April 13. I'll be happy to add the draft to the discussion agenda if the editors wish to do so.

**Comment by zimeon** [comment]
Suggestion in https://github.com/IIIF/api/issues/1979#issuecomment-812219388 looks good to me. I suggest s/has/have/ (developments plural) and removing the "should" in the last sentence.

**Comment by jpstroop** [comment]
Agree w/ @zimeon's suggestions. Good otherwise. I think it's important to get this up soon. I feel as though @tomcrane wrote up a longer-form explanation of the issue. Should we consider linking to that (either in its current context or copied over as an implementation note https://iiif.io/api/annex/notes/) ?

**Comment by kirschbombe** [comment]
Based on the above suggestions:

"Warning: Recent developments in the browser community to discontinue support for third-party cookies have meant that IIIF Authentication API 1.0 workflows that rely on third-party cookies are now, or will soon be, obsolete in most browsers. The IIIF Authentication TSG is currently [working on the next iteration of the Auth specification](link here?), which should address the third-party cookies issue. Workflows relying on first-party cookies remain unaffected by these developments. For a more detailed discussion of the issues, see [Implementation note title](link)."

**Comment by kirschbombe** [comment]
@jpstroop - is this the write-up you had in mind: https://tom-crane.medium.com/what-happens-if-there-are-no-third-party-cookies-5ee5edb84d75?

**Comment by jpstroop** [comment]
Yes!

Sent via mobile, please excuse typos and brevity.

________________________________

**Comment by zimeon** [comment]
Fixed by #1990, warning now shows on https://iiif.io/api/auth/1.0/
