### ISSUE TITLE
can't use the start property in a collection to open a document at a specific canvas

### ISSUE THREAD

**Issue by altomator** [IIIF/api#1991]
as it is said in the specs:
https://iiif.io/api/presentation/3.0/#332-internal-links

- A Manifest may have the start property.
Clients should process start on a Manifest.
- A Range may have the start property.
Clients should process start on a Range.
**- Other types of resource must not have the start property.
Clients should ignore start on other types of resource.**

Is there a rationale for this restriction on collections?

The intent is to create curated collections of documents with specific opening pages:
- curated selection of newspapers issues with a comics section (use case here: https://github.com/altomator/IIIF#iiif-collections)
- curated selection of manuscripts with enlightened content
- etc.

IIIF collections are described in the specs as a general purpose tool, which is in contradiction with this restriction:  "Collections might align with the curated management of cultural heritage resources in sets, also called “collections”, but may have absolutely no such similarity."

**Comment by azaroth42** [comment]
The rationale is that there's no way for a client to know, when interacting with a collection, which of the manifests contains the referenced canvas to start at.

However your intent says specific opening page*s* ... do you mean that in the collection, each manifest would have its own `start`? That's fine ... the Manifest has the `start` property, not the Collection, in the same way that it should have a thumbnail (https://iiif.io/api/presentation/3.0/#51-collection)

**Comment by altomator** [comment]
My intent is to allow the start property in a collection description, for each manifest included in the collection:
...
"items": [
        {
          "id": "https://gallica.bnf.fr/iiif/ark:/12148/bpt6k4130558s/manifest.json",
          "type": "Manifest",
          "label": { "fr": [ "New York Herald, 3 décembre 1905, page 28"]},
          "start": {
              "id": "https://gallica.bnf.fr/iiif/ark:/12148/bpt6k4130558s/canvas/f28",
              "type": "Canvas"
            },
...

As a reuser of this NYH issue digitised by a library (BnF), I'd would like to use it in my Collection an open it at a specific opening page. 
BnF, as the owner of this digital document, may want to specify a default opening page in its Manifest (using the Start property too), e.g. to open it on the title page. These are 2 different use cases.

**Comment by kirschbombe** [comment]
This might be a good use case to include in the cookbook...

**Comment by altomator** [comment]
Ok, thanks! But Mirador 3 seems not to take `start` into account when used in this collection context...

**Comment by azaroth42** [comment]
You could raise that issue for Mirador: https://github.com/ProjectMirador/mirador/issues

**Comment by azaroth42** [comment]
Propose close :)

**Comment by zimeon** [comment]
2022-02-02 Editors' agree to close
