### ISSUE TITLE
create Change Discovery ontology for 'Refresh' class

### ISSUE THREAD

**Issue by mixterj** [IIIF/api#2008]
The current Change Discovery 1.0 spec has a class called 'Refresh' that is not in any current ontology. We should create some sort of documentation for this class, indicating that it is a subclass of as:Activity. @azaroth42  and I were chatting about this today and it seems like that would be the preferred path. This is related to issue #2006

**Comment by azaroth42** [comment]
See: https://github.com/IIIF/api/pull/2006/commits/2337be18ae7efc2e369d54a6632824696c15d4e8

**Comment by azaroth42** [comment]
Fixed.
