### ISSUE TITLE
Should api/index.md have a link to cookbook?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#2009]
I think so? Merge with the "Notes" section?

**Comment by hadro** [comment]
+1 to including cookbook link

My recommendation would be also to include a short bit of copy at the top of the page (1-3 sentences), very straight-forward, about the contents there and that could include a link to the cookbook

**Comment by glenrobson** [comment]
There is a pull request open to add it:

https://github.com/IIIF/api/pull/1995

**Comment by azaroth42** [comment]
Fixed.
