### ISSUE TITLE
Search 1.0 references "layer" section of Prezi 3.0 that doesn't exist

### ISSUE THREAD

**Issue by hadro** [IIIF/api#2024]
Similar issue to #2023, [Search 1.0 says](https://iiif.io/api/search/1.0/#paging-results) "[A]ll of the pages are within a [layer](https://iiif.io/api/presentation/3.0/#layer) that represents the entire resultset of matched annotations", but the linked reference is to a section that exists in Prezi 2.1 but not 3.0.

Should this link/reference be removed, amended, or other?

**Comment by zimeon** [comment]
Same as #2023... I don't think the text of the Search 1.0 spec should be changed but I think we can "sneaky-fix" the link to 2.1

**Comment by digitaldogsbody** [comment]
This is resolved - but should be linked to the commit that fixed it before being closed

**Comment by digitaldogsbody** [comment]
Resolved in this commit: https://github.com/IIIF/api/commit/deacb6b4058ca0d966d6bda05287dd0399e25891#diff-f3bf505edd7cdc1f0667354d38a7c17e755a24010298a00100ff89c1891aea05
