### ISSUE TITLE
Search alignment use of `annotations` and `items` property

### ISSUE THREAD

**Issue by mixterj** [IIIF/api#2054]
The current Search 1.0 spec defines the term `annotations` for point search Hits to Annotations. This current solution causes term collision with Prezi3.

The current proposed solution is to use `items` as the property but that also collides with Prezi3 in terms of the domain and range of the Prezi3 `items` property.

**Comment by mbennett-uoe** [comment]
Could we change this to `parts` or `components`?

**Comment by azaroth42** [comment]
Needs discussion about harmonization of vocabulary and what a "Hit" means in the prezi3 (etc) context

**Comment by digitaldogsbody** [comment]
Will be resolved if proposal in #534 is adopted
