### ISSUE TITLE
Update editorial committee roster

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#2077]
@mcwhitaker and @jpstroop have both stepped down from the editorial committee so we should update accordingly, I can think of:
  * [x] update editorial committee page https://iiif.io/community/editors/
  * [x] update editorial group on github

**Comment by jpstroop** [comment]
Do we need to have separate includes on the specs now too?

**Comment by zimeon** [comment]
Oh, indeed, I see the source for prezi 3:
```
**Editors:**

{% include api/editors.md editors=page.editors %}
```

**Comment by zimeon** [comment]
I'm also really embarrassed to see that in the page metadata we have `orchid` with an `h` everywhere to talk about ORCID ids!

**Comment by hadro** [comment]
> I'm also really embarrassed to see that in the page metadata we have `orchid` with an `h` everywhere to talk about ORCID ids!

Good news is it's just in the markdown, and I can fix with find/replace, I'll add it to the bug fix PR I have open

**Comment by zimeon** [comment]
Done (unless we've forgotten something)
