### ISSUE TITLE
Image Api: Units of area should be square pixels

### ISSUE THREAD

**Issue by damooo** [IIIF/api#2083]
Currently spec says [here](https://iiif.io/api/image/3.0/#52-technical-properties)

> The maximum area in ***pixels*** supported for this image. Clients must not expect requests with a width*height greater than this value to be supported.

Units of area should be in `square pixels` instead of `pixels`

**Comment by zimeon** [comment]
In it the IIIF Image API context, I think a pixel is an area that has a particular shape (a little square tile). Because of this shape it makes sense to talk both an area in terms of pixels, and a width or height in terms of pixel.

**Comment by mikeapp** [comment]
Resolved at Editors meeting 2022-02-02 that current language should stand.
