### ISSUE TITLE
Adding color mode information in the Image Information API

### ISSUE THREAD

**Issue by altomator** [IIIF/api#2110]
The [Image Information API](https://iiif.io/api/image/3.0/#5-image-information) surfaces several technical properties in the JSON response, particularly the width and height of the full image, but not the color mode (B&W, gray, color...) of the full image. This information can be useful in some use cases.

**Comment by azaroth42** [comment]
There is no source image in the abstract. Could have a colorized image via AI that "came from" a black and white source image. (eds, 2024 meeting)
