### ISSUE TITLE
Maintain implementation notes as Auth 2 is developed, for developers wishing to support both v1 and v2

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#2113]
Clients like UV and Mirador may wish to support both Auth 1.0 and Auth 2.0 at the same time - there are extant Auth 1.0 servers out there.

Implementation notes can describe where the two specs deviate.

We don't yet know how much backwards compatibility there might be. #1290 is entirely backwards compatible but isn't dealing with third party cookie issues.

**Comment by tomcrane** [comment]
Do we need the 2023 version of https://iiif.io/api/auth/1.0/implementation/ ?

**Comment by azaroth42** [comment]
... too late. Would go into recipes anyway.
