### ISSUE TITLE
AuthCookieService1 examples without profiles in Presentation 3.0.0 spec

### ISSUE THREAD

**Issue by ksclarke** [IIIF/api#2114]
There are two JSON examples in the 3.0.0 Presentation spec that look like:

```
"service": [
  {
    "@id": "https://example.org/iiif/auth/login",
    "@type": "AuthCookieService1"
  }
]
```

They are missing the `profile` which, I believe, the Authentication 1.0.0 spec says is required (https://iiif.io/api/auth/1.0/#service-description), and I think(?) would be needed for a client to do anything with that service information.

I'm guessing this is just drift between the standards (the presentation spec being finished before the authentication spec), but it seems like this could potentially be confusing to someone trying to read the presentation spec and work from the examples therein. Should the login profile be added to these examples in the spec?

**Comment by azaroth42** [comment]
Obsoleted by auth 2.0 and thus won't fix for 4.0, and can't fix for 3.0. Real issue though, thank you very belatedly @ksclarke.
