### ISSUE TITLE
Note difference between total (prezi/wadm) and totalItems (discovery/as2)

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#2118]
For AnnotationCollection and AnnotationPage, we inherit the definitions from the web annotation data model, which is built on top of the ActivityStreams model, but creates some AnnotationSpecific terminology. In particular, [WADM](https://www.w3.org/TR/annotation-model/#annotation-collection) uses `total` instead of `totalItems` as the items are all Annotations, and it doesn't talk about "items" anywhere else. Discovery, on the other hand, is not about annotations, and reuses the base ActivityStreams term of `totalItems`.

Now we come to search. Search is intended to be used directly with Presentation, as it's about searches for annotations. Thus we should continue to use `total`, despite the discrepancy with Change Discovery.

Propose that we put in a warning to this effect to search 2.0 in section 3.2.2

**Comment by zimeon** [comment]
Suspect intention was to put a note in 3.3.2 (https://preview.iiif.io/api/search-v3-alignment/search/2.0/#paging-results) rather than 3.2.2

**Comment by zimeon** [comment]
I'm not sure it is helpful to add such a note. To do so is to assume that someone is reading the the search spec with Activity Streams in their head. We don't mention Activity Streams and instead base the search spec on notions from Prezi. Prezi talks about its basis in WADM.

**Comment by zimeon** [comment]
Editors' meeting 2022-06-28: We want to use `total` to remain consistent with WADM. We decided not to add a note to Search 2.0.

**Comment by azaroth42** [comment]
Reopening for 4.0, where the list of properties is separated out.  I think under `total` we put in the note about `totalItems`
