### ISSUE TITLE
Cannot distinguish between search term snippet (3.4.2) and highlight within (3.4.3)

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#2120]
In the proposal in #534 as the annotation in the `annotations` block is identical in both cases at the moment.

I propose a "contextualizing" motivation for the search term snippet, and to continue to use "highlighting" for the other cases.

@mixterj ?

**Comment by azaroth42** [comment]
2022-04-19 - TSG agrees with contextualizing motivation as the least bad option.

**Comment by azaroth42** [comment]
Resolved by #2121

**Comment by digitaldogsbody** [comment]
Merged in https://github.com/IIIF/api/pull/2121
