### ISSUE TITLE
Search 2 draft still mentions Layer

### ISSUE THREAD

**Issue by digitaldogsbody** [IIIF/api#2126]
Section 3.2.1 has a reference to the now-deprecated Layer structure:

> Parameters that are received in a request but not implemented must be ignored, and should be included in the ignored property of the Layer in the response, described [below](https://preview.iiif.io/api/search-v3-alignment/search/2.0/#ignored-parameters).

Simplest fix would be to change "the Layer in the response" to just "the response"

**Comment by kirschbombe** [comment]
Addressed in PR #2133
