### ISSUE TITLE
contentState motivation is not defined in any context

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#2139]
Propose to put it in prezi3 context.

**Comment by azaroth42** [comment]
And put all search definitions into prezi3 context, as prezi3 needs at least the service types. 
Thus the additions which are less relevant are: `ignored`, `contextualizing` plus Autocomplete properties.

**Comment by azaroth42** [comment]
Also the annex of selectors.

**Comment by kirschbombe** [comment]
I added contentState and contextualizing motivations to prezi context here: https://github.com/IIIF/api/pull/2305.
