### ISSUE TITLE
Drop support for HEAD requests as auth probes

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#2158]
This issue does not address a published spec, but does propose simplifying an approach that has been in drafts of auth (and experimental implementations) for a while.

For an image service, there is an info.json service description endpoint. This acts as the place to attach auth service information, and also acts as a probe service - the client asks for the info.json and observes the HTTP status code of the response.

For AV resources (and, in fact, all content resources) there is no service description document. It's not a service - it's just a binary resource on the web. The current draft of the auth spec introduces a separate probe service, but makes an assumption that this might not always be possible and that the resource itself can act as its own probe service - the client observes the status code of an HTTP request made by script (e.g., `fetch`) to the resource itself (e.g., an MP4 file). To avoid requesting huge AV files just to see the status code, the draft auth spec says that this direct form of probe should be a HEAD request.

This offers implementation flexibility but it makes the spec more complicated, simply because it has to talk about HEAD requests, and introduce more branches into the flow diagram.

https://preview.iiif.io/api/1290-auth-probe-service/auth/2.0/#21-probe-service

Are there significant AV use cases in particular where it may be possible to implement the HEAD probe but not to implement a separate probe service? If not, this issue suggests dropping the HEAD pattern simply to simplify the possible flows.

**Comment by benwbrum** [comment]
Imagine the following scenario:

- Sometimes-restricted media is served at non-IIIF server `A`
- A manifest `B` is created pointing to this media by an unrelated party -- perhaps a shim creator, a researcher using AudiAnnotate, or someone pasting the media URL into a manifest editor.
- A user points their IIIF client `C` at manifest `B`.

How would `C` be aware of whether `A` will serve the file to their user without making a request for the media file itself via HEAD or GET?

Does this scenario fail to grapple with the Auth spec, but instead describe desired tolerance for clients?

**Comment by tomcrane** [comment]
In this scenario, HEAD-request-support at non-IIIF server `A` would tell the client (e.g., Mirador) that the user can't currently see the media, but it doesn't provide the client with the service endpoints it needs to allow the user to acquire the credential necessary to see the media. I think this is then outside the domain of the IIIF Auth spec, which is all about steering the user through an interaction pattern with the publisher of the media `A`.

One part of the spec is about "leaking" the information about the user's access to a resource so that a client doesn't attempt to show unshowable things.
The other part is allowing the client to let the user do something about their current lack of access.

There's nothing the publisher could put in their Manifest `B` to help the user acquire the credential, other than informal prose about where to go to log in - e.g., "Publisher `A` has a login page at http://a.com/login, you should go there first".

The goal of the auth spec is to automate the interaction that would otherwise have to be describe informally. This idea is described more long-windedly in slide 40 here: https://docs.google.com/presentation/d/1QwX_HiL8qy0E-kv64r3VeHmFSDtzYhNh96nHukJpJCo/edit#slide=id.ga5a145864f_0_116

The UV can't understand that text, but it can (just about) follow a protocol implementation of that text.

Going back to the question - HEAD support at `A` on its own is of value, but doesn't get the user very far; they'd need `A` to implement the Auth spec to use a IIIF viewer to access that resource. Which implies that `A` publishes a Manifest with IIIF Auth Services asserted for that media file. Which would allow `B` to assert those same services of `A`'s in its Manifest.

**Comment by tomcrane** [comment]
Eds meeting 24 January - Agree to drop HEAD, and close issue.
