### ISSUE TITLE
Company Logo, doesnt appear when configuring "provider" on IIIFv3

### ISSUE THREAD

**Issue by medau9** [IIIF/api#2171]
Hello everyone,
I am creating manifests using IIIFv3 and i'm having problems with the company logo. This doesn't show on any on my manifests. Im configuring it temporarily as in the old version, but has anyone been able to solve this problem. 
This is how I've configured the provider: 
```
"provider":[
    {
        "id": "https://example.com/",
        "type": "Agent",
        "label": { "en": [ "Example" ]},
    "logo": [
    {
      "id": "https://example.com/iiif/3/logo.png/full/2048,/0/default.png",
      "type": "Image",
      "format": "image/png",
            "service": [
                {
                  "id": "https://example.com/iiif/3/logo.png/full/2048,/0/default.png",
                  "type": "ImageService3",
                  "profile": "http://iiif.io/api/image/3/level2.json"
                }
            ]
       }
    ]
    }
  ],  

```
Thank you in advance, for any feedback.

**Comment by kirschbombe** [comment]
Hi, @medau9. When you say the logo doesn't show on your manifests, do you mean the logo is not displaying in the viewer (Mirador or UV)? To the best of my knowledge, neither viewer supports the `logo` property in v3 manifests yet, so this is more likely an issue for the viewer you are using. 

You should be able to display the logo using Presentation API 2.1 in Mirador. I'm not sure about UV support for logos in v2.

**Comment by medau9** [comment]
Hi @kirschbombe, the problem was as you mentioned Mirador not supporting v3 yet so the solution was to just use v2 syntax. 
Thank you for the response!

**Comment by regisrob** [comment]
@medau9 I think the [provider logo](https://iiif.io/api/presentation/3.0/#provider) property has recently been implemented in Mirador 3 (see https://github.com/ProjectMirador/mirador/pull/3657).

It does not work in https://projectmirador.org/embed/ but it does work in the dev instance: https://mirador-dev.netlify.app/__tests__/integration/mirador/
You can check with these two examples manifests:
https://iiif.io/api/cookbook/recipe/0234-provider/manifest.json
https://iiif.bvh.univ-tours.fr/data/manifests/B372616101_Res_3630_manifest.json

It depends on which version of Mirador you are using, but I also guess there is an issue with the manifest snippet you pasted above: the value of `logo.service.id` is not correct according to the IIIF specs (see https://iiif.io/api/presentation/3.0/#service; it must be the base URI of the image service, not an image URL)
