### ISSUE TITLE
Auth 2.0 Tasks

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#2202]
- [x] Tiered access section - @zimeon 
 - [x] workflow diagram @tomcrane 
 - [x] interaction diagram in https://preview.iiif.io/api/1290-auth-probe-service/auth/2.0/#simple-authorization-flow - @mikeapp 
 - [x] workflow description - @azaroth42 or @tomcrane 
 - [x] consistent section references - @zimeon 
 - [x] Make sure all internal links are filled in - @tomcrane 
 - [x] table heading consistency - @kirschbombe 
 - [x] tablify the bullet lists in probe service response - @zimeon
 - [x] Change from `interactive` to `active` interaction pattern name @zimeon 
 - [x] re-read. @IIIF/editors
 - [x] Change Log - @tomcrane 
 
Working on branch https://github.com/IIIF/api/tree/1290-auth-probe-service, when complete will merge into https://github.com/IIIF/api/tree/auth2.0-milestone

**Comment by zimeon** [comment]
Took a pass at the tiered access section https://github.com/IIIF/api/commit/ad2e1873f9856063c5cda1d1d2723bb71bda9a86

Also ack for Wellcome https://github.com/IIIF/api/commit/4daa78954496da9a4b33f0bc52f17e08d3d5e561

**Comment by zimeon** [comment]
Fixed section refs and links https://github.com/IIIF/api/commit/794dc3b8e9c21cbdb8ad831d5be34ee1dfca04e6 (perhaps including some of @tomcrane's task)

**Comment by kirschbombe** [comment]
updated table headings for consistency [6565db5](https://github.com/IIIF/api/commit/6565db502c1b8bc964b026a6c3ae98b3c9ddd60b)

**Comment by zimeon** [comment]
Also fixed probe result examples to not have `id` and have correct `type` https://github.com/IIIF/api/commit/1e5a8eafc82d095c78c7528c64630ca2d16346b4

**Comment by zimeon** [comment]
In editors' meeting 2023-02-16 we fixed `@context` description https://github.com/IIIF/api/pull/2127/commits/9e590cbfc19bb31ecb0a7348b58e6f2b163f5c6e

**Comment by zimeon** [comment]
Editors' discussion via Slack: Agree to change from `interactive` to `active` interaction pattern

**Comment by zimeon** [comment]
Changed to `active` in a29e66c4

**Comment by zimeon** [comment]
Resolved. The IIIF Authorization Flow 2.0.0 specification was published 2023-06-02: https://iiif.io/api/search/2.0/
