### ISSUE TITLE
Manage groups of Annotations on multiple canvases in a Manifest

### ISSUE THREAD

**Issue by robcast** [IIIF/api#2203]
There are many applications for specific use-cases which produce large amounts of annotations on multiple images. Examples are OCR/HTR or crowdsourcing of transcription of books producing transcribing annotations or AI/CV algorithms producing tagging or other kinds of annotations.

Users would like to manage these annotations as separate groups or layers identified by labels. Viewers would indicate the availability of annotation groups and offer to show or hide one or multiple groups or offer the use of colors to differentiate annotations from different groups.

Currently the IIIF Presentation spec offers the [AnnotationCollection](https://iiif.io/api/presentation/3.0/#58-annotation-collection) to "represent groupings of Annotation Pages that should be managed as a single whole, regardless of which Canvas or resource they target" which would fit the purpose of managing annotation groups.

But currently an AnnotationCollection is only allowed in the [`supplementary` attribute of a Range](https://iiif.io/api/presentation/3.0/#supplementary) (see also #2123). Using this mechanism would require to create a Range duplicating all Canvases for each annotation group which would not have any other function and using the `supplementary` attribute against the intention in the spec: "Clients might use this to present additional content to the user from a different Canvas when interacting with the Range, or to jump to the next part of the Range within the same Canvas."

Can we add an extension or change the Presentation spec to add annotation groups in the form of a list of AnnotationCollections at the Manifest level?

**Comment by robcast** [comment]
Some related issues:
* #2123 
* https://github.com/IIIF/cookbook-recipes/issues/309
* UI concepts from Mirador for Motivations that could be reused: https://github.com/ProjectMirador/mirador/issues/2946
* Use-case that could be solved (but not with Motivations): https://github.com/ProjectMirador/mirador/issues/3100

**Comment by robcast** [comment]
Additional use-case: I have a web-service that identifies illustrations in scans early-modern printed books and provides a classification and the coordinates of these illustrations on the page. The service takes a IIIF Manifest as an input and provides Web Annotations targeting the Canvases from the Manifest as an output. (https://cordeep.mpiwg-berlin.mpg.de/)

I want to save these Annotations in an AnnotationCollection and provide these in a viewer as an optional "layer" on top of the normal presentation of the Manifest.

The user should see that this layer is available, she should see some information about the layer, and she should be able to show or hide the layer. The Annotations in the layer should be differentiated from other Annotations by their color or other means.

**Comment by giacomomarchioro** [comment]
Additional use-case: I want to group specific areas of a painting e.g. multiple areas that are degraded or areas that have been treated with a certain procedure and I want to group the annotation accordingly.

**Comment by azaroth42** [comment]
No change needed to the specs, can use `partOf` to point to the `AnnotationCollection`. There's an entry in the cookbook list cookbook-recipes#309. Propose close.

**Comment by azaroth42** [comment]
Editors agree invalid -- just use partOf per the spec. The annotation collection can't be *embedded* in the manifest, but it can be *referenced* from the manifest. No change needed. Closing.
