### ISSUE TITLE
Not returning 1×1px with /0,0,1,1/max/0/default.jpg?

### ISSUE THREAD

**Issue by larsmaxfield-asml** [IIIF/api#2264]
My understanding is that a request for `/0,0,1,1/max/0/default.jpg` should extract a 1×1px region at (0,0). However, I'm served a 2738×2738px image instead:

![Screenshot of URI and resultant image size in browser window title.](https://github.com/IIIF/api/assets/129512384/9e04afa4-4a91-4d39-8d1b-5292a9d2661a)

From what I see in the [Image API 3.0 documentation](https://iiif.io/api/image/3.0/#42-size) on size, `max` is:

> The extracted region is returned at the maximum size available, but **will not be upscaled**. The resulting image **will have the pixel dimensions of the extracted region**, unless it is constrained to a smaller size by maxWidth, maxHeight, or maxArea as defined in the [Technical Properties](https://iiif.io/api/image/3.0/#52-technical-properties) section.

Am I encountering expected behavior? I'm still becoming familiar with IIIF so I might be missing something obvious. I've set things up by following the handy training steps [here](https://training.iiif.io/iiif-1-day-workshop/image-api/setting-up-cantaloupe.html) with a Cantaloupe server.

**Comment by azaroth42** [comment]
Yes this is a bug in Cantaloupe. Not a spec issue.
