### ISSUE TITLE
Latest stable version is missing from Change Discovery 1.0 API header

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#2286]
The "Latest Stable Version:" value is missing even though this link from ".." works:

![Screenshot 2024-02-29 at 2 30 21 PM](https://github.com/IIIF/api/assets/658600/c632c5e1-a339-42b3-9545-34d9fa76ee49)

**Comment by azaroth42** [comment]
Duplicate of #2151

**Comment by zimeon** [comment]
Oops, closing in favor of #2151
