### ISSUE TITLE
Possible discrepancy between Pres. API spec. and JSON-LD Context re. viewingDirection

### ISSUE THREAD

**Issue by milvld** [IIIF/api#2297]
While browsing [the Presentation API specification](https://iiif.io/api/presentation/3.0/#viewingdirection) and [the accompanying JSON-LD Context](https://iiif.io/api/presentation/3/context.json), I've noticed that the specification states that the value of viewingDirection 'MUST be a String', whereas the Context views this as an @ container of @ set. 

Is it possible that this is a contradiction? Since it results in the fact that the manifest outputted using this context, uses an array of strings for viewingDirection rather than a single string value.

**Comment by azaroth42** [comment]
Great catch, thank you! It shouldn't be `@container:@set` in the context

**Comment by azaroth42** [comment]
Dawn and Rob note that this can be fixed at any time as context is not semantically versioned
