### ISSUE TITLE
Motivation should be Array, not String

### ISSUE THREAD

**Issue by cubap** [IIIF/api#2324]
https://iiif.io/api/content-state/1.0/#53-multiple-targets-for-a-comparison-view

https://github.com/IIIF/api/blob/17629e12c6fa0327b6043bcdffa8c7f804d48edb/source/content-state/1.0/index.md?plain=1#L581

**Comment by glenrobson** [comment]
Duplicate of https://github.com/IIIF/api/issues/2313
