### ISSUE TITLE
Recto/Verso on Canvas for book modality

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#33]
Requested Feature:  Add explicit recto/verso flag on a canvas to enable page turning applications to correctly determine whether to have the first canvas start on the recto or verso of an opening.  Must work with top-to-bottom as well as left to right, eg for flip charts/flip books.

Decision:
- Allow a new field to say that the canvas is not part of the page turning paradigm, even though it's part of the sequence. 
- The first canvas is explicitly a "single", not part of a recto/verso pair.  If this is not the case, then either mark it as not to be rendered in a page turner, or create an empty canvas at the beginning to represent the single rather than spread.
- Applies only to "paged" viewingHint, and directionality comes from existing "viewingDirection" property.

Editor's Proposal:
- Allow viewingHint on canvas and add "non-paged" to enumerated values
  Example:

``` javascript
{
  "@id": "http://example.org/iiif/book1/canvas/f1r-curtain.json",
  "@type" : "sc:Canvas",
  "viewingHint" : "non-paged",
  "height" : 1200,
  "width" : 800,
  "images" : [...]
}
```

**Comment by nicolasfranck** [comment]
what is the current status/view on this? Without an explicit statement like "recto" or "verso" on each canvas, manifests that start with the left page cannot be shown in a page turning interface..

**Comment by kirschbombe** [comment]
Hi, @nicolasfranck. I believe the only IIIF solution is to use the `viewingHint` property ([Presentation API 2](https://iiif.io/api/presentation/2.1/#viewinghint)) or the `behavior` property ([Presentation API 3](https://iiif.io/api/presentation/3.0/#behavior)) with the value "non-paged" as described above on any canvas that should not be presented as part of the page turning view. Unfortunately, none of the viewers support this property yet that I'm aware of.

**Comment by jpstroop** [comment]
> manifests that start with the left page

If an item is paged left to right, you can use [`viewingDirection`](https://iiif.io/api/presentation/3.0/#viewingDirection).

**Comment by azaroth42** [comment]
I think the case here is:

Object is paged. The first imaged canvas is a verso, not a recto, and thus should be displayed two-up with the following recto.  e.g. the first canvas is the inside front cover and the second is folio 1 recto.

So ... the first canvas is not not-paged, it's that there's a "missing" previous recto.

My solution would be to have an empty canvas as first in the sequence/items and set startCanvas/start to the second canvas. The viewer would then treat the empty first canvas as the recto, and display two up for the first imaged one. Start would have the client skip over the first empty canvas.

**Comment by azaroth42** [comment]
[Opening re recipe for proposed solution]

**Comment by kirschbombe** [comment]
@azaroth42 - got it. I've done the same in the past re: adding in a blank canvas, although UV doesn't seem to like it when the first canvas is empty (in our implementation at least). I wonder if adding in the start property would help. Maybe I'll take a stab at a recipe now that the thumbnail implementation discussion is done.

**Comment by kirschbombe** [comment]
I've also noticed BnF at some point used a "content missing" image on canvases where the images were missing, so that could be a second option...
option a: add empty canvas
option b: add canvas with default "content missing" image

I can create an issue in the cookbook repo and move this convo over there.

**Comment by nicolasfranck** [comment]
It is not just about the first canvas that is a "verso" instead of "verso".
From the manifest a "pattern" is applied to the canvases, forming couples 
like "1", "2-3", "4-5".  This looks like the easiest solution at first, but as
soon as there are exceptions to this pattern, it becomes difficult to
express these exceptions. You just showed a few ways to circumvent
this problem, but these would not be necessary if these canvases
were explicitly marked as either recto or verso.

Making this explicit by marking two canvases as part of one couple
would make this easier for viewers to interpret. Maybe someone
wants to put 3 canvases at once (instead of 2) in the viewport?
Just an idea.

**Comment by nicolasfranck** [comment]
Neither the universalviewer nor mirador implement `viewingHint` `non-paged` for canvases btw.. 
That hint is ignored, and so the canvas becomes part of couple

**Comment by azaroth42** [comment]
Can you describe the scenario that cannot be expressed? Whether viewers implement the spec or not is on the viewer (and thus to be taken up with them, in their repos) and not on the specification.

As far as I can tell, between a "fake" initial folio (truly, the side must exist, it's just not been imaged) and `non-paged` to exclude entries from the two-up pairs, everything can be expressed. Whether it is easy or not is another matter, but the cost of making this 0.01% case easy is a lot of pain for the 99.99% cases. So we run into the maxim:  Make the easy things easy, and the complex things possible.

**Comment by jpstroop** [comment]
`viewingHint=facing-pages` is the solution for the 2-3, 4-5 problem, btw

**Comment by nicolasfranck** [comment]
> Whether viewers implement the spec or not is on the viewer (and thus to be taken up with them, in their repos) and not on the specification.
> 

agreed.

**Comment by regisrob** [comment]
We have the same issue with a digital library that is in the process of implementing IIIF: e.g. in [this example](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372616101%5FMs%5F2102&numfiche=1436&mode=3&ecran=0&offset=0), where the first two canvases (i.e. the spine and the upper cover) should have a `non-paged` behavior, which is not yet supported by Mirador 3 according to this pending [PR](https://github.com/ProjectMirador/mirador/pull/3029) (I have not tested in UV yet)

**Comment by zimeon** [comment]
2022-02-02 Editors' meeting - will close again, per discussion above this isn't a spec issue and will be explained in cookbook. (There remain deficiencies in current implementations)
