### ISSUE TITLE
Investigate LDP compability

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#377]
http://www.w3.org/TR/ldp/

I think our proposed presentation URI structure actually works okay with LDP.
Might also inform how to handle info.json / image content with REST.

**Comment by azaroth42** [comment]
Continuing to defer on rest means we can continue to defer on this. Pushing to 2.2

**Comment by jpstroop** [comment]
Six years on, Editors are closing as use cases have not emerged and those that have seem to be covered by Discovery and Content State.
