### ISSUE TITLE
Allow cropping rotation

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#440]
Potentially by adding 'c' at the end of the rotation parameter:

![image-api-2 1-crop-rotation](https://cloud.githubusercontent.com/assets/871868/6690257/bec1e39e-cc7c-11e4-8d11-f20b9ad2d702.png)

**Comment by zimeon** [comment]
Semantics of crop seem simple and clear, I don't see any problem from an implementation side.

Regarding syntax, could consider a leading bang (!) instead of trailing "c", to mirror use of bang in size parameter: http://iiif.io/api/image/2.0/#size

BUT, perhaps biggest question is whether the increased API complexity is worth is. Do we have evidence of the user of rotation at present? Do we have a compelling enough case for this new form?

**Comment by azaroth42** [comment]
Editors opinion is:  Too complex for too little value.  High value implementations and specific use cases that demonstrate the value are sought for consideration of potential inclusion in Image API 2.2.

**Comment by olivierdalang** [comment]
Just advocating for this feature.

Working with maps here, where rotation is not always towards north.
By allowing cropped rotation, we could get map tiles from the image server directly, to be used in GIS context.
That black or transparent background with no data in it makes only sense when getting the full image.

**Comment by klokan** [comment]
BTW we use the client side for arbitrary rotation successfully. No real requirement for rotation in arbitrary angle (which is optional feature of IIIF - and not implemented in IIPImage).
Practical examples:
- Hold Alt-Shift and click-drag a mouse in our IIIFViewer: http://klokantech.github.io/iiifviewer/
- For more advanced operations on maps available via IIIF have a look at: https://www.youtube.com/watch?v=-cNmx3MbSEo or try it life at: http://cynefin.archiveswales.org.uk/en/tithe-maps/

There is a proxy web service generating WMTS tiles from a IIIF image server as well - giving nice GIS friendly {z}/{x}/{y}.png tiles from any map in IIIF - used in large scale (in beta) on the David Rumsey maps.

**Comment by zimeon** [comment]
Discussion on IIIF Discuss call:
  * Possible use case of citation of a rotated image. Goal is to cite particular state of image. Complication of correspondence between rotation of canvas and rotation of image. Bryan comments that for his addition to Mirador the canvas/container and hence annotation is rotated.
  * Could address this by having the ability to change the order of crop and rotate to be rotate then crop, would be a big change
  * Consensus to defer

**Comment by zimeon** [comment]
Eds' meeting: Still feel this is defer. Note that as an addition it could be in 3.1 so we don't have particular pressure to consider for 3.0.

**Comment by azaroth42** [comment]
Consensus on community call of 2018-01-31 that this could be added to 3.0 as an optional feature (above level 2) if use cases are provided.  Dependent on #1376 as to whether it's in the spec or an extension.

**Comment by jpstroop** [comment]
@IIIF/editors continue to defer pending use cases. Will write to IIIF Discuss later today.

**Comment by azaroth42** [comment]
Community call of 2018-03-14:  Continue to defer.  No use cases known.  Not for 3.0.

**Comment by azaroth42** [comment]
Editors, after three years grace period of no comments, are closing this issue.
