### ISSUE TITLE
Require support for square size at level 1 in Image3.0

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#501]
Can't require it during 2.x due to conflict with minor version differences in compliance levels and only having a major version differentiator in the URI.  So delay requirement until next major version.

See Sem Ver: #470 and Square: #425

**Comment by azaroth42** [comment]
:+1: I think we've accepted this as given, right?

**Comment by zimeon** [comment]
Agreement at The Hague that needs to be level 1 in Image API 3.0

**Comment by azaroth42** [comment]
closed by #1419
