### ISSUE TITLE
Autocomplete on non-q query params? -

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#509]
Should there be a way to autocomplete on the URI index, rather than on the text index?  I would expect not, but it seems asymmetric if query terms are not required (e.g. for semantic tag search).

**Comment by azaroth42** [comment]
Nullified by the change to include URIs in the q param.  

Discussed use cases for autocomplete on other params (especially user) but while we can see the potential, we don't want to go there yet.  Other params are either not susceptible to autocomplete (e.g. date), limited in number of possibilities (e.g. motivation) or will be provided by the user or client (q and box)

**Comment by zimeon** [comment]
Closing, won't fix
