### ISSUE TITLE
Importing Prezi API semantics into Image API ties versions together

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#518]
i.e., importing the semantics of logo, attribution, license in into the Image API means we can't change them.
- Should elements like `logo` be simplified in the Image API?

**Comment by jpstroop** [comment]
Defer until this becomes an issue, probably when one API jumps to 3.0.0

**Comment by azaroth42** [comment]
Is this still valid? Is the issue that in Prezi we can have `rights` while still stuck with `license` in Image for the same predicate?

**Comment by azaroth42** [comment]
Undeferring given work on Prezi 3

**Comment by azaroth42** [comment]
Related to (even depends entirely on) #1217

**Comment by jpstroop** [comment]
Prop

**Comment by azaroth42** [comment]
Reopening given lack of agreement on #1217.

**Comment by azaroth42** [comment]
Reclosed by #1408
