### ISSUE TITLE
profile property must be an array, hence should be plural profiles

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#520]
... or we should make the processing requirement that profile can be either a uri string, or a list of strings and/or objects.

Breaking change, so we can't make it before Image API 3.0

**Comment by azaroth42** [comment]
:+1: I think we've accepted this as correct?

**Comment by zimeon** [comment]
:+1:, defer to Image 3.0 as breaking change however

**Comment by sdellis** [comment]
Is there a reason why profiles must be an array and cannot be treated like all the other repeatable properties (can either be single string/object or array)?

**Comment by azaroth42** [comment]
Yes, because if you read the spec, the *first* profile must be one of the levels.  *First* means that there's order, and a repeated property has no inherent order.

**Comment by jpstroop** [comment]
Unless you support no qualities, you're always going to have two members in the profile list, e.g.:

```json
  "profile" : [
    "http://iiif.io/api/image/2/level2.json",
    {
      "formats" : [ "gif", "pdf" ],
      "qualities" : [ "color", "gray" ],
      "maxWidth" : 2000,
      "supports" : [
          "canonicalLinkHeader", "rotationArbitrary", "profileLinkHeader", "http://example.com/feature/"
      ]
    }
  ]
```

That said, two things:

1 . Our example at the [end of 5.1](http://iiif.io/api/image/2.1/#image-information-request) is misleading.
2. I've always hated that mixed construction (string and object). Maybe the additional stuff should be moved out in 3.0?

**Comment by jpstroop** [comment]
Conversation in the Hague: There are bigger issues here:
 1. Should the compliance URI and the `{ }`  both be in the profile? Or just the `{ }` and the compliance URI somewhere else?
 2. The spec is inconsistent in it's description of what belongs in, e.g., `formats`: should the inline profile list all available formats, or just those that are in addition to the declared level of compliance?

**Comment by azaroth42** [comment]
Does this also impact the use of `profile` in the Presentation 3 spec? I think we're introducing cross-version / cross-api headaches here, and better would be to require clients to scan the list. 
See also: #1013

**Comment by zimeon** [comment]
To the original question: in 3.0 we'll have a number of properties that are required to be arrays but are not plural (e.g. `renderingHint`, `service`, `rendering`) so I'd just stick with `profile` required to be and array (no order specified, cf. #1013) rather than going for plural. This option has the fewest cross-version issues too.

If we want to consider https://github.com/IIIF/api/issues/520#issuecomment-255036400 more I think we should split that off as a separate issue. I do not feel uncomfortable with URI or object inside the `profile` array.

**Comment by azaroth42** [comment]
The required order and mixed construct implies to me that we got it wrong with 2.0 and we should consider, per @jpstroop, an easier pattern in 3.0.

How about we close this issue, and 520, in favor of a new general issue of how to deal with profile in Image 3?

**Comment by azaroth42** [comment]
Closing in favor of #1275.
