### ISSUE TITLE
Mobile (IOS) without popups?!

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#528]
Can't open a popup window in IOS browsers, and can't generate a new tab without a specific user action.  Popup blockers are just on or off, not per domain. 

Should write an auth implementation note to capture these issues and any workarounds.

**Comment by azaroth42** [comment]
@tomcrane Did you find a workaround for this, and if so can you document it as a note?

**Comment by tomcrane** [comment]
There is no workaround as such - a client could do something like attempt to ```window.open(strUrl, strWindowName, strWindowFeatures)``` with strWindowFeatures having explicit dimensions (popup) and if that errors or results in a null reference, fall back to a new tab with ```window.open(strUrl, strWindowName)```. We chose not to do this for UX consistency across devices, but other clients could try it.

I think I will enlarge Appendix A substantially and reference it in the main text - or would a separate document be better for impl notes? I prefer a single coherent document. Need to make sure that a client implementer isn't led into trying something by the main text only to be told they might not want to do it that way in the implementation note.

It will be next week before I can spend some time on this. I have the basis of the notes scattered around Google docs and emails. We can ask @edsilv and @aeschylus to review.

**Comment by azaroth42** [comment]
Can close when we add (accept) implementation notes from @tomcrane that explains the workflow for mobile.
  http://auth_notes.iiif.io/api/auth/0.9/implementation/#window-behaviour-across-devices

**Comment by azaroth42** [comment]
I think we can close, now that implementation notes are merged?

**Comment by zimeon** [comment]
Implementation note is live at http://iiif.io/api/auth/1.0/implementation/, with specific mention of new window issue in http://iiif.io/api/auth/1.0/implementation/#event-initiation . Agree close

**Comment by azaroth42** [comment]
Closing per above.
