### ISSUE TITLE
Use TextQuoteSelectors on hits to match within the content?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#534]
Per current text in 3.3.4.2 in http://search.iiif.io/api/search/0.9/#search-specific-features

However as the selectors are not tied directly to the annotation (or even to the body), the selector approach doesn't work when there are multiple annotations referenced from the hit :(

To make this work, it would need to be a SpecificResource for the Body, which is pretty heavyweight and requires a URI on the body so it can be referred to:

``` json
{
  "selectors": [
    {
      "@type": "oa:SpecificResource",
      "hasSource": "uri-for-body-of-annotation",
      "hasSelector": {
        "@type": "oa:TextQuoteSelector",
        "prefix": "...",
        "exact": "match text",
        "suffix": " ..."
      }
    }
  ]
}
```

**Comment by azaroth42** [comment]
Propose: defer, out of scope for 0.9.

**Comment by azaroth42** [comment]
:+1:s to defer?

**Comment by jpstroop** [comment]
Would it be considered a breaking change to introduce it later (i.e. if a client had to be aware of two different types of resources in the selectors list)? I think it would be useful to get it in now if we agree that it would be a breaking change later.

**Comment by azaroth42** [comment]
Updated pointer: http://search.iiif.io/api/search/0.9/#multi-annotations-hits

I think it would be breaking, as currently selectors expects a selector, not a specific resource.  

@tomcrane: If we had this, would UV use it?

**Comment by tomcrane** [comment]
Not any time soon, unless the British Library suddenly have a pressing need for it. Currently the UV doesn't do any search result highlighting other than by painting rectangles onto the canvas (there's no HTML rendering of the hit other than as a marker on the search bar). However, I'd like to see a contextual popup similar to the Internet Archive bookreader, which could make use of this information.

I can see the problem though. How common would it be? If a server is able to return word level annotations, it won't need to use the TextQuoteSelector because it can return the precise selection as annotations for painting directly.

The problem is for a hit that targets multiple annotations, where the ```hit.before```, ```hit.match``` and ```hit.after``` properties are not sufficient to identify the matching text:

q=bird in the hand

line annos only:

It is often said that a ***bird in the 
hand*** is worth two in the bush

Question - would the 3.4.4 ```hits``` example be semantically wrong if the two annos were line-level? So that "match" is not an exact match for the content of the annos?

**Comment by azaroth42** [comment]
If we don't have any implementers ... propose `defer` rather than further complicate the spec?

**Comment by zimeon** [comment]
I think we should discuss in eds call the question of whether it is likely that we will want this later and might be better heading off a breaking change by doing something now. I think, BTW, that the text in [3.4.4](http://search.iiif.io/api/search/0.9/#multi-annotations-hits) that @tomcrane mentions needs some work to improve clarity anyway.

**Comment by jpstroop** [comment]
:+1: to defer

**Comment by mikeapp** [comment]
:+1: defer

**Comment by azaroth42** [comment]
Consensus is to defer:
  * There's no implementation needed
  * It might not be breaking if we're just adding a new property to cover a specific new feature
  * We will want to update major version when the Web Annotation group gets to full TR, and that provides another opportunity to reassess

**Comment by digitaldogsbody** [comment]
Relies on discussion about terms in https://github.com/IIIF/api/issues/2050

**Comment by azaroth42** [comment]
```
{
	"items": [
		{
			"type": "Annotation",
			"body": {
                "id": "#bird1",
				"value": "this bird is awesome",
				"annotations": [
					{
						"type": "AnnotationPage",
						"items": [
							{
								"type": "Annotation",
								"motivation": "hit",
								"target": {
									"source": "#bird1",
									"selector": [
										{
											"type": "TextQuoteSelector",
											"exact": "bird",
											"prefix": "this",
											"suffix": "is awesome"
										}
									]
								}
							}
						]
					}
				]
			},
			"target": "canvas1#xywh=1,1,2,2"
		}
	]
}
```

**Comment by azaroth42** [comment]
Simplest:
```
{
 "items": [
  {
   "type": "Annotation",
   "motivation": "matching",
   "body": {"value": "word"},
   "target": "canvas1#xywh=1,1,2,2"
  }
 ]
}
```

**Comment by azaroth42** [comment]
Revision - use `items` and `annotations` from prezi3 in the same way as 'hits' in v1.

```json
{
  "type": "AnnotationPage",
  "items": [
  {
   "id": "#bird1",
   "type": "Annotation",
   "motivation": "matching"
   "body": {"value": "that bird in the bush is that"}
   "target": "canvas#xywh=0,0,10,10"
  },
  {
    "id": "#bird2",
    "type": "Annotation",
    "motivation": "matching"
    "body": {"value0": "bird in teh other bush"}
    "target": "canvas#xywh=12,10,10,10"
  }
 ],
 "annotations": [
    { 
      "type": "AnnotationPage",
      "items": [
        {
        "type": "Annotation",
        "motivation": "hit",
        "target": {
         "source": "#bird1",
         "selector": [
          {
           "type": "TextQuoteSelector",
           "exact": "that bird",
           "suffix": "in the bush"
          }
         ]
        },
       {
        "type": "Annotation",
        "motivation": "hit",
        "target": [{
         "source": "#bird1",
         "selector": [
          {
           "type": "TextQuoteSelector",
           "exact": "that",
           "prefix": "the bush is"
          }
         ]
        },
       {
         "source": "#bird2",
         "selector": [
          {
           "type": "TextQuoteSelector",
           "exact": "bird",
           "suffix": "in the other"
          }
         ]
        }
      ]
    }
  ]
}

```

**Comment by digitaldogsbody** [comment]
:+1: to this proposal

**Comment by azaroth42** [comment]
Explanation while fresh in my mind:

* `items` is the set of content annotations that provide the content for the matches. `annotations` is the set of matches against the content annotations -- the "hits" as opposed to the actual content. 

* `items`...
  * ... might be 1:1 with the matches (e.g. single word query with word level annotations)
  * ... might be larger than the query, but completely contain it (the first match in `annotations` above)
  * More than one content annotation may be required to complete the match (the second match in `annotations`), regardless of whether the content is single word or longer string

**Comment by digitaldogsbody** [comment]
Proposal accepted in Content Search TSG call 19th April - https://docs.google.com/document/d/1aEeKjDc7XwnuTnE3tfcBpl7CL33kCyTlAkZ7AoWi27I/edit
