### ISSUE TITLE
Use id/type instead of @id/@type

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#590]
Schema.org, Social Web / ActivityStreams, Annotation WG will all adopt this.
Manu, danbri, tantek, etc all agree.

There will be a best practices document published from W3C that states this

**Comment by azaroth42** [comment]
Upstream issues: 

 * https://github.com/w3c/web-annotation/issues/88 
 * https://github.com/jasnell/w3c-socialwg-activitystreams/issues/232 
 * https://github.com/schemaorg/schemaorg/issues/854

**Comment by azaroth42** [comment]
We should confirm that we're going to do this to avoid future discussion.
My vote:  :+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by jpstroop** [comment]
:+1:

**Comment by tomcrane** [comment]
:+1: - Went down well in The Hague

**Comment by zimeon** [comment]
:+1: - I was a little concerned about the churn this causes in code using the JSON but speak with developers @ The Hague they seemed to see the change as a net benefit

**Comment by azaroth42** [comment]
Discussion on 8/2/17:  Agreement. Need to make it clear that P3 + I2 will run into both. 

Could we add id and type as well as leaving in @id and @type in Image 2.2?  Fewer implementations of actual processors for image -- leaflet and OSD can support both and no one will notice :)

**Comment by jpstroop** [comment]
See also: #1064

**Comment by azaroth42** [comment]
Manifest could consistently use `id` as it just gets fed to the Image processor anyway.  Support from @jronallo and @mejackreed for this, as implementers.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting

**Comment by azaroth42** [comment]
Done for Presentation, removing the tag, but leaving open until all the other specs catch up.

**Comment by azaroth42** [comment]
Tagging principles to document as a design pattern.

**Comment by azaroth42** [comment]
Propose that this will be closed by documenting the principle, that we will then stick to.
E.g. by #1510

**Comment by zimeon** [comment]
:+1: Agree that this is already addressed in the v3 specs, can close by documenting principle in #1510

**Comment by tomcrane** [comment]
👍
