### ISSUE TITLE
Discovery overview, including within: Collection

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#609]
A discovery overview document should recommend best practices that content providers can take, including having up links from Manifests to the Collections that they are known to be part of.

A crawler could then follow those links to construct a better picture of the IIIF universe.

**Comment by zimeon** [comment]
I do like the idea of having a "what you can do now (with no extra infrastructure)" document as a starting point for discovery "specs". I think pushing people to adopt the approaches suggested and seeing how for that gets us would be a productive/efficient way to proceed.

**Comment by azaroth42** [comment]
Closing as no longer meaningful, given discovery TSG work
