### ISSUE TITLE
Change "license" to "rights"

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#644]
The key "license" in the JSON-LD maps (as of 2.1) to dcterms:rights.  It should be called "rights".
This is currently deferred as it would be a breaking change.

**Comment by anarchivist** [comment]
ref #636

**Comment by azaroth42** [comment]
To avoid future discussion, we should confirm it.
My vote: :+1:

**Comment by anarchivist** [comment]
👍  - not an editor, but speaking as a co-chair of the rightsstatements.org TechWG

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by jpstroop** [comment]
:+1:

**Comment by jpstroop** [comment]
2 August 2017 call: Consensus is that we should do this.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#rights
