### ISSUE TITLE
What warnings/issues should go in published specs?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#691]
Currently we have two warnings (or will, once #687 hits) in Image and zero in Prezi.  

I think it would be good to decide and document our policy around warnings and issues for _released_ specs.  While specs are in draft, they are great signaling devices for where to pay attention.  In released specs, they're highlighting areas where we got it wrong the first time, which can reduce confidence in the process and the community.  This is not to say we're always going to get it right (clearly not!), and I agree we need to be transparent and say where we're going to fix things ... I'm not convinced that bold red in the spec is the way to go.

For example, do we also signal the intent to move to the Web Annotation model, once it's published?  Or at the micro scale, `licence` -> `rights`? (Or any other `defer`ed change?)

**Comment by jpstroop** [comment]
> In released specs, they're highlighting areas where we got it wrong the first time, which can reduce confidence in the process and the community.

Past a certain point, but I think that's true, but I don't think we're there yet. Is it better to stay silent, and pull the rug out in the next major revision? If I'm writing a new client, I think I'd rather know.

**Comment by azaroth42** [comment]
Agree that it's good to be open ... but I'd (personally) prefer a separate location to look at for pending deprecations / changes.  Then you implement against the current spec, but can keep in mind the coming changes.

**Comment by tomcrane** [comment]
There are different levels of warning maybe?

* The ```sizes``` inconsistency merits a real warning, as it might cause implementers a headache right now
* ```max```, ```license``` --> ```rights``` and so on are points for implementers to take note of and possibly support both in clients and servers, and don't need a big red box in a released spec, but can be described in a changes section
* OA --> Web Annotation: perhaps this warrants a page to itself - it's important, but you can't do much about it right now, here's what we suggest you should do if you want to implement annotation clients and servers for IIIF resources now and want an easy transition to the W3C model later.

**Comment by azaroth42** [comment]
Given the changes between 2.0 and 2.1 (where we added deprecation warnings for canvases/ranges on range, in favor of members) and the subsequent changes in 3.0 (where we will remove canvases/ranges, in favor of items) what have we learnt?

My feeling is that when we make changes, they're never exactly what we thought they would be when we were writing up the previous version, beyond trivial renames like license->rights. I'm (still) in favor of a separate annex document, linked from the specs and keep warnings in the specs to a minimum.

**Comment by azaroth42** [comment]
Propose close wontfix?

**Comment by zimeon** [comment]
If `close wontfix` means we can't predict what we'll need to do to warn about the as-yet-undiscovered snafu or deprecations to be announced in 3.1 -- I agree

**Comment by azaroth42** [comment]
Closing :)
