### ISSUE TITLE
Deprecate sizeAboveFull ?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#693]
Is there an actual use case for sizes above full?  We've heard a case where it causes problems from the Qatar Digital Library:

> For example, on an individual artwork page, if we use a size parameter of 800x800 max dimensions (/!800,800/), but the source image is only 500px max, the image server will (correctly) upscale the image to match 800x800. However, this will result in a pixelated image being returned to the user.
> From: https://groups.google.com/forum/#!topic/iiif-discuss/NSG0tGssSUw

And also that without a maximum size, it can be used as a Denial of Service attack, per the discussion in #690.

It's a feature that's optional to support at all levels, but by calling it out as a feature and validating whether it is available, implementations make efforts to provide it.

**Comment by jpstroop** [comment]
I think this probably makes sense. If you want to upsample/interpolate, you're likely to do it further down stream, e.g. in the browser. How about we talk about this on the next call?

**Comment by azaroth42** [comment]
Unsatisfying response on the call. Not sure how we make the decision beyond editorial best judgement?

**Comment by acdha** [comment]
@azaroth42 My $.10 would be to favor keeping the spec simpler. If nobody has contributed a compelling use-case for sizeAboveFull, I would deprecate it.

**Comment by zimeon** [comment]
I have mixed feelings about what the bar should be "simpler" when it comes to removal of something from a spec. There is a cost to the community during the transition even if at some stage in the future the result will be simpler. It still seems to me that there are hints of possible use cases, even if they didn't get articulated well on the call. I'd wait for more clarity at the moment.

**Comment by zimeon** [comment]
See thread on [IIIF Discuss](https://groups.google.com/forum/#!topic/iiif-discuss/NSG0tGssSUw) which has mixed input

**Comment by azaroth42** [comment]
Eds agree to defer and re-assess in Image 3.0 discussion to see how usage over the 2.x has gone.  Currently there are good arguments both for and against.

**Comment by jpstroop** [comment]
General consensus on 31 Jan 2018 community call is that this is still OK, and simplifies semantics around #1370

**Comment by azaroth42** [comment]
closed by #1423
