### ISSUE TITLE
Update Shared Canvas model documentation

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#719]
... to include 2.0 and 2.1 additions, update style and references.
Getting this done should not be considered a blocker for the Presentation API.

**Comment by azaroth42** [comment]
Question as to timing with the Web Annotation WG model. Might not need to wait for it to come out as the only real interaction is the sc:painting motivation, which will stay the same.

**Comment by jpstroop** [comment]
:+1: maybe there will be a lull in spec work (hah!) after prezi and image 2.1, and search and auth 1.0.

**Comment by zimeon** [comment]
:+1: also, but I think immediate priorities after image 2.1, prezi 2.1 and search 1.0 will be auth 1.0 and then av wg setup and 0.1 (is that a lull?)

**Comment by zimeon** [comment]
Eds meeting: we do not think this is a blocker for release of Presentation 3.0 and we do not think that it can be done on that scheduled. Marking defe.

**Comment by azaroth42** [comment]
Closing can't be bothered fixing.
