### ISSUE TITLE
Allow linking from AnnotationList to target(s) of Annotations

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#754]
In the typical IIIF interaction pattern (maybe get Collection(s), get Manifest, follow links to AnnotationList(s)) there's little need for a link from the List to the target Canvases (or other resources that are annotated).  However when the client starts with a Layer or other description of a set of AnnotationLists, it would be useful to know which lists should be dereferenced.

In the Shared Canvas model there is a `sc:forCanvas` predicate that accomplishes this for annotation lists, where the annotations target a Canvas. This could be made more generic for annotation lists in general.

From iiif-discuss: https://groups.google.com/forum/#!topic/iiif-discuss/4VRhNoblMGI

At this stage, given the relative new-ness of the discovery/notification work and the timeframe for finalizing 2.1 ... I propose `defer` until 2.2/3.0 when the experimentation in this space will have revealed more best practices.

**Comment by zimeon** [comment]
See also #758, looks like one solution might address both

**Comment by azaroth42** [comment]
Still propose `defer`

**Comment by azaroth42** [comment]
Discussion 08/30:  Still an issue, but not a pressing one that we need to solve right now.

**Comment by azaroth42** [comment]
Per discussion at Toronto, there are practically no limits on the different types of feature that one might want to summarize in the AnnotationCollection, all of which can be easily justified with use cases. For example:

  * Annotation Target:  All of the annotations about a particular canvas, regardless of where they're stored, so the client can render them.
  * Annotation Body Language:  All of the English annotations, as that's the language of the user
  * Annotation Body Format: All of the MP4 annotations, as you only support that format
  * Annotation Body Type: All of the Image annotation, in order to render them first
  * Annotation Audience: All of the annotations intended for scholars, as that's who the user is
  * Annotation Motivation: All of the painting annotations

And so forth.  At which point, it simply becomes a set of canned queries, and the effort should be put into making the Search API more robust.

I propose close `wontfix`.

**Comment by tomcrane** [comment]
> effort should be put into making the Search API more robust.

... in particular, level-0-style **static** search results. The problem then is how the client discovers what may be requested.

**Comment by tomcrane** [comment]
IIIF AV - Propose close, for reasons above, and needs, we think, can be met by #762
