### ISSUE TITLE
How best to version 0.x.y to maintain history?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#821]
Sensibly, we don't track patch level versions and just edit in place.
However, in 0.9 for both search and auth, there were significant changes at "patch" levels which then disappear.  As the process converges on a 1.0 spec, the last 0.9.y == 1.0 ... meaning there's just two copies of the same thing.

I think we should have stronger process for our 0.x.y specs, such that significant changes increment the minor version number. So we would currently be at 0.10 for auth, as we were happy with 0.9 using JSONP.

**Comment by azaroth42** [comment]
Close wontfix? 0.x can change dramatically, and we don't need to record everything.

**Comment by zimeon** [comment]
:+1: close, won't fix
