### ISSUE TITLE
Collection @id discrepancy in presentation spec

### ISSUE THREAD

**Issue by workergnome** [IIIF/api#880]
In [section 5.8](http://iiif.io/api/presentation/2.1/#collection) it says:

> An embedded collection ​_SHOULD_​ also have its own URI from which the description is available.

But in [section 3.3](http://iiif.io/api/presentation/2.1/#technical-properties), it says:

> A collection ​_MUST_​ have exactly one id, and it ​_MUST_​ be the http(s) URI at which it is published.

Are embedded collections different than collections in general, or should 5.8 be a **MUST**?

**Comment by azaroth42** [comment]
The SHOULD for embedded collections is to allow for situations where there's a small collection that just subdivides another, but doesn't make sense to have by itself. In this case, it didn't seem like a hard requirement that the subdivision have its own dereferenceable description... hence downgrading from a MUST to a SHOULD.

Does that help?

**Comment by workergnome** [comment]
I understand the use case and it makes sense.  This is just me being persnickety about the standard.  As an implementer, it's unclear which of those two statements take precedence—they're both very clear, but they appear to contradict each other.  Apparent contradictions bother me. 😞 

This is the Slack conversation that got me thinking about this:

> benwbrum: One use case I've run into making FromThePage a client of the IIIF collection interface is the need for a client reading collections to display breadcrumbs, taking the user "back"/"up" from the collection they're viewing to some parent collection.  So that may be difficult if a collection ID which is used in the `within` block of another collection isn't resolvable as a URL.
> benwbrum: I'm not seeing them, I'm just suggesting that if you make unresolvable parent collection IDs, any child collections won't be able to navigate back.

So, a potential use case:

If we have a collection `top`, and an embedded collection within that `impressionism`, and a manifest within that `Wheat Fields after the Rain`. 

When browsing `top`, there's no need for `impressionism` to have a dereferencable URL, because all content is embedded. But when viewing `Wheat Fields after the Rain`, it's `within` statement should point to `impressionism`, but there's not a dereferencable URL for it, and there's no way to discover it (other than relying on the magic `top` collection).

*(This is not a breaking issue, and I'm happy to let it go.  Just wanted to write the thought out and get it filed somewhere.)*

**Comment by azaroth42** [comment]
I concur with @workergnome's assessment. If there's an "anonymous" collection in the hierarchy, you can't (by definition) refer to it from elsewhere. So where does the Manifest say it is within?  You just can't do that? And if so, we should be clear about that in the within documentation?

**Comment by azaroth42** [comment]
> A Collection must have exactly one id, and it must be the http(s) URI at which it is published.

Could be expanded to say:

> A Collection MUST have exactly one `id`, and it must be the http(s) URI at which it is published, if it is separately available.  Collections that are not available via HTTP SHOULD NOT have an `id`.

Ooops for missing this in the 2.1.1 spec release!

**Comment by azaroth42** [comment]
Discussion 8/2/17:  Requiring an embedded collection to have an `id` makes them less useful, and more overhead to support.  Extra effort to make them resolvable.
Converse:  Makes it less consistent with other decisions where we've required `id`.  Would allow manifests to be `within` them, even if they're not resolvable. 

No firm consensus, nor strong disagreement. Discuss in Toronto.

**Comment by zimeon** [comment]
Agreed at Toronto WG meeting that we will be consistent in requiring ids, allow fragment ids, along the lines of:

> A collection ​_MUST_​ have exactly one `id`, and it ​_MUST_​ be the http(s) URI at which it is published. The `id` _MAY_ be fragment URI.

**Comment by azaroth42** [comment]
Closed by #1307.
