### ISSUE TITLE
Clarify service dereferencability of @id

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#893]
Should have an @id, and if so it should be dereferenceable, and if so it should? return JSON-LD.

Except that none of the auth services return JSON-LD, and shouldn't be expected to.
We need to distinguish between descriptive information (like geo, physical dimensions etc) and temporary interaction information like auth tokens where there's no point in caching the response.

**Comment by azaroth42** [comment]
Propose to close in favor of #1269.

**Comment by tomcrane** [comment]
👍

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
:+1:
