### ISSUE TITLE
Allow more HTML tags

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#897]
Any reason why we omitted these from the list of do-not-strip tags?

From: DDMAL/tripoli#2

**Comment by jpstroop** [comment]
Because they're semantic? Should use  <b> and <i> instead.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by ahankinson** [comment]
As of HTML5 `b` and `i` have (backwards) gained semantic meaning... 

"In earlier versions of the HTML specification, the <i> tag was merely a presentational element used to display text in italics, much like the <b> tag was used to display text in bold letters. This is no longer true, as these tags now define semantics rather than typographic appearance. The <i> tag should represent a range of text with a different semantic meaning whose typical typographic representation is italicized.  This means a browser will typically still display its contents in italic type, but is, by definition, no longer required to."

[Source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i)

**Comment by zimeon** [comment]
I hate the idea of a long discussion of the semantic-ness or not of HTML tags. Of course, we don't specify which version of HTML is embedded in IIIF responses, so with multiple (semantically) incompatible versions out there it is all a bit fuzzy anyway. 

We currently have a pretty limited set of elements allowed [a, b, br, i, img, p, and span](http://iiif.io/api/presentation/2.0/#property-values-in-html). If we are to consider `em` and `strong`, should we also be considering other things like `sup`, `sub`, `small`?

**Comment by ahankinson** [comment]
I wasn't trying to start a long boring discussion, no worries. :)  

I think `sup`, `sub` and `small` are good candidates for inclusion as well. Or, we restrict it to just linking (`a`) and be done with it.

**Comment by jpstroop** [comment]
>  text with a different semantic meaning whose typical typographic representation is italicized.

Sounds very fuzzy (are they semantics or are they typographic representation?)

Whatever, I'd :+1: allowing for `sup`, `sub` and `small` in the next release. Certainly not a breaking change.

**Comment by azaroth42** [comment]
Proposal:  Allow `sup`, `sub` and `small` along with current set. Don't add `em` and `strong` (re long boring semantic vs typographic discussion).

**Comment by mikeapp** [comment]
👍 the proposal

**Comment by tomcrane** [comment]
:+1:

**Comment by ahankinson** [comment]
Potentially also allow headings (`h1-6`). This is useful for larger blocks of description text.

**Comment by zimeon** [comment]
:+1: at Toronto WG meeting, will add `sup`, `sub` and `small` to list of allowed tags.

Some discussion of explicitly allowed tags vs a set of disallowed tags. Agreement that a list of allowed tags is the safer approach and a key purpose of restricting the set of tags is to ensure that clients can safely display compliant content. Should perhaps discuss other tag additions.

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#html-markup-in-property-values

**Comment by zimeon** [comment]
:+1: agree done

**Comment by jpstroop** [comment]
> Tags such as script, style, object, form, input and similar.

Seems a little wishy washy to me. I will try to come up with an explicit list.

**Comment by zimeon** [comment]
I don't think the list to remove can ever be complete... the list to **allow** seems like the key one

> Clients should allow only a, b, br, i, img, p, small, span, sub and sup tags

**Comment by jpstroop** [comment]
Maybe we can just firm up the language in that bullet then:


> Tags such as script, style, object, form, input that may change the behavior of the client.

**Comment by jpstroop** [comment]
> Tags such as script, style, object, form, input and any others that may change the behavior of the client.

(sorry, doing this from my phone)
