### ISSUE TITLE
Reconsider external sequence requirement

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#898]
If we allow the canvases to be referenced from the main sequence, then this is only as much additional information as another range.

(Related to #58, #646)

**Comment by azaroth42** [comment]
From Rafael on -discuss:

> The IIIF Manifest Editor can run locally or on a server and it creates a single manifest.json file that you can then download. This makes me think that we can not support creating multiple sequences in a manifest without the manifest being invalid. 

> What is the rationale behind this rule that additional sequences MUST not embed the canvases? Is it just so that the manifest file does not get too big? If so, would it be possible to consider changing this rule to make it optional, so that additional sequences MAY (instead of MUST) be referred to from the manifest but that canvases CAN also be embedded for additional sequences?

**Comment by Eyal-R** [comment]
This is also a major factor for us. We already implemented and using sequences that have different canvases. Taking out this possibility in IIIF will make this standard less flexible - IIIF should be flexible to allow implementation in different institutions with different needs and methods.
Taking out this possibility - means a sequence is not different than range, and thus one of them should be deprecated. For us, the whole flexibility in sequences (in contrast to ranges) is the ability to use different canvases, like in Rafael's case.

Using IIIF this way, the rationale to prevent the manifest representation getting too large by not embedding the second sequence and on - makes very sense!

Eyal

**Comment by ruthtillman** [comment]
In this case I'd say a sequence is still different from a range in that a range is to be understood as a part of the whole whereas a sequence is considered to be a whole, if not the only whole.

Weighing in with our use cases--it would be very nice, for cases when a sequence was simply a re-ordering, to allow that within the main manifest as an ordering of canvas URIs. However, I wouldn't want to see the possibility of unique canvases in a second sequence deprecated (whether because an existing canvas has different metadata in the second sequence or the sequence includes actual new canvases).

**Comment by benwbrum** [comment]
We're starting a project in which stand-alone sequences might be useful.  The challenge we face is that an external sequence does not necessarily reference the manifest it's a part of.  Is there any use-case prevented by a requirement that a stand-alone sequence MUST contain a `within` element referencing a manifest?

**Comment by zimeon** [comment]
Agreement in Toronto WG meeting to permit multiple sequences in the manifests, but to still permit external references; still requires first sequence to be embedded

**Comment by Eyal-R** [comment]
That's good news, so we wouldn't have to change a lot of implementation to support IIIF v3 (that goes for any institution that implemented external referencing of multiple sequences in a manifest)

**Comment by azaroth42** [comment]
Done:  http://prezi3.iiif.io/api/presentation/3.0/#manifest

**Comment by zimeon** [comment]
:+1: agree done

**Comment by mikeapp** [comment]
👍 also agree done, closing
