### ISSUE TITLE
Make Implementation Notes non-normative

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#928]
As @zimeon points out:

> We use RFC words in the implementation notes in the Image API spec (http://iiif.io/api/image/2.1/#a-implementation-notes) and in the Prezi API spec (http://iiif.io/api/presentation/2.1/#d-implementation-notes). To me it seems inconsistent to switch back and forth.

I think we should get the RFC keywords/requirements out of Notes and into the specs.

(Tagging as defer for now)

**Comment by azaroth42** [comment]
Agreed.

**Comment by zimeon** [comment]
I agree too (perhaps suggested by my quote)

**Comment by zimeon** [comment]
(Removed auth tag  as the [Auth Implementation Notes](http://iiif.io/api/auth/1.0/implementation/) are already a separate document)

**Comment by azaroth42** [comment]
Closed by #1426
