### ISSUE TITLE
Should ranges be able to have non-rectangular regions?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#953]
For example to pick out freeform regions on a large artwork, rather than rectangular regions more typical in printed works like newspapers and books.  Currently regions of canvases for Ranges are required to be xywh associated with the Canvas URI as a fragment.

A region might represent, for example, a set of ships in a naval battle painting, the areas where a story is depicted in a scroll, or the set of rondels in a manuscript illumination for a family tree of the royal family of France.

**Comment by azaroth42** [comment]
AV call of 08/22: No use cases for it on the call. What's available today is good enough for a _presentation_ layer. The use cases all ended up being annotations rather than being needed for ranges.  The cost seems high (lots of additional construction needed) for little value.

AV group proposes close wontfix. Confirm close in Toronto if no further discussion.

**Comment by azaroth42** [comment]
Digirati/Wellcome Quilts as example of this.

**Comment by tomcrane** [comment]
http://ghp.wellcomecollection.org/annotation-viewer/quilt/

**Comment by tomcrane** [comment]
And also http://storiiies.cogapp.com/

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting to defer until after Presentation 3.1 or later

**Comment by azaroth42** [comment]
Given #1338 (etc) we now get this for free, if clients implement it. un-`defer`-ing. PR that closes #1338 etc will also close this.

**Comment by azaroth42** [comment]
Closed by #1500.
