### ISSUE TITLE
Flag to say Do not client-side transmute this content

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#958]
There's currently no way to describe the situation where the content resource (image, audio, video) can be retrieved in its entirety, but the content provider requires clients to not locally change it.  For example, the video or image must not be cropped before rendering to the user.

This can be understood by the user agent and features turned off because of it, so it seems more than just a license term for humans to read.

**Comment by zimeon** [comment]
Brought up as use case with video for NGA. Understanding at meeting that on the open web it is impossible to control for this, but we could have flags that are _MUST_ in the spec and an institution like NGA could select a conforming viewer for internal kiosk use.

**Comment by azaroth42** [comment]
One approach would be to assign a license that says No Derivatives to the resource, such as CC-BY-ND. But this doesn't let clients automatically determine it, and not all resources can be licensed.

**Comment by azaroth42** [comment]
Technologically unenforceable, and we have two slots to record the requirement -- license and attribution (to become requiredStatement) ... closing.  Equally, implement Auth and have a click through license or something more heavyweight.
