### ISSUE TITLE
label on Canvas should be recommended instead of mandatory

### ISSUE THREAD

**Issue by aisaac** [IIIF/api#964]
As per presentation API 2.1 labels are required for canvases.
While having labels is certainly a Good Things, the fact that there are mandatory may tempt manifest publishers to create not-so-useful labels (e.g., language specific abbreviation that indicate the not applicability of the field) and repeat them over many canvases so that their manifests syntactically valid.
At the meeting in The Hague two options were suggested:
- making labels presence strongly recommended (SHOULD) instead of mandatory (MUST) in the spec
- make sure the spec allows for empty labels "" and issue a best practice about this.

Examples of manifests with repeated "N/A" labels (and a derived implementation issue that hopefully will be solved soon) can be found at 
https://app.assembla.com/spaces/europeana-npc/tickets/1661-rendering-iiif-manifests-where-canvases-have-identical-labels/

**Comment by aisaac** [comment]
@azaroth42 @zimeon @blalbrit @jpstroop @mattmcgrattan not being sure anymore about how IIIF issues are handled on github, I've created this and am now flagging this to you. I hope it's not too messy

**Comment by jpstroop** [comment]
@aisaac this is perfect, thanks. :smile:

**Comment by azaroth42** [comment]
I think there's a difference between not present and empty string.  As a client, I would expect to display the value ... if that's an empty string, I would display exactly that.  On the other hand, I would expect to be allowed to create my own label for the canvas if there is nothing specified.

Do we need to account for both?

**Comment by aisaac** [comment]
As we discussed in The Hague it seemed option 1 could be quite a step to make for the specification; and advertising the possibility of using empty strings was less disruptive. Hence this ticket has the two options.

But my preference would be for option 1 (making labels not mandatory) as it's conceptually cleaner, as as you say give more freedom to implementers to do what they think is more appropriate in their context.
If option 1 is possible for the editors, then I'm happy!

**Comment by aisaac** [comment]
As we discussed in The Hague it seemed option 1 could be quite a step to make for the specification; and advertising the possibility of using empty strings was less disruptive. Hence this ticket has the two options.

But my preference would be for option 1 (making labels not mandatory) as it's conceptually cleaner, as as you say give more freedom to implementers to do what they think is more appropriate in their context.

If option 1 is possible for the editors, then I'm happy!

**Comment by azaroth42** [comment]
Confirm in Toronto.

**Comment by azaroth42** [comment]
Discussion in Getty AV: :+1:

**Comment by azaroth42** [comment]
Proposal: `label` on Canvas in 3.0 will be _SHOULD_ not _MUST_.

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting that `label` on Canvas in 3.0 will be SHOULD not MUST. Need to follow up on expected client behaviors

**Comment by azaroth42** [comment]
How do we get to close the issue, regarding client behavior?

**Comment by zimeon** [comment]
From the spec p.o.v. I think this is done as in http://prezi3.iiif.io/api/presentation/3.0/#descriptive-properties we have:

> A Canvas _SHOULD_ have at least one label.
> Clients _MUST_ render label on a Canvas, and _MUST_ generate a label for Canvases that do not have them.

Perhaps we need to ensure review of the client behavior prescription there. As for actual implementation, I think we just have to hope (and work to encourage) client behaviors follows specs.

**Comment by azaroth42** [comment]
We have an issue for the client requirements review. Sufficient to rely on that ine and close this as the spec part?

**Comment by tomcrane** [comment]
Yes, for the spec part. The client requirements review applies across many issues. :+1: to close.
