### ISSUE TITLE
Canvas `@id` dereferencability should remain MAY

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#980]
In Presentation 3.0, what should the requirement for dereferencability of the Canvas `@id` be? It is _MAY_ in 2.x. (Follow on from #884 which fixes inconsistency in table.)

**Comment by azaroth42** [comment]
I propose to leave it the same ... MAY. The cost of requiring dereferencable canvases is very high. The value of SHOULD is very low.

**Comment by benwbrum** [comment]
I'm not clear why we bother with URIs for canvas `@id`s if they are not dereferenceable, but are instead just an index into a manifest document which clients must carry around with them wherever a canvas is reused or annotated.

**Comment by jpstroop** [comment]
> just an index into a manifest document which clients must carry around with them wherever a canvas is reused or annotated

It seems to me that to fulfill this use case alone you would want a globally unique identifier. Is that what you're questioning, or why URIs as opposed to some other scheme, or why we need `@id` at all?

**Comment by azaroth42** [comment]
IIIF-Discuss Thread: https://groups.google.com/d/msg/iiif-discuss/HZtInSSs_8k/mP_dbBxsAwAJ

**Comment by zimeon** [comment]
I think we cannot / don't-want to say MUST because that would be 1) hugely breaking to current implementations & 2) a significant burden for book-like use cases with many canvases. Given that, I think that we may as well stay at MAY.

**Comment by azaroth42** [comment]
Discussion on AV call of 9/5:  Consensus on the AV call is that this should stay as MAY. The cost of making it a MUST is too high, and the difference between SHOULD and MAY is insignificant for protocol level operations. Noted that for AV there are perhaps more interesting use cases of separate canvases from Manifests, involving mashup style content. Propose close won't fix.

**Comment by azaroth42** [comment]
Confirm in Toronto.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting that `@id` dereferencability should remain MAY. Closing at `wontfix`
